### ISSUE TITLE
[addon] addon-actions is not working v6.0.21

### ISSUE THREAD

**Issue by JeffGuKang** [storybookjs/react-native#104]
**Describe the bug**
`crypto.getRandomValues() not supported` error in debug mode.

Related issue: https://github.com/uuidjs/uuid/issues/416
Solution: https://github.com/uuidjs/uuid#getrandomvalues-not-supported

**To Reproduce**

1. Use action addon
2. trigger action addon
3. boom

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/216363/92548298-9e67bd80-f291-11ea-9aae-5bae7cd2e551.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

```
import {action} from '@storybook/addon-actions'

...
<Button onPress={action('onPress')} />
```
**System:**
No related

**Additional context**

**Comment by nidheeshdas** [comment]
I'm facing same issue on a fresh Expo with just `sb init`. No other code changes.

```json
{
"dependencies": {
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@storybook/addon-actions": "^6.0.21",
    "@storybook/addon-essentials": "^6.0.21",
    "@storybook/addon-links": "^6.0.21",
    "@storybook/react-native": "^5.3.21",
    "@storybook/react-native-server": "^5.3.21",
    "babel-loader": "^8.1.0",
    "babel-preset-expo": "~8.1.0",
    "react-is": "^16.13.1"
  }
}
```

**Comment by bitcrumb** [comment]
Same issue.

**Comment by JeffGuKang** [comment]
@nidheeshdas Try `yarn add @storybook/addon-actions@5.3.21`

**Comment by dannyhw** [comment]
@nidheeshdas with storybook for react native you cannot use the v6 storybook libraries because it is not yet supported. 

You should use the latest 5.3 version which at this moment is 5.3.21 like jeff said.

edit-

to clarify 

these dependencies should be using the 5.3.21 version
```
 "@storybook/addon-actions": "^6.0.21",
 "@storybook/addon-essentials": "^6.0.21",
 "@storybook/addon-links": "^6.0.21",
```

**Comment by JeffGuKang** [comment]
> ```
>  "@storybook/addon-actions": "^6.0.21",
>  "@storybook/addon-essentials": "^6.0.21",
>  "@storybook/addon-links": "^6.0.21",
> ```

Thank you. 

```
    "@storybook/addon-actions": "5.3.21",
    "@storybook/addon-knobs": "6.0.21",
    "@storybook/addon-links": "6.0.21", // I am not using this 
    "@storybook/addons": "6.0.21",
    "@storybook/react-native": "5.3.22-alpha.1",
    "@storybook/react-native-server": "5.3.22-alpha.1",
```

It is my case. `actions` and `knobs` are working well with `react-native-server`.

**Comment by dannyhw** [comment]
@JeffGuKang since it's now working I guess I will close this issue, let me know if you want me to open it again :).

**Comment by jonathanm-tkf** [comment]
Same issue

**Comment by dannyhw** [comment]
> @nidheeshdas with storybook for react native you cannot use the v6 storybook libraries because it is not yet supported.
> 
> You should use the latest 5.3 version which at this moment is 5.3.21 like jeff said.
> 
> edit-
> 
> to clarify
> 
> these dependencies should be using the 5.3.21 version
> 
> ```
>  "@storybook/addon-actions": "^6.0.21",
>  "@storybook/addon-essentials": "^6.0.21",
>  "@storybook/addon-links": "^6.0.21",
> ```

@jonathanm-tkf please see my previous comment.

**Comment by DanielRamosAcosta** [comment]
We are havving this same issue at version:

With Expo 40.

```
@storybook/addon-actions@6.1.18
@storybook/react-native@5.3.25"
```

Did you manage to solve the issue @JeffGuKang?

**Comment by dannyhw** [comment]
@DanielRamosAcosta  You cannot use addon-actions v6+ please downgrade the version of @storybook/addon-actions@6.1.18 to 5.3.21.

Version 6 of storybook is not compatible with version 5.3.

**Comment by DanielRamosAcosta** [comment]
Yes! Thanks @dannyhw !

**Comment by simonadenic** [comment]
@dannyhw Just stumbled upon the same issue with v7. 

Here are my dependencies: 
```
    "@storybook/addon-essentials": "^7.5.3",
    "@storybook/addon-interactions": "^7.5.3",
    "@storybook/addon-links": "^7.5.3",
    "@storybook/blocks": "^7.5.3",
    "@storybook/react": "^7.5.3",
    "@storybook/react-webpack5": "^7.5.3",
    "@storybook/react-native": "^7.0.0-alpha.8",
    "@storybook/addon-ondevice-actions": "^7.0.0-alpha.8",
    "@storybook/addon-ondevice-backgrounds": "^7.0.0-alpha.8",
    "@storybook/addon-ondevice-controls": "^7.0.0-alpha.8",
```

**Comment by dannyhw** [comment]
@simonadenic you need to use the alpha version of storybook, i.e not 7.5.3, you would use the latest alpha for 7.6. We added a fix in the 7.6 alpha recently.

**Comment by simonadenic** [comment]
Will try now, thanks a lot for a fast response :)

**Comment by simonadenic** [comment]
Works as expected with 7.6.0-alpha-6, thank you very much! :)
