### ISSUE TITLE
[6.0] CSF support on React Native

### ISSUE THREAD

**Issue by f4z3k4s** [storybookjs/react-native#106]
**Is your feature request related to a problem? Please describe.**
CSF is not yet supported in React Native.

**Describe the solution you'd like**
CSF is supported in React Native.

**Describe alternatives you've considered**
I can use `storiesOf` which is great, but as I am rendering storybook also on web (where I use and would like to use CSF), I get errors like this: `Illegal mix of CSF default export and storiesOf calls in a single file: ../../../../stories/Buttons/Button/Button.stories.tsx` all the time.

**Are you able to assist bring the feature to reality?**
Yes, I can, if you point me towards the solution.

**Additional context**

**Comment by dannyhw** [comment]
Hey @f4z3k4s you're right currently csf isn't supported for react native storybook. I think this is something that will be added as part of v6. Currently the work for v6 hasn't started but I'm planning to start it once things are more stable and I have some time available.

For now stick with storiesOf to avoid issues :).

**Comment by dannyhw** [comment]
Partial support for CSF is now in the next-6.0 branch (not yet finished). Will continue this work after some cleanup in the repo.
