### ISSUE TITLE
'cannot GET /iframe.html ' and keeps loading.

### ISSUE THREAD

**Issue by joielee09** [storybookjs/react-native#108]
**Describe the bug**
'cannot GET /iframe.html ' and keeps loading.
I found some issues related to this problems but got no explicit solutions.

**To Reproduce**
Followed the steps from 'Learn storybook for React Native'
https://www.learnstorybook.com/intro-to-storybook/react-native/en/get-started/
1.Setup React Native Storybook -> ok
2.Setup Jest with React Native -> while I was following the tutorials I cannot get the image of 'yarn storybook'. Instead it throws 'cannot GET / iframe.html' error.

**Expected behavior**
Expected the image in the middle
![app-three-modalities-rn](https://user-images.githubusercontent.com/67178982/93705090-5ed48780-fb55-11ea-834a-eb319f936361.png)

**Screenshots**
It keeps loading
![1](https://user-images.githubusercontent.com/67178982/93705112-8e838f80-fb55-11ea-8c68-cdab216b2dd6.PNG)
and
![2](https://user-images.githubusercontent.com/67178982/93705113-904d5300-fb55-11ea-91d1-d13bc040783f.PNG)
throws this issue

**Code snippets**

**System:**

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD     
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.51)
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21
    @storybook/addon-essentials: ^6.0.21 => 6.0.21
    @storybook/addon-links: ^6.0.21 => 6.0.21
    @storybook/react-native: ^5.3.21 => 5.3.21
    @storybook/react-native-server: ^5.3.21 => 5.3.21
  npmGlobalPackages:
    @storybook/cli: 6.0.21

**Additional context**

**Comment by dannyhw** [comment]
I think we already have several duplicates of this issue so I'm going to close this. Let me know if there is some reason to re-open it.
