### ISSUE TITLE
[Feature request] Add nesting of story tree in React Native

### ISSUE THREAD

**Issue by Gongreg** [storybookjs/react-native#12]
### Work summary
It would help a lot to display story list as a full screen list instead of half screen. Since now the story names are sometimes too long to properly fit the sidebar.

Some people have requested functionality to display a nested tree instead of one level list (#2833). It shouldn't be too difficult to implement (I hope).

The main concern I have is that adding multiple level tree can be a performance issue in RN.

### Where to start

You need to setup CRNA example and try to work on App/OnDeviceUI files. 

### Acceptance criteria

* Stories displayed in full screen instead of a sidebar.
* Stories are nested.

### Who to contact

You can contact me or anyone from contributors in slack.

**Comment by Gongreg** [comment]
@ndelangen I would like to try out web view approach. Lets have a session some time in the future.

**Comment by k-sav** [comment]
Any progress?

**Comment by felixolivares** [comment]
Any updates on this feature ?

**Comment by dannyhw** [comment]
@felixolivares not been developed yet but all PR's are welcome. Working through issues when I can, this is one that I want to fix in 6.0.

**Comment by Katia-Toboleva** [comment]
Hey everyone! Any update on this issue?

**Comment by dannyhw** [comment]
@Katia-Toboleva I've not had time for it yet but its still on my mind to look at it. My idea for this one was to add it after v6 comes out.

**Comment by Katia-Toboleva** [comment]
Hi @dannyhw ! Thanks for an update! Is there any timescale for that?

**Comment by dannyhw** [comment]
@Katia-Toboleva hey, sorry its really hard to give timelines because it just depends on when I have free time or when others want to contribute.

**Comment by Katia-Toboleva** [comment]
Ok, no worries! Thanks for looking after this anyway :)

**Comment by dannyhw** [comment]
please try the new alpha version 6.5.5-alpha.0 which has an implementation of this
