### ISSUE TITLE
Unclear how to properly type stories

### ISSUE THREAD

**Issue by jkepps** [storybookjs/react-native#123]
**Describe the bug**
Neither the docs, the examples, nor the code itself makes it particularly clear how to properly type annotate when creating a story. There is a tsc error when I try to use the `addDecorator` method on `StoryApi`. The call back receives an argument `getStory` that has an `unknown` return type.

**To Reproduce**
1. Create a story using typescript
2. add a decorator
3. observe the `getStory` callback argument has a return type of `unknown`

**Expected behavior**
`getStory` should be able to infer the type or there should be a mechanism for annotating the type

**Screenshots**

**Code snippets**
```jsx
storiesOf('EndOfRewards', module)
  .addDecorator(getStory => (
    <BackgroundGradient>{getStory()}</BackgroundGradient> 
     // Type 'unknown' is not assignable to type 'ReactNode'.
     //  Type 'unknown' is not assignable to type 'ReactPortal'.ts(2322)
  ))
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.6.0 - ~/.asdf/installs/nodejs/14.6.0/bin/node
    Yarn: 1.22.4 - ~/.asdf/installs/nodejs/14.6.0/.npm/bin/yarn
    npm: 6.14.6 - ~/.asdf/installs/nodejs/14.6.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21
    @storybook/addon-knobs: ^5.3 => 5.3.21
    @storybook/addon-links: ^5.3 => 5.3.21
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23
    @storybook/addon-ondevice-knobs: ^5.3.23 => 5.3.23
    @storybook/react-native: ^5.3.23 => 5.3.23
```

**Additional context**

**Comment by jkepps** [comment]
It appears that a simple solution for this is to update the type definition for `storiesOf` to be the following:
```js
export declare const storiesOf:<T = ReactNode> (kind: string, module: NodeModule) => import("@storybook/addons").StoryApi<T>;
```

**Comment by dannyhw** [comment]
Sorry that you've had issues with type support for react native storybook, it's something I want to work on in the project as I have also noticed some issues. Thank you for creating a pr and contributing to storybook, appreciate it 🙏.

Will leave this open until I create a patch version with this fix included.

**Comment by jkepps** [comment]
@dannyhw happy to contribute! will continue to look for more ways i can help out 🙂

**Comment by dannyhw** [comment]
Published:
 - @storybook/addon-ondevice-knobs@5.3.24-alpha.0
 - @storybook/react-native@5.3.24-alpha.0

### Bug Fixes

* size of radios is inconsistent with other knobs (#118)
* type annotation for storiesOf method (#124)
* ondevice select knob undefined value causes key error (#111)
* reset groupId in selectStory handler (#137)

Your change is live now in 5.3.24-alpha.0
