### ISSUE TITLE
Native knobs:  Knobs disappear when using group ids

### ISSUE THREAD

**Issue by har0ld-scl** [storybookjs/react-native#126]
**Describe the bug**

Using knobs with different group ids between stories causes the knobs of the other stories to not load or display properly.

**To Reproduce**

1. Create a pair of stories (story A and story B). 
2. Add some knobs to both stories.
2. Set different groupId names on those knobs.
3. Open story A and click on one tab (group) that doesn't exists in story B.
4. Open story B.
5. The knobs of story B disappear.

**Expected behavior**

Using different group ids on the knobs should not interfere with the loading of the knobs from other stories.

**Screenshots**

![storybook-knobs-disappear](https://user-images.githubusercontent.com/61238804/97756911-7a2e9d00-1ada-11eb-8b4f-2e7de27946a6.gif)

**Code snippets**

```jsx
storiesOf('First component', module)
  .add('First example', () => (
    <View>
      <Text>{text('message', 'Hello first example!', 'Click me')}</Text>
    </View>
  ))
  .add('Second example', () => (
    <View>
      <Text>{text('message', 'Hello second example!', 'Missing tab')}</Text>
    </View>
  ));
```

**System:**
Environment Info:

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: 6.0.27 => 6.0.27
    @storybook/addon-knobs: 6.0.27 => 6.0.27
    @storybook/addon-ondevice-actions: 5.3.23 => 5.3.23
    @storybook/addon-ondevice-knobs: 5.3.23 => 5.3.23
    @storybook/react-native: 5.3.23 => 5.3.23
    @storybook/react-native-server: 5.3.23 => 5.3.23
```

**Additional context**

The groupId tab that doesn't exists in the other stories must be active to reproduce the issue.

This occurs both on android and ios either both dev and release mode.

**Comment by dannyhw** [comment]
Thats a strange issue, thanks for reporting this, will look into it when I can.

**Comment by dannyhw** [comment]
Published:
 - @storybook/addon-ondevice-knobs@5.3.24-alpha.0
 - @storybook/react-native@5.3.24-alpha.0

### Bug Fixes

* size of radios is inconsistent with other knobs (#118)
* type annotation for storiesOf method (#124)
* ondevice select knob undefined value causes key error (#111)
* reset groupId in selectStory handler (#137)

Your change is live now in 5.3.24-alpha.0
