### ISSUE TITLE
Storybook server continuously changing story variant

### ISSUE THREAD

**Issue by chasepoirier** [storybookjs/react-native#127]
**Describe the bug**
When clicking through story variants somewhat quickly (<2s) the server begins to continuously change the active variant without clicking anything new. Only resets once the page has been reload.

**To Reproduce**
1. Open a story with multiple variants
2. Click between variants quickly
3. See server begin changing variants on its own

**Expected behavior**
Clicking quickly between story variants should not continue changing variants once I've stopped changing the variant.

**Screenshots**
![sb-bug](https://user-images.githubusercontent.com/23040747/97910331-979c7a80-1d17-11eb-9b42-df7276a3715f.gif)

**System:**
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 80.0.1
    Safari: 14.0

**Additional context**
Running in a yarn workspace but not sure if that matters

**Comment by dannyhw** [comment]
I would want to see a v6.5 reproduction to be able to investigate
