### ISSUE TITLE
React native Storybook 6.5

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#131]
**Is your feature request related to a problem? Please describe.**

Update react native storybook with the new api changes from storybook 6.0 and improvements.

**Describe the solution you'd like**

- [x] csf support
- [x] main.js/preview.js config style supported
  - [x] support for importing stories automatically
- [x] args
- [x] controls
- [x] Improved docs and tutorial 
- [x] server for v6
- [x] Improved typescript support (would be nice)
- [ ] tests (at least unit tests)
- [x] developer experience improvements for contributors

6.0 bug fixes :

- [x] remove deprecated components in favour of community components such as datetime picker (fixes react-native-web issues)

**Additional context**

Please use this issue for discussion on 6.0 such as suggestions or questions about its development.

Now released, checkout the blog: https://storybook.js.org/blog/storybook-for-react-native-6-5/

**Comment by ivan-khr85** [comment]
Please, add support for React v17.0 and React-Native v0.64

**Comment by dannyhw** [comment]
@ivan-khr85 hey, yeah I haven't had a chance to check this however I don't see any reason it wouldn't work. I will update the examples to 0.64 when I get a chance and check it out.

Did you already try it and had issues or something?

**Comment by pang0018** [comment]
@dannyhw  One issue I am running into is thatReact-Native 0.64 uses the the latest of @testing-library/jest-native which breaks Storyshots (see [thread](https://stackoverflow.com/questions/61706963/typeerror-require-requireactual-is-not-a-function). Getting React Native storybook to version 6.x should resolve the issue.

**Comment by dannyhw** [comment]
For more information please see the comments I made in this PR #135

**Comment by dannyhw** [comment]
Tasks have been split into smaller parts that are tracked in the 6.0 project [here](https://github.com/storybookjs/react-native/projects/2) 
#164 auto import stories
#166 update version of repo to 6.0 
#167 update storybook dependencies
#168 update react native to 0.64.1 and react to 17
#169 update dependencies for ondevice addons
#170 add react-native-web example

**Comment by dannyhw** [comment]
CSF Support and ARGs are now complete with #175 being merged

**Comment by dannyhw** [comment]
The first basic iteration of ondevice controls was added with #182 along with more of the declarative config features.
The first alpha of 6.0 will be created once the issues in the first milestone are completed https://github.com/storybookjs/react-native/milestone/1

**Comment by dannyhw** [comment]
Now that all the issues in the first milestone have been completed I have released the first alpha.

I've also created an initial guide on how you can get setup with a fresh project. Migration guide to come in the future.

Find the guide here:
https://github.com/storybookjs/react-native/blob/next-6.0/v6README.md

**Comment by trajano** [comment]
Can you make the list a checklist style

[ ] e.g.
[x] so it looks nicer.

Also can you add the following to the list?
[ ] migration guide

**Comment by dannyhw** [comment]
> Can you make the list a checklist style
> 
> [ ] e.g.
> [x] so it looks nicer.
> 
> Also can you add the following to the list?
> [ ] migration guide 

Sure if that's useful I can update it like that 👍

**Comment by avertin** [comment]
With version 6, how do you embed storybook inside an existing RN application? Where should the main.js, preview.js and storybook.require.js files go?

**Comment by dannyhw** [comment]
> With version 6, how do you embed storybook inside an existing RN application? Where should the main.js, preview.js and storybook.require.js files go?

@avertin That all works basically the same, the only difference is that the folder is now `.storybook` by default (added a `.`) . You still get a component returned from a getStorybookUI function call.

**Comment by xiongemi** [comment]
when is the official 6.0 going to be released? would it be using webpack 5?

**Comment by dannyhw** [comment]
> when is the official 6.0 going to be released? would it be using webpack 5?

react native storybook doesn't use webpack so I don't know if that would matter much.

In regards to react-native 6.0 release date
I would love to give a timeline but it's hard because it depends a lot on my free time. It will come out when it's ready, hopefully early next year. I'm likely going to be without a computer in December so that will delay things a bit.

**Comment by ramykl** [comment]
Any updates on this?

**Comment by dannyhw** [comment]
@ramykl 
> Any updates on this?

Currently working on getting 6.4 storybook dependencies working. Once that's done probably the first stable version will not be far off. I'm leaning on the side of releasing asap and adding other missing features over time.

**Comment by nicolascgarcia** [comment]
Hi, I would like to know if is there any date setted to release the new stable version?

**Comment by dannyhw** [comment]
@nicolascgarcia i would love to release a version but currently I'm at a bit of a blocker. 

In order to support 6.4 and 6.5 versions of storybook a large rewrite of internals is necessary. A lot of that work is done but I've run into some problems which need help from other maintainers and so I've pairing on it a bit but its hard to organise.

Its hard to say because I don't have a lot of free time and external factors are involved. I plan to release the stable version as soon as it works with 6.4/6.5 and has been tested.

**Comment by trajano** [comment]
@dannyhw  I think what you have at the moment is good as an interim release so we can baseline and add 6.4/6.5 versions later.  As the saying goes, "Don’t Let “Perfect” Be the Enemy of “Good"

**Comment by dannyhw** [comment]
@trajano sorry for the late response here. I appreciate the encouragement and the sentiment here. There are a few things close to coming to fruition that i wanted to wait on. However I'm becoming more likely to ship as time goes on.

I had some positive talks recently with some core storybook maintainers that made it seem like progress is imminent which is something i need to follow up on again essentially. 

I know this has been a really drawn out update so I appreciate the patience and I understand those questions about a release date. It's on my mind a lot so I promise its going to happen sooner or later.

**Comment by dannyhw** [comment]
Update 

- new version will be 6.5.14 not 6.0, this is because new changes were needed in storybook to make react native work and that was introduced in 6.5.14 and therefore you must use a minimum of storybook version 6.5.14.
- Compatibility with 6.5+ however means 6.4 and below won't work without patches.
- I've now written a new tutorial for v6.5 and its under review
- new sb init command with v6.5 support
- server support has been added for v6.5
- experimental support for auto arg types

New release is pending tutorial approval, documentation updates and a blog post for the release.

Thanks to everyone for your patience, a lot of weekends and late nights have gone into this release and whilst it taken longer than anyone wanted (me included), we're finally getting there.

**Comment by dannyhw** [comment]
A note on v7:

As you may know v7 of storybook (web) is coming out soon, and whilst that might seem to be an issue for React Native I'm actually hopeful that we can get a V7 out in the coming months. The reason is that in the recent changes for 6.5 support a lot of changes were made that make React Native more compatible with ReactJS Storybook, even re-using a lot of the setup code (preview-web). I don't want to make premature promises, but I think we'll see a v7 within a reasonable time frame.

V7 will be a big release because it will likely solve other issues we've had such as polyfills polluting the global namespace (corejs promises I'm looking at you) and on demand story loading could be a possibility.

The difficult part will be getting react native to work with storystore v7 since the old store is deprecated. However I know a few people that can help me get that done so I'm hopeful.

**Comment by stevoland** [comment]
Thanks again for your massive efforts. v6 is a banger!

**Comment by alex1092** [comment]
@dannyhw If you need some help with any specific tests hit me up, be glad to look into it

**Comment by dannyhw** [comment]
@alex1092 

v6 (6.5) is ready I'm just getting the release blog and tutorial reviewed whats left is basically updating the template projects, starter projects and documentation.

For example migration guide and also double checking all the github documentation. Seems like we'll get the bottom panel for addons in too

I still need to update these templates

~https://github.com/dannyhw/react-native-template-storybook~
~https://github.com/dannyhw/react-native-storybook-starter~
~https://github.com/dannyhw/expo-storybook-starter~
~https://github.com/dannyhw/expo-template-storybook~

There is also all the documentation on this repo that needs double checking to make sure its up to date for 6.5

The migration guide is the next big documentation step I think

**Comment by dannyhw** [comment]
Heres an interesting issue to pick up for you @alex1092 

https://github.com/storybookjs/react-native/issues/377

Basically having an error boundary to show an error message instead of crashing.

**Comment by dannyhw** [comment]
I've updated expo templates now and the migration guide. I also tried to update a few more pieces of documentation. Any proof reading very appreciated 🙏

**Comment by dannyhw** [comment]
React native cli templates are updated, and release is planned for April 5th if all goes well.

**Comment by dannyhw** [comment]
more details to come soon :)

Thanks everyone for your support, its been a journey.

**Comment by dannyhw** [comment]
https://storybook.js.org/blog/storybook-for-react-native-6-5/

**Comment by douglasjunior** [comment]
I'm trying the storybook 6 right now, but I'm getting these errors: https://github.com/storybookjs/storybook/issues/15067

> TypeError: (tag.text || "").trim is not a function

Maybe related to type inheritance like this:

```ts
export type CustomTextProps = TextProps & {
    /// ...
};
```

My project was created by `npx react-native init StoryBook6Example --template react-native-template-storybook`.

EDIT:

Fixing this version on my package.json solves the issue: https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-1032805986

```json
  "resolutions": {
    "react-docgen-typescript": "2.2.2"
  }
```

**Comment by dannyhw** [comment]
@douglasjunior hey thanks for sharing your solution. Yes the docgen stuff can have some issues with extending types from libraries. If you have more problems you can also just remove the docgen and manually set your argtypes since docgen for react native storybook is somewhat experimental

**Comment by douglasjunior** [comment]
@dannyhw seems that the source of the problem is the `babel-plugin-react-docgen-typescript` that depends on `react-docgen-typescript` 1.x.

The last version of `babel-plugin-react-docgen-typescript` was about 3 years ago.

**Comment by dannyhw** [comment]
@douglasjunior yeah this is why its kinda experimental because the real solution would require developing a new babel plugin or converting the webpack plugin that core storybook uses to work somehow with metro.
