### ISSUE TITLE
Storybook Core versions

### ISSUE THREAD

**Issue by pjivers-bom** [storybookjs/react-native#140]
When you say:
> The last stable version of @storybook/react-native is 5.3.23 and it should be used with 5.3 versions of Storybook Core.

Do you mean that Storybook Core versions should be `5.3.0` or `5.3.x`? I'm assuming the latter but it's not 100% clear to me.

**Comment by dannyhw** [comment]
Basically if you install a storybook package make sure it doesn't install the 6.0 or higher version. Take the latest version from 5.3.x where x is what the latest minor version.

So if a storybook package like @storybook/addons has a latest version of 6.0 don't use that version instead use the latest minor version from 5.3 onwards, for example if the latest version before 6.0 for that package is 5.3.21 then use that.

`5.3.21` ✅
`~5.3.21` ✅

Don't use 

`6.0.0` ❌
`~6.0.0` ❌
`^6.1.0` ❌
`~6.1.0` ❌

Just make sure that none of you storybook dependencies are resolving to 6.0 or higher, you can check in yarn.lock to make sure.

**Comment by dannyhw** [comment]
If you can think of a better way of explaining it I'll happily update the readme to be more clear. I had a hard time figuring out the best way to explain it 😅.

**Comment by dannyhw** [comment]
@pjivers-bom were you able to figure it out?

**Comment by dannyhw** [comment]
Closing due to no response.
