### ISSUE TITLE
Events are not recorded if we quickly access the 'Actions' section.

### ISSUE THREAD

**Issue by LeonardoRepetto** [storybookjs/react-native#141]
**Describe the bug**
When I press a button using delaypressOut with TouchableHighlight or TouchableOpacity and move very fast to 'Actions', the OnPress event is not logged, but if I wait a few seconds after clicking, the action is logged successfully.

**To Reproduce**
1. Create a button with delayPressOut in 1000 and TouchableHighlight or TouchableOpacity.
2. Click the button and move fast to see the 'Actions'.
4. OnPress event is not logged, it doesn't matter when you wait.

**Expected behavior**
The OnPress event should be registered.

**Screenshots**
![Example](https://s7.ezgif.com/save/ezgif-7-a2c7fe58aee4.gif)

**System:**

  OS: macOS 10.15.7
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Binaries:
  Node: 15.0.1 - /usr/local/bin/node
  npm: 6.14.8 - /usr/local/bin/npm
Browsers:
  Chrome: 86.0.4240.193
  Edge: 86.0.622.63
  Safari: 14.0
npmPackages:
  @storybook/addon-actions: 5.3.18 => 5.3.18 
  @storybook/addon-knobs: 5.3.18 => 5.3.18 
  @storybook/addon-ondevice-actions: 5.3.18 => 5.3.18 
  @storybook/addon-ondevice-knobs: 5.3.23 => 5.3.23 
  @storybook/addons: 5.3.18 => 5.3.18 
  @storybook/react-native: 5.3.23 => 5.3.23 
  @storybook/react-native-server: 5.3.18 => 5.3.18

**Comment by dannyhw** [comment]
Hey thanks for reporting this, will investigate when I can :)
