### ISSUE TITLE
addDecorator() argument typing.

### ISSUE THREAD

**Issue by s5unanow** [storybookjs/react-native#142]
Have a problem with TypeScript using addDecorator() function
![image](https://user-images.githubusercontent.com/58434753/101589577-65a2c600-39f1-11eb-96b5-50ff8edb720f.png)

So there probably should be a way to add typing to addDecorator() argument. 

Managed to solve adding an interface to CenterView component like that
![image](https://user-images.githubusercontent.com/58434753/101589726-b0244280-39f1-11eb-96ba-d8720859971a.png)
But it's probably a workaround, not a complete solution.

**Comment by dannyhw** [comment]
Hey thanks for creating this issue, this is something I myself have run into so I understand how annoying it can be. My workaround is usually to do `(story:any)` on the decorator rather than changing the components prop typing. Ideally storybook shouldn't change the way you use your component. 

Anyway this will get fixed, however I'm focused on 6.0 now so it might have to be with that release.

**Comment by MorelSerge** [comment]
Also running into this issue, anyone found a decent workaround?

**Comment by dannyhw** [comment]
Can you check with the latest version 5.3.25?

**Comment by StampixSMO** [comment]
@dannyhw typing changes, but not fixed :/
![image](https://user-images.githubusercontent.com/79153163/109300215-89c6b400-7836-11eb-8aa5-d67b496059ae.png)

**Comment by dannyhw** [comment]
Ok well it seems like I need to take another look at it, thanks for letting me know. If anyone want to take this one I'm open to PR's :)

**Comment by chitra591** [comment]
> Ok well it seems like I need to take another look at it, thanks for letting me know. If anyone want to take this one I'm open to PR's :)

@dannyhw - I could give it a try :)

**Comment by dannyhw** [comment]
@chitra591 that would be great, if you need any help I'm available :). If you want to chat you can find me in the react-native channel on the discord: https://discord.gg/sMFvFsG

**Comment by flexbox** [comment]
Hey @s5unanow 

This issue looks a bit old, there is a new [way to add decorators now](https://www.youtube.com/watch?v=4yi_yCTkgng) compatible with storybook 6.5 and the last CSF syntax.
Do you think you can upgrade and close this issue?

**Comment by s5unanow** [comment]
Hey @flexbox , thanks for updating.
As for now I am not able to test given functionality, but much appreciate it has been solved.

Closing this issue.
