### ISSUE TITLE
In Expo 41 the app never loads due to promise not being fulfilled

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#159]
**Describe the bug**

Due to #20 the expo loading screen never goes away probably because it's waiting for a promise to resolve.

**To Reproduce**
1. expo init APPNAME
2. npx -p @storybook/cli sb init --type react_native
3. add `export {default} from "./storybook"` in app.tsx
4. app never loads

**Expected behavior**
App should load and promises should resolve correctly

**Additional context**
If you comment out line 11 in node_modules/@storybook/addons/dist/index.js you can see that the issue stops 
`//require("core-js/modules/es.promise"); `

This requires a more permanent solution of course but this illustrates the problem.

**Comment by dannyhw** [comment]
I've been talking with the storybook maintainers about a possible solution to this. Ideally there would be a modern build of storybook/addons available or atleast one without the es.promise polyfill. 

Recently i.e11 support was separated out into a separate repo so this could make it possible to provide a solution without the promise polyfill since ie.11 is the only browser without support for promises.

**Comment by dannyhw** [comment]
A [PR](https://github.com/storybookjs/storybook/pull/14954) was created on the main storybook repository with a fix for future version of storybook. This means that this issue will be resolved in 6.0 of react native storybook. The PR enables provides a modern version of the distributed files, in your project you would add the following config `resolverMainFields:['sbmodern', 'main']` and the storybook dependencies used would be without polyfils.

**Comment by nickplee** [comment]
A workaround for Storybook 5.3 that worked for me, assuming you're ok with another dependency, was to add the following to my app's `index.js`:

```javascript
import Bluebird from 'bluebird';
global.Promise = Bluebird;
```

**Comment by grahamlyus** [comment]
Thanks for this. I just encountered the same issue in a bare react-native app using expo-font.
