### ISSUE TITLE
[6.0] improve fast reload by refactoring to use function components

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#179]
Based on the react native documentation fast reload works best for function components and will use a full reload for class components. By converting to function components we might be able to improve the fast reload experience.

**Comment by lauriharpf** [comment]
If this work helps get 6.0 out, I would be interested in giving it a go. Made https://github.com/storybookjs/react-native/pull/187 as an example to check understanding of the task & your interest in getting contributions for this.

https://github.com/storybookjs/react-native/issues/186 and my lack of familiarity with the codebase hinder the ability to spot regressions, so some QC would be necessary.

**Comment by dannyhw** [comment]
@lauriharpf for sure you're welcome to take on this issue. Happy to have your contribution 🙂 .

I'll happily provide any assistance and test your changes as required. If you want to discuss anything we can do it here or you can find me in the react native channel of the storybook [discord](https://discord.gg/sMFvFsG).

**Comment by lauriharpf** [comment]
> @lauriharpf for sure you're welcome to take on this issue. Happy to have your contribution 🙂 .

Thank you! 🙂 

Had some spare time and felt like it, so continued this a bit in https://github.com/storybookjs/react-native/pull/189 . Also pushed some minor changes to https://github.com/storybookjs/react-native/pull/187. Joined the discord, let's sync up here or there as needed 👍 .

**Comment by dannyhw** [comment]
This work was completed by @lauriharpf 🙏 . Closing this issue.
