### ISSUE TITLE
Always show the welcome page. How to switch to other pages?

### ISSUE THREAD

**Issue by JessieLiullkk** [storybookjs/react-native#183]
**Describe the bug**
When l  clicked the sidebar, nothing will change.

**To Reproduce**
1. yarn storybook
2. Click on a menu to change page
3. nothing will change

**Expected behavior**
show the page which l clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/37792083/122012193-7ba1a100-cdef-11eb-945f-a0e9c13f98bc.png)

**System:**
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Firefox: 88.0.1
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21 
    @storybook/addon-knobs: ^5.3 => 5.3.21 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.25 => 5.3.25 
    @storybook/react-native: ^5.3.25 => 5.3.25 
    @storybook/react-native-server: ^5.3.23 => 5.3.23 
  npmGlobalPackages:
    @storybook/cli: 6.2.9

**Additional context**
 "react": "16.13.1",
 "react-native": "0.62.3",

**Comment by dannyhw** [comment]
This is the server UI and doesn't have a preview, you must use the ondevice UI to see the stories. You can use the server to control the ondevice UI if you wish to.

**Comment by JessieLiullkk** [comment]
> This is the server UI and doesn't have a preview, you must use the ondevice UI to see the stories. You can use the server to control the ondevice UI if you wish to.

I got it. Thx.
