### ISSUE TITLE
gap at bottom of story list 

### ISSUE THREAD

**Issue by wolverineks** [storybookjs/react-native#184]
my guess is this is caused by `{ marginBottom: 40 }`
https://github.com/storybookjs/react-native/blob/3a199cce9cd8c4563683930247cc1777f02d4399/app/react-native/src/preview/components/StoryListView/StoryListView.tsx#L209

is the marginBottom necessary?

<img width="212" alt="Screen Shot 2021-06-16 at 15 12 36" src="https://user-images.githubusercontent.com/8462274/122301266-4a8ba400-ceb5-11eb-90f8-acb42bdf9708.png">

**Comment by dannyhw** [comment]
@wolverineks could you please provide information about your setup such as the storybook version, which OS and react native version

**Comment by wolverineks** [comment]
os: macos 11.2.3 big sur
react-native: 0.63.4
storybook: @storybook/react-native: 5.3.23

ive only verified this on android emulator, Pixel_3_XL_API_29

**Comment by dannyhw** [comment]
@wolverineks ok thanks I'll test it soon and put a fix probably in 6.0 alpha coming soon-ish.

**Comment by Patil2099** [comment]
I would love to work on this @dannyhw

**Comment by dannyhw** [comment]
@Patil2099 would be very happy to have your contribution 🙇 . Let me know if you need any help 👍

**Comment by Patil2099** [comment]
How to run this example locally I just want to be sure that my changes fix the issue @dannyhw.

**Comment by dannyhw** [comment]
@Patil2099 

first run 
```
yarn bootstrap --core
cd examples/native
```

If for ios run
```
cd ios
pod install
cd ..
```

Then run the bundler manually in examples/native like `yarn start` then in another terminal either `yarn ios` or `yarn android`

if you want to run a watcher for your changes in one of the packages like app/react-native then run `yarn dev` in the root.
