### ISSUE TITLE
Unable to run example provided in the repo for StoryBook v6.0.0-alpha.0

### ISSUE THREAD

**Issue by sanjeevyadavIT** [storybookjs/react-native#194]
**Describe the bug**
I want to setup storybook v6.0.0-alpha.0 on my own code. So I tried running the example present in this repo, but when I'm trying to run, it is giving me an error

**To Reproduce**
1. Go to examples/native folder
2. do `yarn install` in terminal
3. Open Android Emulator
4. Run `yarn android` in terminal
5. Run `yarn start` in another terminal
6. See the error

**Expected behavior**
Storybook should have loaded correctly on Emulator

**Screenshots**
<img width="463" alt="Screenshot 2021-06-29 at 1 46 06 PM" src="https://user-images.githubusercontent.com/13250741/123762382-6133f100-d8e0-11eb-9382-15cf21139671.png">

**Code snippets**
```bash
error: Error: While trying to resolve module `@storybook/react-native` from file `/Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/examples/native/Storybook.tsx`, the package `/Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/app/react-native/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/app/react-native/dist/index.js`. Indeed, none of these files exist:

  * /Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/app/react-native/dist/index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/app/react-native/dist/index.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/node_modules/metro/src/node-haste/DependencyGraph.js:436:17)
    at Object.resolve (/Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
    at _next (/Users/sanjeevyadav/ReactNativeProjects/react-native-storybook-next-6.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:9)
```

**System:**
Environment Info:

 System:
    - OS: macOS 10.15.7
    - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Binaries:
    - Node: 14.17.0 - /usr/local/bin/node
    - Yarn: 1.22.10 - /usr/local/bin/yarn
    - npm: 6.14.13 - /usr/local/bin/npm
Browsers:
    - Chrome: 91.0.4472.77
    - Firefox: 89.0.2
    - Safari: 13.1.3

**Additional context**

**Comment by dannyhw** [comment]
@sanjeevyadavIT hey thanks for raising this however it does seem like you haven't ran the `yarn bootstrap` command in the root of the project. Either run bootstrap or go to the app/react-native folder and run `yarn prepare` and it should run fine.

**Comment by dannyhw** [comment]
also please note that 6.0 is not even remotely ready to use on your own projects 😅

**Comment by sanjeevyadavIT** [comment]
@dannyhw Thanks, running `yarn bootstrap` on main repo worked, and thanks for pointing it out

I have one question, sorry if it sounds silly

I have installed storybook v5 in react-native, and all the dependency are in `devDependency` section in package.json as it will be, my question is, does adding storybook, increase the bundle size in production build???

I am talking specifically all the storybook library, not the stories that I write, as we are using codepush, bundle size is important.

**Comment by dannyhw** [comment]
> @dannyhw Thanks, running `yarn bootstrap` on main repo worked, and thanks for pointing it out
> 
> I have one question, sorry if it sounds silly
> 
> I have installed storybook v5 in react-native, and all the dependency are in `devDependency` section in package.json as it will be, my question is, does adding storybook, increase the bundle size in production build???
> 
> I am talking specifically all the storybook library, not the stories that I write, as we are using codepush, bundle size is important.

it depends, it shouldn't increase bundle size if you don't import those files in the production build, however I personally haven't done testing to confirm that. I recommend doing some tests with your build.
