### ISSUE TITLE
How I deploy Storybook to web with UI like React Web, Left Panel replace Bottom tab.

### ISSUE THREAD

**Issue by TuanKhoi273** [storybookjs/react-native#208]
**Describe the bug**
I build some component in React native Storybook and build to web with Netlify, but UI Web so difficult to see, it has a bottom tab, I want Left panel menu to Easy to change tab like some web Example of StoryBook. 

**Screenshots**
A web I deployed.
<img width="1439" alt="Screen Shot 2021-07-12 at 14 30 52" src="https://user-images.githubusercontent.com/27020077/125248108-e1fdde80-e31d-11eb-85ec-49f14f32a0fc.png">
<img width="1433" alt="Screen Shot 2021-07-12 at 14 31 04" src="https://user-images.githubusercontent.com/27020077/125248121-e629fc00-e31d-11eb-97f4-7689b1a89ad8.png">

A web I want.
<img width="1195" alt="Screen Shot 2021-07-12 at 14 32 27" src="https://user-images.githubusercontent.com/27020077/125248212-035eca80-e31e-11eb-8a79-9def4c3d081a.png">

How I can do this?. Could someone help me?

**Comment by dannyhw** [comment]
@TuanKhoi273 Hey, currently the ui is built more for a device. There will be improvements to the UI for web coming in the future, currently planned for the alpha 3 milestone of 6.0 see #163.

One option is that you could use a web storybook with the react native components and add a config change to the webpack that applies the react-native-web transforms.

**Comment by TuanKhoi273** [comment]
> @TuanKhoi273 Hey, currently the ui is built more for a device. There will be improvements to the UI for web coming in the future, currently planned for the alpha 3 milestone of 6.0 see #163.
> 
> One option is that you could use a web storybook with the react native components and add a config change to the webpack that applies the react-native-web transforms.

Thank you.

**Comment by dannyhw** [comment]
For this you can use @storybook/addon-react-native-web 

http://github.com/storybookjs/addon-react-native-web
