### ISSUE TITLE
[6.0] Remove FunctionComponent type

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#212]
As a follow up on #182 

_Originally posted by @lauriharpf in https://github.com/storybookjs/react-native/pull/182#discussion_r667507872_

We might want to not use `FunctionComponent` or `FC`, as the React core team seems to lean on the side of "don't use it": https://github.com/facebook/create-react-app/pull/8177

We could tackle this by running https://github.com/gndelia/codemod-replace-react-fc-typescript on the codebase.

**Comment by Patil2099** [comment]
I would love to work on this
