### ISSUE TITLE
Using vulnerable package https://www.npmjs.com/advisories/815

### ISSUE THREAD

**Issue by ntucker** [storybookjs/react-native#22]
**Describe the bug**
Versions of `simple-markdown` prior to 0.4.4 are vulnerable to Cross-Site Scripting. See https://www.npmjs.com/advisories/815 for more info

**Comment by Gongreg** [comment]
Hey, are you still getting `simple-markdown` version lower than 0.4.4? Which package are you installing? ondevice-addon-notes or addon-notes?
