### ISSUE TITLE
Vulnerabilities found in dependencies

### ISSUE THREAD

**Issue by cdedreuille** [storybookjs/react-native#227]
**Describe the bug**
I installed the latest version of storybook. It works great locally but I couldn't push it to production as there are some vulnerabilities found in the dependencies on `@storybook/react-native-server`.

**To Reproduce**
1. Install storybook on a react native app
2. yarn audit
3. See error

**Expected behavior**
No errors when testing with `yarn audit`

**Screenshots**
<img width="628" alt="Screenshot 2021-07-15 at 18 24 34" src="https://user-images.githubusercontent.com/1540635/125830815-97ee26a0-3300-4fa0-84b1-638bd3334202.png">

**System:**
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 16.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21 
    @storybook/addon-knobs: ^5.3 => 5.3.21 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.25 => 5.3.25 
    @storybook/react-native: ^5.3.25 => 5.3.25 
    @storybook/react-native-server: ^5.3.23 => 5.3.23

**Comment by dannyhw** [comment]
Thanks for reporting this, I'll try to make sure we keep the audit clean in future versions 🙏 .

In terms of updating the old versions of packages from 5.3 it depends on if I can find time to do that.
