### ISSUE TITLE
Compare functionality of ondevice-controls to the web version

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#236]
We should compare the functionality that we have currently and raise issues for any disparity between the two.

Ideally we would have all the same functionality, or at least the majority.

**Comment by jestupinanb** [comment]
I am not completely sure if that is something related to ondevice-controls addon but when I create a story on the web version by default all the props are shown and the mobile version only shows the props that I have added in the .args
![image](https://user-images.githubusercontent.com/30636279/186998723-46e35413-dadc-47ef-8057-7871283203b7.png)
![image](https://user-images.githubusercontent.com/30636279/186998775-cfcb7143-ec2f-415b-94be-a99496266bca.png)
![image](https://user-images.githubusercontent.com/30636279/186998867-48d9b036-3df3-45ea-a2f2-360565e89bb0.png)

**Comment by dannyhw** [comment]
Heres how you can make automatic args work:

https://dev.to/dannyhw/automatic-args-in-react-native-storybook-140a

**Comment by dannyhw** [comment]
at the risk of being wrong I think theres nothing left to fix here, we can always adjust in the future.
