### ISSUE TITLE
2 warnings in new example project, require cycle and duplicate decorator

### ISSUE THREAD

**Issue by leotm** [storybookjs/react-native#240]
**Description**

2 warnings in new project

**To Reproduce**

1. Fork/clone this repo
2. `yarn`
3. `yarn bootstrap`
4. `cd examples/native`
5. `cd ios && pod install && cd ..`
6. (Revert `project.pbxproj` to run on M1)
7. `yarn start --reset-cache`
8. `yarn ios`
9. 2 warnings present
10. Remove cause (details below)
11. `yarn start --reset-cache`
12. `yarn ios`

_Or_

1. Clone https://github.com/leotm/react-native-template-typescript (@storybook/react-native@5.3.25)
2. Update `App.tsx` line 117 for storybook
3. `yarn`
4. `cd ios && pod install && cd ..`
5. `yarn start --reset-cache`
6. `yarn ios`
7. 1 warning present
8. Remove cause (details below)
9. `yarn start --reset-cache`
10. `yarn ios`

**Expected behavior**

No warnings

**Screenshots**

2 Warnings

1 `WARN Require cycle: ../../node_modules/util/util.js -> ../../node_modules/util/node_modules/inherits/inherits.js -> ../../node_modules/util/util.js](https://github.com/facebook/metro/issues/287`

https://github.com/facebook/metro/issues/287

2 `WARN You tried to add a duplicate decorator, this is not expected [Function anonymous]`

![Screenshot 2021-07-18 at 20 52 28](https://user-images.githubusercontent.com/1881059/126080397-e7fdb8c3-eafd-4d28-974a-4dff442d992b.png)

Cause removed, 0 Warnings

![Screenshot 2021-07-18 at 21 01 14](https://user-images.githubusercontent.com/1881059/126080631-b2e58c5e-31d1-49d7-bef8-df152eb3840a.png)

But ofc, we need to call `getStorybookUI({...})`

**Code snippets**

```tsx
import { getStorybookUI } from '@storybook/react-native';
...
StorybookUIRoot = getStorybookUI({})
```

**System**

```sh
  OS: macOS 11.4
  CPU: (8) arm64 Apple M1
Binaries:
  Node: 16.5.0 - /opt/homebrew/bin/node
  Yarn: 1.22.10 - /opt/homebrew/bin/yarn
  npm: 7.19.1 - /opt/homebrew/bin/npm
Browsers:
  Safari: 14.1.1
```

**Additional context**

`StorybookUIRoot = getStorybookUI({})` in any project causes warning 1

**Comment by dannyhw** [comment]
@leotm

Thanks for this detailed issue I appreciate it 🙏 .
Actually I had noticed the dependency loop warnings when setting up a project to test the new alpha. I've not had a chance to look into it yet but now that we have this issue I'll plan it into the alpha2 milestone and hopefully we can have a fix soon. 

With the duplicate decorator that sounds like it's probably related to fast reload, not sure though. I'll definitely be doing more testing over the coming days to try and find and fix as many issues as possible.

If you or anyone else is able to find the cause of these warnings then all contributions are very welcome.

Thanks for your interest in this project, I'll keep working to improve it 👍

**Comment by sangameshsomawar** [comment]
@dannyhw : I followed all steps mentioned [here]( https://github.com/storybookjs/react-native/blob/next-6.0/v6README.md)
Getting no warnings. (Just thought to inform you, I can see label as help wanted 😊) 

<img width="682" alt="Screenshot 2021-11-16 at 4 06 48 PM" src="https://user-images.githubusercontent.com/93119254/141969932-f403cc39-9b57-474e-8678-0292cfd895ee.png">

**Comment by dannyhw** [comment]
@sangameshsomawar thanks for trying this out, does it stay without warnings if you reload the app?

**Comment by sangameshsomawar** [comment]
@dannyhw 
Tried with fast reload, no warnings.
<img width="682" alt="Screenshot 2021-11-16 at 5 24 52 PM" src="https://user-images.githubusercontent.com/93119254/141980975-3b7350a3-58d6-446e-9324-45d55d6e8631.png">

**Comment by dannyhw** [comment]
@sangameshsomawar thanks, maybe its no longer an issue then 🤔 . Or rather it's a problem in 5.3 still but for the upcoming release it will be resolved

**Comment by sangameshsomawar** [comment]
@dannyhw: Yes, the Issue will not be there in new releases I think. You can simulate and confirm once then you can close the issue. 😄

**Comment by nguyenvantruong17** [comment]
I got the same problem. Then, I integrated the [react-hook-form](https://react-hook-form.com/get-started#ReactNative) and it did NOT work.
I've been debugging and I think that the problem is causing an error with react-hook-form.
Can anyone tell me how to solve this problem? Thx.

**Comment by dannyhw** [comment]
@nguyenvantruong17 are you using v6.0? or 5.3?

**Comment by nguyenvantruong17** [comment]
> @nguyenvantruong17 are you using v6.0? or 5.3?

I'm using v5.3.

**Comment by nguyenvantruong17** [comment]
> @nguyenvantruong17 are you using v6.0? or 5.3?

BTW. I've fixed that problem by setting **inlineRequires = false** in **metro.config.js** file.

**Comment by leotm** [comment]
no longer getting both original warnings since upgrading to 6 alpha, altho getting a diff one

will upgrade to beta soon and raise separately if remains

thanks again for checking earlier @sangameshsomawar and @nguyenvantruong17 

keep up the good work @dannyhw

**Comment by brandon-austin-lark** [comment]
> BTW. I've fixed that problem by setting inlineRequires = false in metro.config.js file.

This is also the only solution that I have found thus far. Any file that import Storybook into, my app crashes. Just really strange behavior going on. on v.5.3
