### ISSUE TITLE
[6.0] Provide a quick guide for having storybook alongside your app

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#241]
**Is your feature request related to a problem? Please describe.**

I often am asked how can you run storybook along side your existing app. Usually the answer is that it's the same as any component so you can do it how you would any other component. However I think that a simple guide could useful for many people and be linked to when these questions come up.

There are a few methods of creating multiple entry points of your app or just optionally rendering something.

It would be good if we could document an easy way to do this with react native storybook

**Describe the solution you'd like**

- Explore the option of using two metro-configs with different project-roots. 
- Explore the option of using a json config file that toggles storybook
- any other options that seem viable
- Create a quick guide for this and link to it on the readme

**Comment by dannyhw** [comment]
Will investigate this for 6.0, if it's complicated might delay to 6.1

**Comment by thenriquedb** [comment]
Same question here, Can you find any way to solve this?

**Comment by dannyhw** [comment]
@thenriquedb there are multiple ways of doing it. The only thing missing is documentation. I recently discovered that the ignite cli has its own way of doing it also.

I mentioned in this issue an option I'm exploring using metro to create two entry points.

The main point though is that the UI is just a component so you're free to include it or hide it just like any other component.

Of course the intention is to provide a documented solution however other things have taken priority.

**Comment by dannyhw** [comment]
I've written a blog post explaining how you can do this:
https://dev.to/dannyhw/multiple-entry-points-for-react-native-storybook-4dkp

Still not decided on whether it should be part of the default setup. Let me know your thoughts about it if you are interested in this.
