### ISSUE TITLE
`Can't find variable: document` [v6]

### ISSUE THREAD

**Issue by pvinis** [storybookjs/react-native#243]
**Describe the bug**

I am trying to use storybook v6 with react native + server, and I can't.

I have the deps:
```
"@storybook/addon-actions": "^6.4.0-alpha.20",
"@storybook/addon-ondevice-actions": "^6.0.1-alpha.0",
"@storybook/react-native": "^6.0.1-alpha.0",
"@storybook/react-native-server": "^6.0.0-alpha.0"
```

then I have the scripts:
```
"start-storybook": "STORYBOOK=1 yarn start",
"prestorybook-server": "sbn-get-stories",
"storybook-server": "start-storybook",
```

At this point, I
- `yarn storybook-server` in one terminal
- `yarn start-storybook` in another terminal

The server terminal gives me
```
yarn storybook-server
yarn run v1.22.10
$ sbn-get-stories
$ start-storybook
info => Loading presets
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 6.0.0-alpha.0 started                  │
│   4.48 s                                           │
│                                                    │
│    Local:            http://localhost:7007/        │
│    On your network:  http://192.168.8.130:7007/    │
│                                                    │
╰────────────────────────────────────────────────────╯
```

and it opens my browser, and everything is "loading" with the grey placeholders.

The other terminal is basically running the packager.

If my `main.js` contains `"@storybook/addon-ondevice-actions"`, everything works ok, but just on the device/simulator. If I add `"@storybook/addon-actions"` to my `main.js`, then right after loading the app on the simulator, the packager prints `Can't find variable: document`.

I'm guessing it's because the server is not found somehow? Or the loaded tab on my browser? My browser  still shows storybook with grey boxes everywhere, so they don't seem to be able to find each other?

**Comment by dannyhw** [comment]
Hey apologies for not making it clear in the release notes, currently the server is not included in this alpha. Additionally main.js in this case is only implemented for ondevice addons.

I'm not sure yet how the server will fit in with 6.0, but I appreciate all feedback regarding that.

**Comment by dannyhw** [comment]
The server is now supported, I have a post out about it https://dev.to/dannyhw/quick-guide-for-storybookreact-native-server-v6-4nl2
