### ISSUE TITLE
[6.0] Controls tab display looks broken when story has no controls

### ISSUE THREAD

**Issue by lauriharpf** [storybookjs/react-native#253]
**Describe the bug**
The message displayed in the Controls tab when story has no controls configured has some issues:

1. The text layout makes the view look "broken", as the two sentences are joined together  ("controlsLearn how"...)
1. The second sentence ("Learn how to add controls") is a link that opens the browser, but there's no visual hint - the text looks identical to the one that is not a link.
1. There is a disabled RESET-button that has no purpose (since there are no controls, there is nothing to reset)

See screenshot below:

![Screen Shot 2021-08-15 at 18 38 40](https://user-images.githubusercontent.com/6605505/129484196-52d72e17-0d7a-4ed7-a112-8da57c7d9084.png)

**To Reproduce**
1. Run the example app under `examples/native`
2. Select the top story ("Background StoriesOf -> Basic")
3. Press "Addons"
4. Open the "Controls" tab

**Expected behavior**
The app should show a message that doesn't have the issues described above, for example something like this:

![Screen Shot 2021-08-15 at 18 37 33](https://user-images.githubusercontent.com/6605505/129484376-97df2a6b-5c53-4785-8c78-4b97c2b5c8db.png)

**Comment by wahyunurrosyid** [comment]
mantap

**Comment by dannyhw** [comment]
@wahyunurrosyid please don't leave comments like this that provide no value, I look through all issue comments so this just wastes time.
