### ISSUE TITLE
Stories aren't displaying in browser

### ISSUE THREAD

**Issue by sanjeevyadavIT** [storybookjs/react-native#26]
**Describe the bug**
My stories don't appear in browser.
On (android) simulator i can see the stories
I have also tried running `adb reverse tcp:7007 tcp:7007` this command and nothing happens
I even changed the port then also nothing happened

**To Reproduce**
1. clone the repo `https://github.com/alexakasanjeev/magento_react_native.git`
2. cd into the folder
3. change branch `git checkout  bug/storybook-server-not-working`
4. run `npm run storybook`
5. in another terminal run `npm start`
6. in another terminal run `react-native run-android`
7. stories are visible in emulator put not on browser

**Expected behavior**
It should have shown the stories on the browser

**Screenshots**
![storybook](https://user-images.githubusercontent.com/13250741/63635879-5d503b80-c685-11e9-9218-ae09eb5f030b.png)

**Code snippets**
**package.json**
```[js]
{
  "name": "magento_react_native",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "prestorybook": "rnstl",
    "storybook": "start-storybook -p 7007"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.3.0",
    "axios": "^0.18.0",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.4.1",
    "react-navigation": "^3.3.2",
    "react-navigation-header-buttons": "^2.2.0",
    "react-redux": "7.1.0-alpha.4",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.0.2"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^5.1.11",
    "@storybook/react-native": "^5.1.11",
    "@storybook/react-native-server": "^5.1.11",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "24.3.1",
    "babel-loader": "^8.0.6",
    "eslint": "^5.15.3",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-react-native": "^3.6.0",
    "jest": "24.3.1",
    "metro-react-native-babel-preset": "0.53.0",
    "react-native-storybook-loader": "^1.8.0",
    "react-test-renderer": "16.8.4"
  },
  "jest": {
    "preset": "react-native"
  },
  "config": {
    "react-native-storybook-loader": {
      "searchDir": [
        "./src"
      ],
      "pattern": "**/stories.js"
    }
  }
}

```

**System:**
```[bash]
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.87
    Firefox: 68.0.1
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11 
    @storybook/react-native: ^5.1.11 => 5.1.11 
    @storybook/react-native-server: ^5.1.11 => 5.1.11 
  npmGlobalPackages:
    @storybook/cli: 5.0.11

```

**Additional context**
similar issue storybookjs/storybook#6489

**Comment by Gongreg** [comment]
oh, thanks @shilman, found it!

**Comment by i-oliva** [comment]
@Gongreg @khrystynapochynok still have the same issue running expo and TS

changing dependencies back to `5.2.1` doesn't fix it either

**Comment by Gongreg** [comment]
@pavilion, could you share more information? Exact storybook version, ios/android, physical device or emulator/simulator?

We are still in release of new version which will fix some of the issues. Hope to get a chance to work on rc version by the end of this week or during the next one.

**Comment by i-oliva** [comment]
@Gongreg 

1. `expo init project`
2. *select blank typescript project*
3. Follow https://storybook.js.org/docs/guides/guide-react-native/
4. `yarn storybook`

Stories are being displayed in Android but not on browser.

**Comment by Gongreg** [comment]
You might have to forward port 7007 `adb reverse tcp:7007 tcp:7007`

**Comment by i-oliva** [comment]
> You might have to forward port 7007 `adb reverse tcp:7007 tcp:7007`

Doing that makes the stories appear on the left bar but they don't render (browser) which is probably expected?

**Comment by Gongreg** [comment]
Great. That is not a bug. Stories are not rendered in the browser, they are rendered in the app itself. We will add support for react-native-web in the future.

**Comment by abdullahizzuddiin** [comment]
Hi @Gongreg 
Do you have any update with this?

**Comment by Gongreg** [comment]
Hello. You can follow example of react-native-web, their docs are actually using Storybook.
