### ISSUE TITLE
initialSelection not loading specified story

### ISSUE THREAD

**Issue by scousino** [storybookjs/react-native#273]
**Describe the bug**
The initialSelection parameter for getStorybookUI is not loading the specified story as the first selection on load. Instead, I still just see the default Preview screen telling me to open the navigator and select a story.

**To Reproduce**
1. Open any Storybook app and set the initialSelection to an ID string for a story in your Storybook app
2. Run the app

**Expected behavior**
The story specified by initialSelection to be loaded into the Preview window on start

**Screenshots**
What I see on load, rather than the story specified via the initialSelection param:
![image](https://user-images.githubusercontent.com/8717527/135509059-4f5001ee-f3e8-411a-a1b5-6eaf1e427715.png)

**Code snippets**
The toId function is imported from @storybook/csf
![image](https://user-images.githubusercontent.com/8717527/135508533-f41f0df0-f779-4736-b312-dd753c7683ca.png)

**System:**
![image](https://user-images.githubusercontent.com/8717527/135508671-5f9763e9-fa11-4e39-a08e-f5e044cf79bb.png)

**Comment by dannyhw** [comment]
#274 should fix this, at least it works in the example project.
