### ISSUE TITLE
[6.0] When writing requires paths are always written as up a directory

### ISSUE THREAD

**Issue by jgornick** [storybookjs/react-native#277]
**Describe the bug**
If I provide an absolute path glob, the [story requires always include a `../`](https://github.com/storybookjs/react-native/blob/c8563fd2a2e86bbc16b5652da524715df1d43a5a/app/react-native/scripts/loader.js#L41). This causes issues because it's not able to resolve the specified path.

**To Reproduce**
Set a stories path to something like `/path/to/projects/**/*.story.*`.

**Expected behavior**
I would expect the requires to use absolute paths to the resolved files provided by the glob library.

**System:**
Environment Info:

  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.11 - /usr/local/Cellar/yvm/4.1.4/shim/yarn
    npm: 7.24.2 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.71
    Edge: 94.0.992.38
    Safari: 14.1.2

**Comment by dannyhw** [comment]
@jgornick hey thanks for reporting this, at first glance I can say that what your saying makes sense. This seems like a side effect of the changes we did to move the storybook files all into .storybook. I'm currently looking at #275 so I might include a fix for this in a PR for that issue.

**Comment by dannyhw** [comment]
I've found a good fix for this I think, should be coming soon.

**Comment by dannyhw** [comment]
@jgornick see #278 :)
