### ISSUE TITLE
[6.0] the object control is too narrow vertically on the web

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#282]
**Describe the bug**

When running react native storybook with react-native-web the object text input is very small vertically and it's very difficult to edit.

**To Reproduce**
1. run storybook with react native web
2. use a story with a object control
3. go to addons panel and try to use the object control

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/3481514/137024424-3d711b89-5d8c-401d-a155-e84ea1bebcc5.png)

**Additional context**

Probably just needs some extra styling for web

**Comment by jorgearuv** [comment]
I would like to take this issue @dannyhw
