### ISSUE TITLE
[6.0] support new storybook architecture being introduced with 6.4

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#284]
**Is your feature request related to a problem? Please describe.**

Soon the storybook team will be merging some changes to the storybook architecture and it's necessary to make changes to this package in order for react native storybook to stay up to date.

**Describe the solution you'd like**

Necessary changes are made to support the new story store and api changes.

**Are you able to assist bring the feature to reality?**
Yes

**Additional context**

https://github.com/storybookjs/storybook/issues/15355

**Comment by dannyhw** [comment]
This issue gains more priority now that 6.4 is already out. Will be working on this now.

**Comment by chico** [comment]
@dannyhw really appreciate you working on this 👏, any chance you might have a ballpark ETA for when it might be done? Thank you! 🤞

**Comment by Listor** [comment]
Hey @dannyhw appreciate your time as well. Is there anything we can do to assist you in getting this done?

**Comment by dannyhw** [comment]
@chico @Listor hey thanks for the kind words, sorry for the delay responding I had holidays and stuff recently.

I've been reaching out for help on this but most people are taking holidays too. There is a branch with an initial attempt, but its still really rough and doesn't work yet https://github.com/storybookjs/react-native/tree/next-6.5. Stories weren't loading properly and its basically a case of debugging this or reworking it. I got pretty stuck with it, though I'll be coming back to it, hopefully with some help it can be sorted out.

The next alternative is that in 7.0 there are going to be some changes to make it easier for react native, however I still really want to get something out before then. I'm in talks with the web maintainers so when people are around I'll see what can be done.

**Comment by dannyhw** [comment]
done in #384
