### ISSUE TITLE
Unable to build storybook, "command not found"

### ISSUE THREAD

**Issue by OkhaifoOikeh** [storybookjs/react-native#287]
**Describe the bug**
The `yarn build-storybook` command is not working in react native
**To Reproduce**
`yarn add @storybook/cli --dev`
`yarn sb init`
`"scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "storybook": "start-storybook -p 7007",
    "build-storybook": "build-storybook"
  },` 

**Expected behavior**
Not sure because it keeps returning 
`$ build-storybook
/bin/sh: build-storybook: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
And its not the envrionment variable because the path is in my root folder env, its also not because I am not running it from root folder because I am as well.
**Additional context**
the operating system is OSX Catalina

**Comment by Rynxiao** [comment]
Same issue here. I can't find the relevant command in the `bin` directory of `node_modules` either.

**Comment by dannyhw** [comment]
there is no build-storybook command for react native because the ondevice storybook works differently. You should build the app the same as any other react native app.

**Comment by NM-2000** [comment]
Hey @OkhaifoOikeh, were you able to build this? I'm facing the same issue.

**Comment by dannyhw** [comment]
@NM-2000 please see my comment above. There is no build storybook for react native, you can build the ondevice storybook with the normal build commands for react native.

**Comment by NM-2000** [comment]
Hey @dannyhw, I did what you said and built it for android using react-native command and got `index.android.js` bundle.

What I am trying to do is to connect Chromatic with RN StoryBook. In the first place, I'm not sure if Chromatic even works with RN StoryBook (searched on google, didn't find any clue). If it does work, it's failing with the built bundle.

Have raised an issue on Chromatic's Github.
https://github.com/chromaui/chromatic-cli/issues/571
I hope they'll respond. 🤞😄

**Comment by dannyhw** [comment]
@NM-2000 to use chromatic with react native the only way is with react-native-web you can see my post about react-native-web storybook to get some context https://dev.to/dannyhw/introducing-storybook-for-react-native-web-mn4

**Comment by dannyhw** [comment]
in the repo for addon-react-native-web repo I use chromatic on the example project using react-native components via react-native-web
