### ISSUE TITLE
Images/Icons not loading and console output not working

### ISSUE THREAD

**Issue by manufunk** [storybookjs/react-native#289]
**Describe the bug**
I'm trying to setup storybook with react native expo and I'm able to see my stories in the emulator. However I'm facing 2 issues here:

1. I have native-base icons and images in my component that do render well on the main app but in storybook the images and icons are just not rendered. This also happens if I switch to default Expo icons. For the images I'm using, this is done via URL and not any static content. Is anyone else facing such issues and does someone know how to resolve it?
2. If I'm using storybook and render the component, I do not get any console.log output in my Terminal. This is different to running the main app. Why is that and can I somehow enable it?

**System:**
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.13 - /usr/local/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Edge: 94.0.992.50
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21 
    @storybook/addon-centered: ^5.3.21 => 5.3.21 
    @storybook/addon-knobs: ^5.3 => 5.3.21 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.25 => 5.3.25 
    @storybook/react: ^6.3.12 => 6.3.12 
    @storybook/react-native: ^5.3.25 => 5.3.25 
    @storybook/react-native-server: ^5.3.23 => 5.3.23

**Comment by dannyhw** [comment]
This is not expected behaviour, personally I've not experienced this. Could you provide a reproduction of this error so I can debug it?

**Comment by dannyhw** [comment]
@manufunk I noticed you have storybook react 6.0 installed. What's that being used for? The 5.3 react native storybook is not really compatible with 6.0.

**Comment by manufunk** [comment]
@dannyhw Thank you for the quick answer.
Regarding the dependencies, I guess the react dependency must have slipped in somehow. I removed it now as it should not be in there.

I investigated more and narrowed it down. I have some initial action calls to my redux store in the App.tsx like this:

```
const loadGeneralData = async () => {
  // Load categories
  rootStore.dispatch(getCategories()); // <- getCategories is an action from redux
};
```

If I remove the calls to my store, it works fine. Reason for having that is that I need to fetch some stuff in the beginning from my servers during app load. I will investigate further why this happens because if I dispatch a reducer state change like this `rootStore.dispatch({ type: LOGOUT_SUCCESS })`, it works.

**Comment by manufunk** [comment]
Ok seems like the issue existed because of a possible code cycle when running in a certain error I will inside the error logout the user and this could cause another error which was the cycle that I wanted to resolve anyhow. Even this is just a warning, it somehow broke the logic here. Still wondering why this was only the case for storybook.

**Comment by dannyhw** [comment]
@manufunk thanks for the update 👍
