### ISSUE TITLE
Typing information is incomplete/missing for storiesOf

### ISSUE THREAD

**Issue by arlyon** [storybookjs/react-native#29]
**Describe the bug**

The index.d.ts declares this type:

```ts
export declare const storiesOf: (...args: any[]) => any;
```

 This 'breaks' code completion (in that there isnt any) and requires explicitly defining the types of the chain functions.

```
src/Exercises.stories.tsx:26:19 - error TS7006: Parameter 'getStory' implicitly has an 'any' type.

26     .addDecorator(getStory => <CenterView>{getStory()}</CenterView>)
                     ~~~~~~~~
```

`@storybook/react` is typed properly.

**Comment by henrikra** [comment]
I have fixed this: https://github.com/storybookjs/react-native/pull/44 Can you test my PR? :)
