### ISSUE TITLE
Error running the native example for iOS

### ISSUE THREAD

**Issue by ChrisJamesC** [storybookjs/react-native#297]
**Describe the bug**
When running the native example I get an error: 

**To Reproduce**
1. Follow the steps in "CONTRIBUTING.MD": 
   - git clone https://github.com/storybookjs/react-native.git react-native-storybook
   - cd react-native-storybook
   - yarn bootstrap --core
   - cd examples/native
   - yarn install

2. the error happens on the following command: 
   - yarn ios

**Expected behavior**
The app should run smoothly

**Screenshots**
➜  native git:(next-6.0) yarn ios    
yarn run v1.22.17
$ react-native run-ios
info Found Xcode workspace "rn_example.xcworkspace"
info Launching iPhone 12 (iOS 15.0)
info Building (using "xcodebuild -workspace rn_example.xcworkspace -configuration Debug -scheme rn_example -destination id=97B48F54-009E-4E16-9702-3DEE33BE1242")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening rn_example.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace rn_example.xcworkspace -configuration Debug -scheme rn_example -destination id=97B48F54-009E-4E16-9702-3DEE33BE1242

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: 2d23359cfea64142409ddca5fa30169e
Build description path: /Users/XXX/Library/Developer/Xcode/DerivedData/rn_example-hdwapawavqjhbqdaowvproxqavvh/Build/Intermediates.noindex/XCBuildData/2d23359cfea64142409ddca5fa30169e-desc.xcbuild

note: Build preparation complete
note: Building targets in parallel
/Users/XXX/repos/react-native-storybook/examples/native/ios/Pods/Target Support Files/Pods-rn_example/Pods-rn_example.debug.xcconfig:1:1: error: unable to open file (in target "rn_example" in project "rn_example")
/Users/XXX/repos/react-native-storybook/examples/native/ios/Pods/Target Support Files/Pods-rn_example/Pods-rn_example.debug.xcconfig:1:1: error: unable to open file (in target "rn_example" in project "rn_example")
/Users/XXX/repos/react-native-storybook/examples/native/ios/Pods/Target Support Files/Pods-rn_example/Pods-rn_example.debug.xcconfig:1:1: error: unable to open file (in target "rn_example" in project "rn_example")
/Users/XXX/repos/react-native-storybook/examples/native/ios/Pods/Target Support Files/Pods-rn_example/Pods-rn_example.debug.xcconfig:1:1: error: unable to open file (in target "rn_example" in project "rn_example")
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the rn_example editor. (in target 'rn_example' from project 'rn_example')

**Code snippets**
no diff from next-6.0

**System:**
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 15.1

**Additional context**
Maybe it's because of the Mac M1 ?

**Comment by dannyhw** [comment]
don't forget to run pod install, however its possible that an upgrade to 0.66 is needed.

**Comment by ChrisJamesC** [comment]
@dannyhw I also had to fix my pod install setup indeed, but I hit more errors. I'll continue investigating and document my findings here. 

Fun fact: I face these issues because I wanted to tackle the 0.66 upgrade as a first contribution :)

**Comment by dannyhw** [comment]
@ChrisJamesC any update?

**Comment by ChrisJamesC** [comment]
Hey @dannyhw, sorry I didn't have time to get back to this project. I hope I can do some day, but feel free to close this issue if it's too old.
