### ISSUE TITLE
Issue with refresh / reload (maybe because of npm workspaces)

### ISSUE THREAD

**Issue by ghost** [storybookjs/react-native#299]
**Describe the bug**

Hello,

In my current project in RN 0.64, anytime I am doing a modification in a component, the storybook reloads and I have to navigate to the component I am working on.

I am using: 
    "@storybook/addon-actions": "^5.3.21",
    "@storybook/addon-knobs": "^5.3.21",
    "@storybook/addon-links": "^5.3.21",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.25",
    "@storybook/react-native": "^5.3.25",

I don't remember to have the same issue in the last project in RN I have worked on.

Is it a configuration issue please or the expected behavior?

I am not using the web server in this project. I was using it in the last one.

I am in a mono repo architecture with npm workspaces (with storybook in each package)

**Code snippets**

index.js

```
if (__DEV__) {
  if (Config.STORYBOOK) {
    import('./storybook').then(StorybookUIRoot => register(StorybookUIRoot.default));
  } else ...
```

storybook/index.ts

```
import {withKnobs} from '@storybook/addon-knobs';
import {addDecorator, configure, getStorybookUI} from '@storybook/react-native';
import SplashScreen from 'react-native-lottie-splash-screen';
import './rn-addons';

SplashScreen.hide();

addDecorator(withKnobs);

configure(() => {
  require('./stories');
  require('@app/react-native-theming/storybook/stories');
}, module);

const StorybookUIRoot = getStorybookUI({asyncStorage: null});

export default StorybookUIRoot;
```

**Comment by dannyhw** [comment]
If you use async storage you can work around this. However it should normally work.

```
import AsyncStorage from '@react-native-async-storage/async-storage';
const StorybookUIRoot = getStorybookUI({asyncStorage: AsyncStorage, shouldPersistSelection:true});
```

**Comment by dannyhw** [comment]
It's been a while without an update so I'll close this for now. Let me know if you would like to re-open this.

**Comment by marlonschlosshauer** [comment]
> If you use async storage you can work around this. However it should normally work.
>  ```ts
> import AsyncStorage from '@react-native-async-storage/async-storage';
> const StorybookUIRoot = getStorybookUI({asyncStorage: AsyncStorage, shouldPersistSelection:true}); 

That did the trick for me. Thanks! However I'm getting a TS error on `getStorybookUI`: 
```
Argument of type '{ asyncStorage: AsyncStorageStatic; shouldPersistSelection: true; }' is not assignable to parameter of type 'Partial<Params>'.
  Object literal may only specify known properties, and 'asyncStorage' does not exist in type 'Partial<Params>'. [2345]
```

Where `Params` is `import("./preview/Preview").Params `.

Did I forget to configure something? Should I open a new issue for that?
I can ignore the error on my end so no need to hurry 👍

**Comment by dannyhw** [comment]
@marlonschlosshauer what version of rn storybook are you using?

**Comment by marlonschlosshauer** [comment]
> @marlonschlosshauer what version of rn storybook are you using?

I'm currently using `6.0.1-beta.7`.

**Comment by dannyhw** [comment]
@marlonschlosshauer in the beta asyncStorage is no longer optional so you don't need to pass it as an option. Just the shouldPersistSelection is fine.

**Comment by marlonschlosshauer** [comment]
Yep that worked, thanks! 🍻
