### ISSUE TITLE
Preview instance access in OnDeviceUI

### ISSUE THREAD

**Issue by toddpi314** [storybookjs/react-native#300]
Hey folks!

I have an tutorial setup on https://github.com/storybookjs/native/issues/66 that bridges together the OnDeviceUI with the deep-link interop. 

But, to do this, I had to dig out the Preview instance to seed in the active story id. Seeding via the getStorybookUI constructor factory was a bit too heavy handed, especially with retaining active story state.

Below is the patch to export if the maintainers are interested in adopting (Tested on `@storybook/react-native@5.3.25`):

```diff
diff --git a/node_modules/@storybook/react-native/dist/index.js b/node_modules/@storybook/react-native/dist/index.js
index 15ce6b6..80c316b 100644
--- a/node_modules/@storybook/react-native/dist/index.js
+++ b/node_modules/@storybook/react-native/dist/index.js
@@ -19,3 +19,4 @@ exports.raw = preview.api().raw.bind(preview);
 exports.storiesOf = function (kind, module) {
     return rawStoriesOf(kind, module).addParameters({ framework: 'react-native' });
 };
+exports.preview = preview
\ No newline at end of file
```

I specifically need to get at `_selectStoryEvent`, so having an accessor to guard the actual instance might make more sense.

**Comment by dannyhw** [comment]
@toddpi314 would be happy to accept a PR with this change if you are able to.

Either way I'm more than happy to facilitate this way of using the project. Maybe we can use this to replace the server in 6.0 🤔 .
