### ISSUE TITLE
React Native Storyshots - RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by nigelsim** [storybookjs/react-native#302]
**Describe the bug**
When running `storyshots` the following error occurs. Running the storybook within the app on the device works as expected:
```
 FAIL  ./storyshots.test.ts
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded
        at Function.get [Symbol.species] (<anonymous>)
        at Array.slice (<anonymous>)

      at Resolver.resolveStubModuleName (node_modules/jest-resolve/build/index.js:375:49)
      at Symbol (node_modules/core-js/modules/es.symbol.description.js:25:75)
      at Symbol (node_modules/core-js/modules/es.symbol.description.js:25:106)
      at Symbol (node_modules/core-js/modules/es.symbol.description.js:25:106)
      at Symbol (node_modules/core-js/modules/es.symbol.description.js:25:106)
```
**To Reproduce**
1. Setup React Native Story book and test
2. Add `@storybook/addon-storyshots`
3. Setup `storyshots.test.ts` as per README
4. Run `yarn test`

**Expected behavior**
Snapshots to be generated

**Code snippets**
storybook/index.ts
```typescript
import { getStorybookUI, configure } from '@storybook/react-native';
import { loadStories } from './storyLoader';


configure(() => {
  loadStories()
}, module);

configure(loadStories, module);
// Refer to https://github.com/storybooks/storybook/tree/master/app/react-native#start-command-parameters
// To find allowed options for getStorybookUI
const StorybookUIRoot = getStorybookUI({});

export default StorybookUIRoot;
```
storyshots.test.ts
```typescript
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots();
```

button.stories.ts
```typescript
import { Button } from './Button';
import { storiesOf } from '@storybook/react-native';

storiesOf('Button', module)
    .add('Default', () => (<Button title='My Button' color='#fafafa' onPress={null}></Button>
    ));
```

**System:**
 - OS: Linux
 - Device: NA
 - Browser: NA
 - Framework: React Native 0.57.8
 - Addons: @storybook/addon-storyshots
 - Version: 5.1.0-rc.2

**Comment by enesozturk** [comment]
It is still an issue with:

```json
{ 
    "expo": "~43.0.2",
    "react-native": "0.64.3",
    "@storybook/addon-actions": "^5.3",
    "@storybook/addon-knobs": "^5.3",
    "@storybook/addon-links": "^5.3",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.25",
    "@storybook/react-native": "^5.3.25",
    "@storybook/react-native-server": "^5.3.23",
}
```

**Comment by dannyhw** [comment]
I've never really worked with storyshots if someone could explain more about this issue or open a PR that would be really helpful.

**Comment by enesozturk** [comment]
@dannyhw, still having the issue with upgraded packages:
```json
  "expo": "^44.0.0",
  "@storybook/addon-actions": "^6.4.9",
  "@storybook/addon-knobs": "^6.4.0",
  "@storybook/addon-links": "^6.4.9",
  "@storybook/addon-ondevice-actions": "^5.3.23",
  "@storybook/addon-ondevice-knobs": "^5.3.25",
  "@storybook/react-native": "^5.3.25",
  "@storybook/react-native-server": "^5.3.23",
```

I render my storybook inside the app with a specific route. 

```js
 <Stack.Navigator>
    <Stack.Screen
      name="Home"
      component={MainStack}
    />
    <Stack.Screen
      name="Storybook"
      component={StorybookComp}
    />
</Stack.Navigator>
```
App is working as expected. When I navigate to the Storybook route. I got this message. (But I can continue using by dismiss this message)

<img width="499" alt="Screen Shot 2021-12-18 at 22 02 03" src="https://user-images.githubusercontent.com/19428358/146652908-f533b345-e8f8-483d-853b-b489d304eaa4.png">

If I directly render Storybook in App.js (in Expo, this is the root file) like this:
```js
import React from "react";
import StorybookUIRoot from "./storybook";

export default StorybookUIRoot;
```
🟢 It is ok.

🔴 But when I want to import both my app and Storybook, it gives the error. 

Here I thought:
- Maybe the Storybook conflicts with any package I use, but I could not find it. If I do not import my app, it is ok.
- Vice versa: when I use the Storybook inside navigation but do not call it, the error does not show up. When navigate to Storybook, Storybook renders and error shows up

```js
function App() {
  const { storybook } = Constants.manifest.extra;
  const [fontsLoaded] = useFonts({
    Poppins_400Regular,
    Poppins_600SemiBold,
  });

  if (!fontsLoaded) {
    return <AppLoading />;
  }

  return <>{Boolean(storybook) ? <LinksScreen /> : <MainNavigator />}</>;
}

export default App;

```

I can give these details. Appreciate your help. Still trying to solve this issue.

**Comment by dannyhw** [comment]
You shouldn't mix 5.3 with 6.x either use V6 or 5.3 but not both.

**Comment by enesozturk** [comment]
`addon-knobs` page is deprecated and `addon-controls` start with 6.x.x - https://www.npmjs.com/package/@storybook/addon-knobs

How to continue here? Downgraded the others to 5.x.x latest.

Edit: Downgraded all the packages like below. Still giving error.

```json
"@storybook/addon-actions": "5.3.13",
"@storybook/addon-knobs": "5.3",
"@storybook/addon-links": "5.3.7",
"@storybook/addon-ondevice-actions": "^5.3.23",
"@storybook/addon-ondevice-knobs": "5.3.25",
"@storybook/react-native": "^5.3.25",
"@storybook/react-native-server": "^5.3.23",
```

**Comment by enesozturk** [comment]
[This](https://github.com/storybookjs/react-native/issues/152#issuecomment-808388571) solved the issue for me. But not sure any other thing will be affected by setting `inlineRequire: false`. What do you think?

For my Expo app, in `metro.config.js`:
```js
const { getDefaultConfig } = require("expo/metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig(__dirname);
  return {
    transformer: {
      // ...my configs
      // added this function 👇🏽
      getTransformOptions: async () => ({
        transform: {
          inlineRequires: true,
        },
      }),
    },
    resolver: {
      // my configs
    },
  };
})();

```

**Comment by dannyhw** [comment]
Inline requires is just an optimization disabling it shouldn't be a problem.

**Comment by ayushjain6** [comment]
@dannyhw I have tried with inlineRequires: false in react-native-cli application which is causing other issues in the project

**Comment by SamakaCD** [comment]
Setting `inlineRequires` to `false` or `true` didn't help me. However, it's possible to avoid the issue by loading a module with the Storybook lazily like this:
```tsx
<NavigationContainer>
  ...
    <Stack.Screen name={Routes.Storybook}>
      {() => {
        const { Storybook } = require('./screens/Storybook')
        return <Storybook />
      }}
    </Stack.Screen>
  ...
</NavigationContainer>
```

**Comment by MarkKewley** [comment]
Why is this issue closed? It's still occurring for me on Android only devices using the latest expo/storybook. Crazy that there hasn't been a ton of progress in 3.5 years... yea yea I suppose I could dig in but I'm pretty lazy right now.

The work around that worked for me though was from @SamakaCD  so thank you. I had to do a slight modification for my purposes (since my `./storybook` is just exporting a default React tsx component)

```
const StorybookUI = require('./storybook').default;
return <StorybookUI />;
```

**Comment by dannyhw** [comment]
Its closed because many solutions have been posted here that don't seem related to any storybook code. Also lots has changed in the v6 beta so its very likely this issue wouldn't occur anymore. Happy to reopen if its shown to be a persistent issue in the beta.

**Comment by MarkKewley** [comment]
Yea I'm on 5.3 (just added storybook to my app yesterday) and after doing so I was encountering this issue with Android only devices. 

When I removed all the boilerplate setup code for Storybook in the `storybook/index.tsx` the issue dissapeared.

What was also strange is that all my [SecureStore](https://docs.expo.dev/versions/latest/sdk/securestore/#installation) functions were basically empty which I think was causing all the unhandled exceptions which resulted in the max call stack. 

Refactoring to lazy-load the storybook related code iff I was running in storybook mode (dotenv variable to toggle it on/off) resolved the issue.

E.g.
```
export default function App() {
  ... extra code for splash screen/colorscheme/etc...
  
  if (STORYBOOK_ENABLED === 'true') {
    const StorybookUI = require('./storybook').default;
    return <StorybookUI />
  }

  // main app code
  return (
    ...
  );
}
```

I'll have to give v6 a shot at some point to see if the issue disappears.

**Comment by DimitrisTzimikas** [comment]
In my case the problem was on my project App import. 

example:

`index.js`


```
/* Libraries */
import {AppRegistry} from 'react-native';

/* Local Files */
import App from './src/App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

After I tried to add storybook:
``` 
/* Libraries */
import {AppRegistry} from 'react-native';

/* Local Files */
import App from './src/App';
import {name as appName} from './app.json';
import StorybookUIRoot from './Storybook'; <--- Storybook Import

//AppRegistry.registerComponent(appName, () => App); <--- Comment out App Registry for App
AppRegistry.registerComponent(appName, () => StorybookUIRoot); <--- Add StorybookUIRoot to App Registry
```

After this setup I got the same error. I think the problem lies on my application setup and libraries I've added, can't really say which one it is. But after those changes it worked. 

```
/* Libraries */
import {AppRegistry} from 'react-native';
import config from 'react-native-ultimate-config';

/* Local Files */
//
import {name as appName} from './app.json';
import StorybookUIRoot from '@src/Storybook';

if (config.STORYBOOK === 'true') { <--- Here I use react-native-ultimate-config to load from .env the flag, you can use whatever flag you like
  AppRegistry.registerComponent(appName, () => StorybookUIRoot); <--- Again load StorybookUIRoot to App Registry
} else {
  const App = require('./src/App').default; <--- Use inline import to prevent components from loading and cause the error
  AppRegistry.registerComponent(appName, () => App);
}
```

So after all I've inline require the App.tsx (root of my project) and the problem was solved. 

Hope it helps✌️

**Comment by gavrix** [comment]
If anyone finds this ticket first. This issue appears with storybook v6 as well. This [solution](https://github.com/storybookjs/react-native/issues/405#issuecomment-1436683333) fixed it for us (Hermes + inlineRequires: true)

**Comment by dannyhw** [comment]
The better solution is to add this to your metro config

```
  resolver: {
    resolverMainFields: [
      "sbmodern",
      ...defaultConfig.resolver.resolverMainFields,
    ],
  }
```

**Comment by dannyhw** [comment]
Inline requires changes shouldn't be needed if you have this in your metro config

```
  resolver: {
    resolverMainFields: [
      "sbmodern",
      ...defaultConfig.resolver.resolverMainFields,
    ],
  }
```

**Comment by pfcodes** [comment]
This started happening to me after upgrading to expo 49. anyone know a fix?

**Comment by pfcodes** [comment]
> Inline requires changes shouldn't be needed if you have this in your metro config
> 
> ```
>   resolver: {
>     resolverMainFields: [
>       "sbmodern",
>       ...defaultConfig.resolver.resolverMainFields,
>     ],
>   }
> ```

Only started to experience this after upgrading to expo 49. this fixed it for me. thanks.
