### ISSUE TITLE
Issue for React Native Web when it was started

### ISSUE THREAD

**Issue by titojuan** [storybookjs/react-native#304]
**Describe the bug**
When I start Storybook, it compiles everything correct but the console shows us an issue and keeps loading.
But the components that it builds work correctly in the emulators

`Uncaught Error: Singleton client API not yet initialized, cannot call addArgTypesEnhancer`

<img width="1088" alt="Screen Shot 2021-12-13 at 14 27 57" src="https://user-images.githubusercontent.com/9262478/145875562-ff76da0d-26ac-456c-b97c-9375b8fabcee.png">

**System**
System: MacOS Monterey 12.0.1
Corel i5 / 8 GB / 512 GB

**Packages**
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-web": "^0.14.10",
"@react-theming/storybook-addon": "^1.1.1",
"@storybook/addon-a11y": "6.3.11",
"@storybook/addon-docs": "6.3.11",
"@storybook/addon-knobs": "6.3.1",
"@storybook/addon-links": "6.3.11",
"@storybook/addon-postcss": "2.0.0",
"@storybook/addon-storysource": "6.3.11",
"@storybook/addon-viewport": "6.3.11",
"@storybook/addons": "6.3.11",
"@storybook/preset-scss": "^1.0.3",
"@storybook/react": "6.3.11",
"@storybook/react-native": "5.3.25"

**Additional context**
This error was unexpected, previously everything worked fine

**Comment by dannyhw** [comment]
@titojuan could you share more about what you ran when this error happened? Are you running addon-react-native-web in this screenshot? or is it something else?

if you could provide a public reproduction repository that would be really helpful.

**Comment by titojuan** [comment]
@dannyhw when I execute this command `start-storybook -p 7007 -s public`, In my **main.js** is this

```
const path = require('path');

module.exports = {
  stories: [
    '../src/docs/**/**.stories.@(tsx|mdx)',
    '../src/components/atomics/**/**.stories.@(tsx|mdx)',
    '../src/components/molecules/**/**.stories.@(tsx|mdx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-storysource',
    '@storybook/addon-a11y',
    '@storybook/addon-postcss',
    '@storybook/addon-viewport/register',
    '@react-theming/storybook-addon',
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
        babelOptions: {},
        sourceLoaderOptions: null,
      },
    },
  ],
  typescript: {
    check: false,
    checkOptions: {},
  },
  webpackFinal: async (config) => {
    config.resolve.alias = {
      'react-native$': 'react-native-web',
    };
    config.module.rules.push({
      test: /\.(js|jsx|ts|tsx)$/,
      use: [
        {
          loader: require.resolve('babel-loader'),
          options: {
            presets: [['react-app', {flow: false, typescript: true}]],
          },
        },
      ],
    });
    config.resolve.extensions.push('.ts', '.tsx');
    return config;
  },
};
```

**Comment by dannyhw** [comment]
@titojuan any reason why you don't use the addon? https://github.com/storybookjs/addon-react-native-web

**Comment by dannyhw** [comment]
also you are using `"@storybook/react-native": "5.3.25"` which could be bringing in old versions of storybook. If you want to use the two in the project you would be better off using the react native @next (alpha)

**Comment by titojuan** [comment]
@dannyhw I tried with [@storybookjs/addon-react-native-web](https://github.com/storybookjs/addon-react-native-web) but I have a new issue, also update **storybook** to version 6.4.9

<img width="599" alt="Screen Shot 2021-12-15 at 11 29 48" src="https://user-images.githubusercontent.com/9262478/146225893-0693bdb7-a407-478d-b9e7-8f4304ffd843.png">

**Comment by dannyhw** [comment]
@titojuan what version is your @storybook/react-native? 5.3 is too old to work with 6+ and the react native alpha isn't yet compatible with 6.4, only 6->6.3

this is easily resolved by using compatible versions. If you can send me the repo I could fix it I'm pretty sure.

**Comment by titojuan** [comment]
@dannyhw We could see it in a call by meet or zoom because this repository is private, but I will try to install `@storybook/react-native@next`

**Comment by titojuan** [comment]
> @titojuan what version is your @storybook/react-native? 5.3 is too old to work with 6+ and the react native alpha isn't yet compatible with 6.4, only 6->6.3
> 
> this is easily resolved by using compatible versions. If you can send me the repo I could fix it I'm pretty sure.
