### ISSUE TITLE
Radio control type not working in both Mobile and Web

### ISSUE THREAD

**Issue by Karthik-B-06** [storybookjs/react-native#308]
**Describe the bug**

Having a radio type control to work with both Mobile and Web but having to control type: 'radio' works on the web and type: 'radios' works on mobile. 

**Expected behavior**
A single control type (either 'radio' or 'radios') working on both Mobile and Web. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35562287/147325078-9f07fa52-85f8-490f-bdea-25df3431e769.png)

**Code snippets**
This code works on mobile. 
```
  argTypes: {
    size: {
      options: <size_options>,
      control: { type: 'radios' },
    },
  },
```
This works for the web. 
```
  argTypes: {
    size: {
      options: <size_options>,
      control: { type: 'radio' },
    },
  },
```

**System:**
```
    "@storybook/addon-ondevice-actions": "^6.0.1-alpha.7",
    "@storybook/addon-ondevice-backgrounds": "^6.0.1-alpha.7",
    "@storybook/addon-ondevice-controls": "^6.0.1-alpha.7",
    "@storybook/addon-ondevice-notes": "^6.0.1-alpha.7",
    "@storybook/addon-react-native-web": "^0.0.14",
```

**Comment by dannyhw** [comment]
@Karthik-B-06 thanks for reporting this issue 🙇‍♂️. If you find any more inconsistencies please let me know.

I'll fix this one I'm back from holidays. Or if you'd like to make a contribution all pr's are welcome.

Happy Holidays 🙂

**Comment by Karthik-B-06** [comment]
Hey, @dannyhw I have made a PR fixing the same.

**Comment by dannyhw** [comment]
This is merged and will be released soon.
