### ISSUE TITLE
Storybook does not work with Expo

### ISSUE THREAD

**Issue by kristremblay** [storybookjs/react-native#32]
**Describe the bug**
When trying to install Storybook with the most recent release of Expo, the process fails at `installing dependencies` with the error `No matching version found for @storybook/react-native@^5.0.6`.

**To Reproduce**
1. Create new project with `expo init ProjectName`
2. cd into the directory
3. Run `getstorybook`

**Expected behavior**
Storybook would install properly and I would be a happy boy.

**System:**
 - OS: Windows 10
 - Node Version: 11.4.0
 - NPM Version: 6.4.1
 - Framework: React Native (Expo)

Log dump
```
245 verbose stack @storybook/react-native: No matching version found for @storybook/react-native@^5.0.6
245 verbose stack     at pickManifest (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\npm-pick-manifest\index.js:65:11)
245 verbose stack     at fetchPackument.then.packument (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:52:18)
245 verbose stack     at tryCatcher (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
245 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
245 verbose stack     at Promise._settlePromise (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
245 verbose stack     at Promise._settlePromise0 (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
245 verbose stack     at Promise._settlePromises (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
245 verbose stack     at Async._drainQueue (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
245 verbose stack     at Async._drainQueues (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
245 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
245 verbose stack     at processImmediate (timers.js:632:19)
```

**Comment by shilman** [comment]
@alechp Please use the latest 5.1.0 version. The 5.2.0 version may be messed up -- it's a long story.

**Comment by kristremblay** [comment]
@alechp @shilman Thank you both. That migration guide for 5.1 lgtm, I'll have to check it out when I get home though.

Cheers

**Comment by igorgidea** [comment]
Windows 10
node 12.18.0
Storybook 5.3.19
expo 38.0.8
In browser Google Chrome   84.0.4147.8 or Firefox 78.0.2 there is "forever stories loading" on the left panel
![изображение](https://user-images.githubusercontent.com/20354531/88405223-99c97180-cdd7-11ea-9df4-ed8785830fae.png)

Any ideas how to fix it? btw its works fine in android emulator when i run command "expo start --android"

**Comment by s-kuniyoshi** [comment]
@igorgidea 
I have same issue.
Please anyone resolve it. ;-(

**Comment by warent** [comment]
This happened to me, turned out to be a configuration issue. Following this helped me get it setup:
https://github.com/expo/examples/tree/master/with-storybook
