### ISSUE TITLE
Stories only appear when using storiesOf instead of CSF

### ISSUE THREAD

**Issue by JacobGalati** [storybookjs/react-native#320]
**Describe the bug**
I just started a new Expo project and initially setup using v5, but switched it over to 6.0.1-alpha.7 and followed the instructions found [here](https://github.com/storybookjs/react-native/blob/next-6.0/v6README.md).

When I created my first story with CSF format no stories appear in Expo Go or Web View. If i switch to `storiesOf` format it appears. 

**Expected behavior**
Stories to appear when using the CSF format.

**Screenshots**

|CSF Format | storiesOf Format|
|-----|-----|
| <img style="display: inline;" src=https://user-images.githubusercontent.com/4642741/151465671-e01e2762-708d-440e-becd-45cb07e62a89.jpeg height="400"/> | <img style="display: inline;" src=https://user-images.githubusercontent.com/4642741/151465686-ab68d016-2181-4855-825a-203b5bcefae5.jpeg height="400"/> |

**Code snippets**
Functioning Button.stories.tsx
```tsx
import { storiesOf } from "@storybook/react-native";
import { Button } from "react-native-elements";

storiesOf("Button", module).add("default", () => (
  <Button title="Button Text" />
));
```
Broken Button.stories.tsx
```tsx
import React from "react";
import { Button } from "react-native-elements";
import { ComponentStory, ComponentMeta } from "@storybook/react-native";

export default {
  title: "Button",
  component: Button,
  argTypes: {
    onPress: { action: "pressed the button" },
  },
} as ComponentMeta<typeof Button>;

type ButtonStory = ComponentStory<typeof Button>;

const Template: ButtonStory = (args) => <Button {...args} />;

export const Primary = Template.bind({});

Primary.args = {
  title: "Button Text",
};
```
I can give you code snippets for my other storybook files, but they match what is outlined in the 6.0 setup I linked above.

**System:**
```
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.4.14 => 6.4.14
    @storybook/addon-controls: ^6.4.14 => 6.4.14
    @storybook/addon-ondevice-actions: ^6.0.1-alpha.7 => 6.0.1-alpha.7
    @storybook/addon-ondevice-backgrounds: ^6.0.1-alpha.7 => 6.0.1-alpha.7
    @storybook/addon-ondevice-controls: ^6.0.1-alpha.7 => 6.0.1-alpha.7
    @storybook/addon-ondevice-notes: ^6.0.1-alpha.7 => 6.0.1-alpha.7
    @storybook/react-native: ^6.0.1-alpha.7 => 6.0.1-alpha.7
```

**Comment by dannyhw** [comment]
Avoid using storybook packages with a verison above 6.3. I'm still working on 6.4 compatibility since it had some internal api changes.

Change these to 6.3
```
    @storybook/addon-actions: ^6.4.14 => 6.4.14
    @storybook/addon-controls: ^6.4.14 => 6.4.14
```


Also please share your main.js and other files in the .storybook folder

**Comment by JacobGalati** [comment]
@dannyhw That fixed the issue. Thank you! Below is my `main.js` just in case you still would like to see it.

```js
module.exports = {
  stories: [
    "../components/**/*.stories.?(ts|tsx|js|jsx)",
    "./stories/**/*.stories.?(ts|tsx|js|jsx)",
  ],
  addons: [
    "@storybook/addon-ondevice-notes",
    "@storybook/addon-ondevice-controls",
    "@storybook/addon-ondevice-backgrounds",
    "@storybook/addon-ondevice-actions",
  ],
};
```

**Comment by dannyhw** [comment]
@JacobGalati great! glad to hear that fixed it. Will close the issue for now since it's resolved let me know if you want to reopen :).

**Comment by JacobGalati** [comment]
Quick related question while I've got you. @dannyhw :)
Does 6.0 support AsyncStorage yet? Trying to put
```jsx
const StorybookUIRoot = getStorybookUI({
  asyncStorage: require("@react-native-async-storage/async-storage").default,
});
```
in my Storybook.tsx results in an error. If it's a bug I'll make a new issues, but I'm assuming it is either a WIP, or its configured somewhere else now.
Thanks!

**Comment by dannyhw** [comment]
@JacobGalati that isn't needed anymore because its included by default now. In fact async storage is no longer optional.
