### ISSUE TITLE
storybook/react-native@next not working with expo SDK 44

### ISSUE THREAD

**Issue by archived-vish** [storybookjs/react-native#339]
**Issue Summary**
The stories don't appear in the navigator though the build does go through successfully.  I used the following [instructions](https://github.com/storybookjs/react-native/blob/next-6.0/v6README.md) to do the setup.

**To Reproduce**
- Clone [repo](https://github.com/vthukral94/expo-storybook-alpha) 
- Run `yarn ios`

**Expected behavior**
Stories appear in the navigator.

**System:**
```
  System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.0 - ~/dev/n/bin/node
    Yarn: 1.22.17 - ~/dev/n/bin/yarn
    npm: 8.3.1 - ~/dev/n/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Firefox: 97.0.1
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: ^6.4.19 => 6.4.19 
    @storybook/addon-controls: ^6.4.19 => 6.4.19 
    @storybook/addon-ondevice-actions: ^6.0.1-beta.5 => 6.0.1-beta.5 
    @storybook/addon-ondevice-backgrounds: ^6.0.1-beta.5 => 6.0.1-beta.5 
    @storybook/addon-ondevice-controls: ^6.0.1-beta.5 => 6.0.1-beta.5 
    @storybook/addon-ondevice-notes: ^6.0.1-beta.5 => 6.0.1-beta.5 
    @storybook/react-native: ^6.0.1-beta.5 => 6.0.1-beta.5 
```

**Comment by dannyhw** [comment]
@vthukral94 This is likely not a problem with expo since react native storybook is not yet compatible with storybook 6.4.

Please update these packages to use ~6.3 instead for the time being.
```
  @storybook/addon-actions: ^6.4.19 => 6.4.19 
  @storybook/addon-controls: ^6.4.19 => 6.4.19 
```

Let me know if the problem persists after downgrading the version

**Comment by archived-vish** [comment]
Thanks @dannyhw the fix worked. I think it might be a good idea to add this to docs
