### ISSUE TITLE
mdx support in react-native

### ISSUE THREAD

**Issue by astriskit** [storybookjs/react-native#340]
**Describe the bug**
This issue here - storybookjs/react-native#341

**Expected behavior**
being able to use Docs add-on as shown in the react-tutorials

**Comment by dannyhw** [comment]
I've moved the issue you mentioned over to this repo so I think we can close this issue since there is more details in that one.

let me know if you want to reopen. I will add my comments to #341 regarding mdx in react native.

**Comment by astriskit** [comment]
Thanks @dannyhw.
