### ISSUE TITLE
[6.0] Remove unused params from getStorybookUI 

### ISSUE THREAD

**Issue by levino** [storybookjs/react-native#342]
In version 6 when I call
```typescript
export const StorybookUIRoot = getStorybookUI({
    host: '192.168.1.167',
    isUIHidden: true,
})
```
both values are ignored.

**Comment by dannyhw** [comment]
Thats because the server isn't yet supported in 6.0 so it does nothing.

**Comment by levino** [comment]
Okay. We should then remove the property from the config for `getStorybookUI` so TS gives an error when people try to set this. Maybe it should even throw an error "Server still unsupported!". Finding this out wasted quite some time for me.

**Comment by dannyhw** [comment]
@Levino thats a good point! thanks for the feedback 🙏 . I would like to say though that some rough edges are expected in beta however I understand it can be frustrating.

**Comment by levino** [comment]
My pleasure. I suggest to use a whitelist for the options parameters which are currently supported and throw if any excess / unsupported values are set by the user.

**Comment by sunkibaek** [comment]
@dannyhw Hey there! I'm trying to make the first contribution to this project and this seems to be simple enough!

Is this a matter of removing server-related params from `getStorybookUI`? But I'm not sure which one I should remove—there seem a few:

```typescript

export type Params = {
  onDeviceUI?: boolean;
  resetStorybook?: boolean;
  disableWebsockets?: boolean;
  query?: string;
  host?: string;
  port?: number;
  secured?: boolean;
  initialSelection?: InitialSelection;
  shouldPersistSelection?: boolean;
  tabOpen?: number;
  isUIHidden?: boolean;
  shouldDisableKeyboardAvoidingView?: boolean;
  keyboardAvoidingViewVerticalOffset?: number;
} & { theme?: typeof theme };
```

I guess we are removing `host` and `port`. How about `query` and `disableWebsockets`?

**Comment by dannyhw** [comment]
Sorry for not responding before, I've been really busy recently. I just merged a big refactor that removes many unused ones. Then now I just remembered about this issue so sorry for doing it without saying anything. If you want another issue to work on I'd be happy to find another for you.

**Comment by Mellbourn** [comment]
> Thats because the server isn't yet supported in 6.0 so it does nothing.

I've been trying to start a storybook server in our react-native solution, to be able to run [loki](https://github.com/storybookjs/react-native/issues/342#issuecomment-1085891960). Are you saying that running a storybook server is now impossible?

**Comment by dannyhw** [comment]
@Mellbourn this was previously the case but a few months ago I was able to get the server working so now the server is supported for v6.5

**Comment by Mellbourn** [comment]
@dannyhw thank you! Correcting the version of `@storybook/core-server` to 6.5.16 worked for me.
