### ISSUE TITLE
React-native-server with 6-alpha

### ISSUE THREAD

**Issue by astriskit** [storybookjs/react-native#349]
**Describe the bug**
The infinite loading issue is there. Seemingly specifying host and port doesn't work either.
**To Reproduce**
Use the setup-guide to create the project; 
And run `start-storybook`, optionally with the `-p <Port>` and `-h <Host>`.
And run `expo start`.
And head to device, to run the app on device by scanning qrcode on the web-interface, as with all the expo-apps.

**Expected behavior**
The web-interface should stop loading and control the navigation on device.

**System:**
 System:
    OS: macOS 12
    CPU: intel i-5
  Binaries:
    Node: 16.14.0
    Yarn: 1.22.18 
    npm: 8.3.1 
  Browsers:
    Chrome: 100.0.4896.88
    Firefox: 99.0.1
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: 6.3 => 6.3.13 
    @storybook/addon-controls: 6.3 => 6.3.13 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-actions: ^6.0.1-beta.5 => 6.0.1-beta.5 
    @storybook/addon-ondevice-backgrounds: ^6.0.1-beta.5 => 6.0.1-beta.5 
    @storybook/addon-ondevice-controls: ^6.0.1-beta.5 => 6.0.1-beta.5 
    @storybook/addon-ondevice-notes: ^6.0.1-beta.5 => 6.0.1-beta.5 
    @storybook/react-native: ^6.0.1-beta.5 => 6.0.1-beta.5 
    @storybook/react-native-server: ^5.3.23 => 5.3.23

**Comment by dannyhw** [comment]
@astriskit hey thanks for your taking the time to create this issue. Currently the server is not supported for 6.0, so this is expected.  

The plan is to replace it or rework it later after the initial release of 6.0.

**Comment by astriskit** [comment]
@dannyhw - thanks for the info. 

Closing since [wont-fix](https://github.com/storybookjs/react-native/issues/349#issuecomment-1100046293) for now.
