### ISSUE TITLE
build-storybook failing on @storybook/react-native: 5.3.25

### ISSUE THREAD

**Issue by NM-2000** [storybookjs/react-native#355]
**Describe the bug**
"build-storybook" command failing on @storybook/react-native: 5.3.25

**To Reproduce**
1. npx -p @storybook/cli sb init --type react_native
2. Once RN storybook is installed, execute `npm run build-storybook`

**Expected behavior**
StoryBook should be built successfully.

**Actual behaviour**
"build-storybook" command doesn't exist.

**Comment by dannyhw** [comment]
@NM-2000 this is a duplicate so I'm closing please continue any discussion on the existing issue #287

**Comment by NM-2000** [comment]
Sure @dannyhw. Thanks!
