### ISSUE TITLE
Facebook Login stopped working iOS

### ISSUE THREAD

**Issue by sagark1510** [storybookjs/react-native#356]
**Describe the bug**
Storybook in react native was working fine. I integrated react-native-fbsdk-next and added login feature. However, after Login call completes the promise coming from the native to JS never gets resolved on iOS. The fun thing is as soon as I comment the import storybook line it starts working. Not sure what is wrong here but it happens. 

**To Reproduce**
1. integrate and import stroybooks
2. integrate react-native-fbsdk-next
3. add the login code
4. promise won't resolve or reject

**Expected behavior**
The promise should be resolved or rejected in iOS

**Screenshots**
 N/A

**Code snippets**
index.js
```
import {AppRegistry} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';
import Config from './src/constants/config';
import StorybookApp from './src/StorybookApp';

let Main = App;

if (Config.STORYBOOK) {
  Main = StorybookApp;
}

AppRegistry.registerComponent(appName, () => Main);
```

**System:**
```
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  Binaries:
    Node: 14.17.2 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 98.0.1
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21 
    @storybook/addon-knobs: ^5.3 => 5.3.21 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.25 => 5.3.25 
    @storybook/react-native: ^5.3.25 => 5.3.25 
    @storybook/react-native-server: ^5.3.23 => 5.3.23 
```
**Additional context**
Same has happened with someone else as well. Here you can check this comment. 
https://github.com/thebergamo/react-native-fbsdk-next/issues/105#issuecomment-954688508

**Comment by dannyhw** [comment]
@sagark1510 please try my solution in #20 using patch package and see if it resolves this for you.

https://github.com/storybookjs/react-native/issues/20#issuecomment-1046101914

**Comment by dannyhw** [comment]
It's been a while without a response so I'm closing this issue for now. Let me know if you want me to re-open this.
