### ISSUE TITLE
@storybook/cli sb init adds incorrect addons

### ISSUE THREAD

**Issue by Dhillon-Prabh** [storybookjs/react-native#357]
**Describe the bug**
The auto-generated file `addons.js` is populated incorrectly to have values such as:
'@storybook/addon-actions/manager'
which cause `yarn storybook` to crash with the error 'Module not found: '@storybook/addon-actions/manager''.
 It should have the value '@storybook/addon-actions/register'
**To Reproduce**
create a new react-native (in my case) project and run the init command from the docs.

**Expected behavior**
init should not incorrectly populate files.

**Comment by dannyhw** [comment]
The command you are looking for is this one `npx -p @storybook/cli sb init --type react_native`

**Comment by Dhillon-Prabh** [comment]
yup, that's what I used. But after successfully running this command you will find the issue I described above. Just posted this issue as a fyi 'cause it took a hot few mins to realise '.../manager' is incorrect.

**Comment by dannyhw** [comment]
@Dhillon-Prabh well I think that shouldn't be the case unless you've installed a newer version of addons. What does your package.json look like?

**Comment by Dhillon-Prabh** [comment]
unfortunately I am unable to share that as it is a private repo but I'd go ahead and close this issue since I got it to work eventually.

**Comment by Dhillon-Prabh** [comment]
I created a test project and ran the command `npx -p @storybook/cli sb init --type react_native` and here's the content of package.json:
```
{
  "name": "storybooktest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "storybook": "start-storybook -p 7007",
    "build-storybook": "build-storybook"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.18.2",
    "@storybook/addon-actions": "^5.3.21",
    "@storybook/addon-knobs": "^5.3.21",
    "@storybook/addon-links": "^5.3.21",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.25",
    "@storybook/react-native": "^5.3.25",
    "@storybook/react-native-server": "^5.3.23",
    "babel-loader": "^8.2.5"
  },
  "dependencies": {}
}
```
and addons.js:
```
import '@storybook/addon-actions/manager';
import '@storybook/addon-links/manager';
import '@storybook/addon-knobs/manager';
```
If I am not mistaken, it should be '.../register' instead of manager for the above imports.
Moreover, I just realised that the auto-installed dependencies don't have the latest versions (6.x.x).

*Q:* I am trying to add https://storybook.js.org/docs/react/essentials/toolbars-and-globals for context. Is it doable for react-native? do I need to update all dependencies manually to 6.x?
Appreciate it!

**Comment by dannyhw** [comment]
React native storybook stable is at 5.3 so it's intentionally installing those versions since v6 is not totally compatible. If you want to use v6 you need to be on the beta version.

I'm reluctant to change the cli template since its been working like that for a long time so I'd find it strange if it stopped working now. Does it not work in your test project?

**Comment by dannyhw** [comment]
If you can explain in more detail what you want to achieve I'm happy to help.

**Comment by amaralcamilla** [comment]
It happened the same here (same code, same problem). I replaced `/manager` with `/register` at those imports. It seems that works, but the sidebar doesn't render.

How did you resolved?

**Comment by dannyhw** [comment]
The issue with the cli should be resolved in the latest version of the cli.

If you check the pinned issues there is one about the sidebar not loading with some discussion.
