### ISSUE TITLE
[React Native] Virtual device simulator in web preview

### ISSUE THREAD

**Issue by atticoos** [storybookjs/react-native#36]
Currently the web preview for React Native storybooks is empty, as it uses the device to display the components.

It would be interesting to embed a device directly in the storybook webpage via a tool like https://appetize.io/

[Here's a demo](https://appetize.io/embed/7fvyvt159mfnw92dr23a651ugg?autoplay=true&orientation=portrait&device=iphone6splus&deviceColor=black&scale=50&language=en&osVersion=9.3), via https://github.com/Themoji/ios/pull/12#issuecomment-215836315

My only concern is https://appetize.io/pricing -- hard to tell if the free plan is a 100-minute total usage cap, such that it might not be a good fit.

Related to storybookjs/storybook#836

**Comment by clearly-outsane** [comment]
Did this go anywhere? It sure is useful for stakeholders like someone mentioned

**Comment by dannyhw** [comment]
@clearly-outsane storybook/native is a version of storybook for native code that uses appium, it is technically possible to use with react native storybook. 

If you just want to render react native in the web then you can use addon-react-native-web to render react native stories in reactjs storybook. Which personally I think is an easier option for sharing with stakeholders.

Heres some information about the react-native-web addon
https://www.dannyhwilliams.co.uk/introducing-react-native-web-storybook
