### ISSUE TITLE
Addons import fail

### ISSUE THREAD

**Issue by rdgomt** [storybookjs/react-native#378]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@storybook/react-native@6.0.1-beta.7` for the project I'm working on.

I was trying to use @storybook/addon-react-native-web as an addon in my project, but it fails to be imported in storybook.requires.js because this addon exports nothing from @storybook/addon-react-native-web/register.

Environment:
"@storybook/addon-react-native-web": "0.0.18",
"@storybook/builder-webpack5": "^6.5.10",
"@storybook/cli": "^6.5.10",
"@storybook/manager-webpack5": "^6.5.10",
"@storybook/react": "^6.5.10",
"@storybook/react-native": "^6.0.1-beta.7",

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@storybook/react-native/scripts/loader.js b/node_modules/@storybook/react-native/scripts/loader.js
index bba60f1..bac859c 100644
--- a/node_modules/@storybook/react-native/scripts/loader.js
+++ b/node_modules/@storybook/react-native/scripts/loader.js
@@ -74,7 +74,7 @@ function writeRequires({ configPath, absolute = false }) {
   const storyRequires = storyPaths.map((storyPath) => `require("${storyPath}")`).join(',');
   const path_array_str = `[${storyRequires}]`;
 
-  const registerAddons = main.addons.map((addon) => `import "${addon}/register";`).join('\n');
+  const registerAddons = main.addons.map((addon) => `import "${addon}";`).join('\n');
   let enhancersImport = '';
   let enhancers = '';
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by dannyhw** [comment]
Hey thats actually not the intended use of addon-react-native-web, its a web specific addon so you shouldn't be including it in your ondevice storybook. It is instead used on a web setup (react) an example of which can be found in this project https://github.com/dannyhw/expo-template-storybook

In this setup there are two separate storybook configs: .ondevice and .storybook

**Comment by rdgomt** [comment]
Hey @dannyhw, thanks for your response, but when I remove addon-react-native-web from the project the storybook web fails to build.

ModuleParseError: Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

<img width="860" alt="Captura de Tela 2022-08-22 às 09 25 40" src="https://user-images.githubusercontent.com/23437436/185920850-ee3a19bc-e22f-445b-85a3-3ed4a2c89d90.png">

**Comment by rdgomt** [comment]
Guys, now I did a fresh install following https://github.com/dannyhw/react-native-storybook-starter/ and everything is working fine. Sorry for the inconvenience.

**Comment by dannyhw** [comment]
ok glad you were able to get it working 🙏
