### ISSUE TITLE
`@storybook/addon-actions` & `@storybook/addon-ondevice-actions` are not working

### ISSUE THREAD

**Issue by alechp** [storybookjs/react-native#38]
I'm using `@storybook/react-native` and `@storybook/react-native-server` and having the same issue (or at least same error message) as described here: https://github.com/storybooks/storybook/issues/6471#issue-431269970 (ie. `synthetic event is used for performance reasons error`) 

## Summary
* `@storybook/react-native`: No addons are shown on the device (under the `addons` tab on iOS Simulator)
* `@storybook/react-native-server`: Unlike `@storybook/react-native`, the `addons` tab displays as expected. However, when clicking a button with an `action()` handler on it (eg.`<Button onPress={action("clicked-text")}>`), a "synthetic event handler" error is thrown recursively. 

## Source (`storybook/stories/index.js`)

```js
storiesOf("Button", module)
  .addDecorator(getStory => <CenterView>{getStory()}</CenterView>)
  .add("with text", () => (
    <Button onPress={action("clicked-text")}>
      <Text>Hello Button</Text>
    </Button>
  ))
```

## Error
The error below recurses

### Screenshot
![Screen Shot 2019-05-17 at 11 01 05 AM](https://user-images.githubusercontent.com/3058939/57947515-f48e4180-7893-11e9-84ef-156c4d2bbfdf.png)

### Text
```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're %s `%s` on a released/nullified synthetic event. %s. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information., accessing the property, target, This is set to null
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:619:8 in warningWithoutStack
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:1577:10 in warn
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:1569:9 in get$$1
* [native code]:null in stringify
- node_modules/@storybook/react-native/node_modules/@storybook/channel-websocket/dist/index.js:67:46 in sendNow
- node_modules/@storybook/react-native/node_modules/@storybook/channel-websocket/dist/index.js:56:21 in send
- node_modules/@storybook/channels/dist/index.js:126:32 in handler
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:152:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:200:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:464:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:320:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:17 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```

### Chrome (`@storybook/react-native-server`)
![Screen Shot 2019-05-17 at 11 00 44 AM](https://user-images.githubusercontent.com/3058939/57947572-1982b480-7894-11e9-9341-7cb320633d87.png)

### iOS Simulator (`@storybook/react-native`)
<img width="545" alt="Screen Shot 2019-05-17 at 11 06 06 AM" src="https://user-images.githubusercontent.com/3058939/57947530-fd7f1300-7893-11e9-8849-3b0a07acea9b.png">
<img width="545" alt="Screen Shot 2019-05-17 at 11 04 03 AM" src="https://user-images.githubusercontent.com/3058939/57947531-fd7f1300-7893-11e9-8530-e04c1d8b982d.png">

### package.json

> Also, if you're wondering why I'm using `@storybook/react-native-server@5.1.0-alpha.7` instead of `@storybook/react-native-server@5.1.0-beta.0` please see this issue: https://github.com/storybooks/storybook/issues/6769

```json
  "scripts": {
    "android": "expo start --android",
    "build": "yarn run build:components",
    "build:components": "webpack --config ./webpack.components.js",
    "eject": "expo eject",
    "expo": "expo start",
    "ios": "expo start --ios",
    "start": "npm-run-all --parallel expo storybook",
    "storybook": "start-storybook -p 7007"
  },
  "dependencies": {
    "@emotion/native": "^10.0.11",
    "expo": "^32.0.0",
    "native-base": "^2.12.1",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-router": "^5.0.0"
  },
  "devDependencies": {
    "@babel/preset-react": "^7.0.0",
    "@emotion/core": "^10.0.10",
    "@storybook/addon-actions": "^5.0.11",
    "@storybook/addon-links": "^5.0.11",
    "@storybook/addon-storysource": "^5.0.11",
    "@storybook/addons": "^5.0.11",
    "@storybook/react-native": "^5.0.11",
    "@storybook/react-native-server": "5.1.0-alpha.7",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.5",
    "babel-preset-expo": "^5.0.0",
    "babel-runtime": "^6.26.0",
    "duplicate-package-checker-webpack-plugin": "^3.0.0",
    "emotion-theming": "^10.0.10",
    "npm-run-all": "^4.1.5",
    "prop-types": "^15.7.2",
    "react-dom": "16.5.0",
    "size-plugin": "^1.2.0",
    "storybook-react-router": "^1.0.5",
    "webpack-cli": "^3.3.2",
    "webpack-node-externals": "^1.7.2"
  },
```

#### addons.js
```js
import "@storybook/addon-actions/register";
import "@storybook/addon-links/register";
import "@storybook/addon-storysource/register";
```

#### rn-addons.js
```js
import "@storybook/addon-ondevice-actions/register";
import "@storybook/addon-ondevice-links/register";
import "@storybook/addon-ondevice-storysource/register";
```

### Quick Fix
Haven't found a quick fix yet (besides not using `@storybook/addon-actions` / `@storybook/addon-ondevice-actions`). 

I'm going to try upgrading `react-dom` like suggested here: 
https://github.com/storybooks/storybook/issues/6471#issue-431269970

I'll update if that progresses the "synthetic event" error.

**Comment by cloud-walker** [comment]
Hi, its working for me, I've installed both `addon-ondevice-actions` and `actions` but I've registered only `addon-ondevice-actions`, but I import `addon-actions` in the stories!

**Comment by dbudziwojski** [comment]
I'm still seeing this issue, `action("clicked-text")` continues to not cause the action logger to appear, whilst the Addons tab continued to show "No adding loaded". Warning appears as per original documentation. I've attempted the import of `addon-ondevice-actions`to no avail.

**Comment by dannyhw** [comment]
does anyone still have this issue? if so it would be good if it could be reproduced in a branch using the example app. Try the reproduction steps in the contributing doc or make an expo snack based on the one in the readme.

**Comment by WarrenBuffering** [comment]
Thank you @cloud-walker. I've been trying to figure this one out for too long now. Honestly I'm really just struggling to find good docs for Storybook's setup pertaining to RN. There's what looks like an official tutorial, but they contradict the setup instructions on the actual package. Does anyone know what setup instructions are up to date? If you do could you share the link?

**Comment by dannyhw** [comment]
@WarrenBuffering currently I'm working with the tutorial maintainer to improve it but honestly the tutorial doesn't work for me and that's why I've given my own version of the getting starting guide here on the repo (still a work in progress). 

There is also an issue with the cli init command for react native, I've already fixed in the alpha version (@next) so hopefully that will get released soon. It will get released with 6.1 of storybook since the cli is linked with the main storybook repo.

**Comment by dannyhw** [comment]
also in regards to this specific issue it's related to storybook server and I'm thinking it's probably fixed in v6 of storybook so when I'm able to make a v6 for react native that would hopefully resolve this issue. If I can find the root cause I will try to get a patch for 5.3 though.


Just a side note:
From my experience this error doesn't actually cause anything to fail it's just a nuisance. In fact you can see that it's a warning not a full on error.

**Comment by mashaalmemon** [comment]
I just started using storybook and noticed us react-native folks are still on 5.3 whereas the rest of the storybook ecosystem is on 6.3! 

For anyone still experiencing this error on 5.3 with react native, looking at the error experienced closer it says:


_Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `isPropagationStopped` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://reactjs.org/link/event-pooling for more information._

Using @alechp 's example which is from the storybook react-native 'Hello World':

```js
storiesOf("Button", module)
  .addDecorator(getStory => <CenterView>{getStory()}</CenterView>)
  .add("with text", () => (
    <Button onPress={action("clicked-text")}>
      <Text>Hello Button</Text>
    </Button>
  ))
```

To get rid of the nuisance error we can just replace

```js
onPress={action("clicked-text")}
```

with 
```js
onPress={(e)=>{ e.persist(); action('clicked-text')(e)}}
```

Ultimately we're just calling `event.persist()` before calling the handler generated by `action`. Once this is done, e everything else seems to work the same (that is the action feeds through to the react-native-server), without the nuisance error!

**Comment by rusakovic** [comment]
@mashaalmemon 
Great. Thank you. This bug is still not solved.

For google search:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `StoryView`.
```

**Comment by traviswimer** [comment]
I ran into this error while using the [default React Native stories.](https://github.com/storybookjs/storybook/blob/7064642e1aee7786c77fe735c064c0c29dbcee01/lib/cli/src/generators/REACT_NATIVE/template-csf/storybook/stories/Welcome/Welcome.stories.js)

This probably isn't exactly the same problem that this issue is discussing, but I want to mention it in case it helps.

For me the problem was that when these default stories import their `index.js` file, they do so like this:
```
import Welcome from '.';
```

This results in an error, but I was able to prevent the error by actually including the `index` file name in the `import`:
```
import Welcome from './index';
```

I'm not sure if this is just a result of my specific environment or if it is a bug in the Storybook default examples. I am using Typescript, so maybe that is part of the problem. (isn't it always 😏)

**Comment by aike19115** [comment]
@traviswimer Thanks for your answer, it solved the problem I was facing! (Expo project with TypeScript)

**Comment by fontesrp** [comment]
@traviswimer you're my hero

**Comment by dannyhw** [comment]
this seems like an old issue so I'm closing as part of a cleanup, let me know if it needs to be reopened.
