### ISSUE TITLE
sb-rn-get-stories does not work with main.ts file

### ISSUE THREAD

**Issue by diginikkari** [storybookjs/react-native#390]
**Describe the bug**

Generating stories using provided `sb-rn-get-stories` script fails when  using `main.ts` instead of `main.js`.

**To Reproduce**
1. Create .storybook config using typescript files:
main.ts
``` typescript
import type { StorybookConfig } from '@storybook/core-common';

const config: StorybookConfig = {
  stories: ['./FakeStory.stories.tsx'],
  addons: [
    '@storybook/addon-ondevice-notes',
    '@storybook/addon-ondevice-controls',
    '@storybook/addon-ondevice-backgrounds',
    '@storybook/addon-ondevice-actions',
  ],
};

export default config;
```
2. run: `npx sb-rn-get-stories`

Fails with error: `Error: Cannot find module '/PATH/.storybook/main.js'

**Expected behavior**
Expecting script to generate valid `storybook.requires.js`-file.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Environment Info:

  System:
    OS: macOS 13.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 100.0
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: ~6.5.13 => 6.5.13 
    @storybook/addon-ondevice-actions: 6.0.1-beta.9 => 6.0.1-beta.9 
    @storybook/addon-ondevice-backgrounds: 6.0.1-beta.9 => 6.0.1-beta.9 
    @storybook/addon-ondevice-controls: 6.0.1-beta.9 => 6.0.1-beta.9 
    @storybook/addon-ondevice-notes: 6.0.1-beta.9 => 6.0.1-beta.9 
    @storybook/core-server: ~6.5.13 => 6.5.13 
    @storybook/react-native: 6.0.1-beta.9 => 6.0.1-beta.9 

**Additional context**
I cloud try to make PR to fix this if is not something that is already in process?

**Comment by dannyhw** [comment]
@diginikkari seems like something we should support, just made a PR #391

**Comment by diginikkari** [comment]
Cool, that was fast 🔥. Note that `main.js` and `preview.js` are also hard coded in `watcher.js`.

**Comment by dannyhw** [comment]
Good point, I'll check that a bit later on. Thanks for your feedback 🙏

**Comment by diginikkari** [comment]
Fixed in #391

**Comment by alexbchr** [comment]
I am currently on RC.3 and #391 seems to fix the fact that `main.ts` isn't found, however the Typescript code inside doesn't seem to get compiled. I keep getting errors with the imports:

```
// This is in main.ts
import path from 'path'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by dannyhw** [comment]
@alexbchr can you try running the get stories command with ts-node? 🤔

**Comment by alexbchr** [comment]
@dannyhw I tried running `ts-node @storybook/react-native/bin/get-stories.js`, but that was failing, just like it wasn't able to find `get-stories.js` in that path, which is honestly really weird.

That being said, I ended up having it working by creating a `main.js` file next to my `main.ts` with the following content in it:
```js
// Fix to have `main.ts` work with Storybook React Native
require('ts-node/register')
module.exports = require('./main.ts')
```
