### ISSUE TITLE
Stories not loading on Release builds

### ISSUE THREAD

**Issue by wkoutre** [storybookjs/react-native#399]
**Describe the bug**
On `release` builds, the on device Navigator is empty. On `debug` builds, it loads as expected.

**To Reproduce**
Checkout [this sample repo](https://github.com/wkoutre/react-native-storybook_demo).

- Clone
- Run `yarn install`
- run `npx react-native run-android --variant release` (or build iOS for release)
- open on sim/emulator/real device > see an empty Navigator
- run `yarn android` or `yarn ios` > see the Navigator load as expected

**Expected behavior**
I expect the on-device GUI to behave the same in a `release` build as in a `debug` build.

**Screenshots**
iOS Release build

![image](https://user-images.githubusercontent.com/13321210/202804458-d145f898-5dae-4137-96f9-5506fc5b5b08.png)

iOS Debug build

![image](https://user-images.githubusercontent.com/13321210/202806093-819a0db6-4436-4c18-af76-49cc4e87c5e6.png)

**Code snippets**
[Sample repo](https://github.com/wkoutre/react-native-storybook_demo)

Partial console output from `adb logcat '*:S' ReactNative:V ReactNativeJS:V` on app launch on Android

```
11-18 13:31:11.165  3439  3628 E ReactNativeJS: Error reading preview.js:
11-18 13:31:11.167  3439  3628 E ReactNativeJS: [TypeError: Cannot read property 'accept' of undefined]
```

**System:**

System:
  OS: macOS 13.0
  CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
Binaries:
  Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
  npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
Browsers:
  Chrome: 107.0.5304.110
  Firefox: 103.0
  Safari: 16.1
npmPackages:
  @storybook/addon-controls: 6.3 => 6.3.13 
  @storybook/addon-ondevice-controls: 6.0.1-beta.9 => 6.0.1-beta.9 
  @storybook/addons: 6.3.13 => 6.3.13 
  @storybook/react-native: 6.0.1-beta.9 => 6.0.1-beta.9

**Comment by haivle** [comment]
I have the same issue

**Comment by dannyhw** [comment]
Hey @wkoutre @haivle  sorry about that a fix is coming, it was already resolved in https://github.com/storybookjs/react-native/pull/397

**Comment by dannyhw** [comment]
solved in 6.0.1-beta.10, please try it out

**Comment by wkoutre** [comment]
All good now, thanks!

**Comment by dannyhw** [comment]
@wkoutre thanks for reporting and for following up 🙇
