### ISSUE TITLE
Object is not a constructor

### ISSUE THREAD

**Issue by RyanGst** [storybookjs/react-native#402]
**Describe the bug**
After starting metro bundler (with --clear-cache option) app freezes for some minutes, then crashes with message "Object is not a constructor" 

**To Reproduce**
1. Run npx -p @storybook/cli sb init --type react_native
2. Export StorybookUIRoot as entry point
3. Start metro bundler

**Expected behavior**
Expect StorybookUIRoot to be rendered.

**Screenshots**
![Screenshot_1669122196](https://user-images.githubusercontent.com/37024302/203321449-8075b51f-8df5-43b8-aa48-ad9a3d00d0b7.png)

**Code snippets**

```
import { AppRegistry } from 'react-native';
import { getStorybookUI, configure, addDecorator } from '@storybook/react-native';
import { withKnobs } from '@storybook/addon-knobs';
import './rn-addons';
addDecorator(withKnobs);
configure(
  () => {
    require('./stories');
  },
  module,
  false
);
const StorybookUIRoot = getStorybookUI({});
// If you are using React Native vanilla and after installation you don't see your app name here, write it manually.
// If you use Expo you should remove this line.
AppRegistry.registerComponent('main', () => StorybookUIRoot);

export default StorybookUIRoot;
```

**System:**
```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Firefox: 107.0
  npmPackages:
    @storybook/addon-actions: ^6.5.12 => 6.5.13 
    @storybook/addon-knobs: ^6.4.0 => 6.4.0 
    @storybook/addon-links: ^6.5.12 => 6.5.13 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.26 => 5.3.26 
    @storybook/react-native: ^5.3.25 => 5.3.27 
    @storybook/react-native-server: ^5.3.23 => 5.3.23 
```

**Additional context**
Used storybook for several weeks, not sure how this bug appeared since I didn't make any changes to dependencies/configuration

**Comment by RyanGst** [comment]
Closing this because my project's dependencies were not clean, so I've been able to reproduce this (Object is not a Constructor) without calling storybook main component.

**Comment by dannyhw** [comment]
@RyanGst thanks for updating 🙏
