### ISSUE TITLE
RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by akucharczyk** [storybookjs/react-native#405]
**Describe the bug**
When I try to open Storybook, the application freeze and crashes after a while. In the console it spams a lot of errors.
```bash
 ERROR  RangeError: Maximum call stack size exceeded.
Error: Requiring module "node_modules/core-js/internals/is-constructor.js", which threw an exception: RangeError: Maximum call stack size exceeded.

 ```

**To Reproduce**
Render Storybook on an iOS simulator

**Expected behavior**
I expect to be able to use is.

**Code snippets**
Just did `npx -p @storybook/cli sb init --type react_native`

**System:**
  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21 
    @storybook/addon-knobs: ^5.3 => 5.3.21 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-knobs: ^5.3.26 => 5.3.26 
    @storybook/react-native: 5.3.25 => 5.3.25 
    @storybook/react-native-server: ^5.3.23 => 5.3.23

**Comment by dannyhw** [comment]
Hey thanks for raising an issue. Do you have a reproduction or can you provide more detailed steps?

**Comment by dannyhw** [comment]
Can you try setting inline requires to false in your metro config?

**Comment by akucharczyk** [comment]
@dannyhw https://github.com/akucharczyk/storybook-react-native

**Comment by dannyhw** [comment]
@akucharczyk it works with inline requires false, I just ran it

**Comment by akucharczyk** [comment]
Just saw it, but I get on my actual app now `Object is not a constructor`
![image](https://user-images.githubusercontent.com/25926746/203985306-8894e889-b33d-4028-9ff0-ef969c47d0be.png)
I will try to reproduce this in this repo

**Comment by dannyhw** [comment]
for me:
![image](https://user-images.githubusercontent.com/3481514/203985504-c1940a1a-baf7-4a63-ac7e-8d675343278c.png)

**Comment by dannyhw** [comment]
Object is not a constructor probably means you are exporting a component incorrectly or something like that, its usually what it refers to

**Comment by akucharczyk** [comment]
Where did I need to export them? 
I have my index.ts in the stories which loads all stories.

stories/index.ts
```js
import './BottomSheetCard.stories.tsx';
...
```
index.ts
```js
import {
  getStorybookUI,
  configure,
  addDecorator,
} from '@storybook/react-native';
import { withKnobs } from '@storybook/addon-knobs';
import './rn-addons.ts';

// enables knobs for all stories
addDecorator(withKnobs);

configure(() => {
  require('./stories');
}, module);

// Refer to https://github.com/storybookjs/react-native/tree/master/app/react-native#getstorybookui-options
// To find allowed options for getStorybookUI
const StorybookUI = getStorybookUI({
  asyncStorage: null,
  tabOpen: -1,
});

export default StorybookUI;
```
example story
stories/BottomSheetCard.stories.tsx
```js
import React from 'react';
import { storiesOf } from '@storybook/react-native';
import { number } from '@storybook/addon-knobs';
import { View } from 'react-native';

import { Text } from '@core/presentation/elements/BrandText';
import BottomSheetCard from '@core/presentation/elements/BottomSheetCard';

storiesOf('BottomSheetCard', module)
  .add('without content', () => (
    <BottomSheetCard endSnapPoint={number('endSnapPoint', 500)}>
      <View style={{ backgroundColor: 'red', height: 200 }} />
    </BottomSheetCard>
  ))
  .add('with content', () => (
    <BottomSheetCard
      endSnapPoint={number('endSnapPoint', 500)}
      onClose={() => console.log('close')}>
      <View>
        <Text>I am Content</Text>
      </View>
    </BottomSheetCard>
  ));

```

**Comment by dannyhw** [comment]
I'm referring to just using react correctly, nothing specific. If you reproduce I can be more helpful

**Comment by rodgomesc** [comment]
<img align="left" src="https://user-images.githubusercontent.com/4893591/204443528-22fd1d45-a322-489b-baa0-c29425b8df82.png" width="25%"/>


 i'm using this lib for quite a few months, and after my `yarn.lock` get upgraded in one PR i fall in to that issue, tried to walk through the changes but it was huge and i got lost , after double check everything in [documentation](https://github.com/dannyhw/expo-template-storybook/blob/main/metro.config.js) it didn't worked, also compared with [https://github.com/dannyhw/expo-storybook-starter](https://github.com/dannyhw/expo-storybook-starter) everything was in place except for the lib versions, so after use same lib versions as `expo-storybook-starter` it worked


#### that's my diff, hope this work for you as well


<img align="left" src="https://user-images.githubusercontent.com/4893591/204442924-c5990c9c-dbcb-40de-bc76-be3701e07397.png" width="65%"/>

**Comment by akucharczyk** [comment]
@rodgomesc Thank you for sharing, I chose the same way and upgraded to 6.0.1-beta

**Comment by dannyhw** [comment]
Please provide a reproduction if possible.

Also try the latest beta-10

**Comment by KPS250** [comment]
System Version: macOS 13.0 (22A380)
Model Name: MacBook Pro Apple M2

"react-native": "0.71.3"
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native-safe-area-context": "^4.5.0",
"@react-native-async-storage/async-storage": "^1.17.11",
"@react-native-community/datetimepicker": "^6.7.5",
"@react-native-community/slider": "^4.4.2",

"@storybook/addon-actions": "^6.5.14",
"@storybook/addon-controls": "^6.5.14",
"@storybook/addon-ondevice-actions": "6.5.0-rc.0",
"@storybook/addon-ondevice-controls": "6.5.0-rc.0",
"@storybook/react-native": "6.5.0-rc.0",

I created  a new TS RN project and integrated Storybook using CLI. On build and run I get the below issue

<img width="334" alt="image" src="https://user-images.githubusercontent.com/33733142/220014987-e1c34427-0ef7-4d7f-b0bb-ddb32bdaddf2.png">

**Comment by dannyhw** [comment]
@KPS250 could you provide a reproduction? Also can you try adding sbmodern to the resolvers in metro config like this 

```

module.exports = {
  /* existing config */
  resolver: {
    resolverMainFields: ['sbmodern', 'react-native', 'browser', 'main'],
  },
};

```

**Comment by feng-yu-healthbank** [comment]
Having the same error on an empty project created by `react-native init`.

System:
OS: Windows 11 22H2 22621.1413 Windows Feature Experience Pack 1000.22639.1000.0
CPU: AMD Ryzen 5900X 
GPU: AMD Radeon 7900XTX

Binaries:
Node: v18.2.0
Yarn: 1.22.19
npm: 9.6.2
Java: 15.0.2

Browsers:
Edge Version 111.0.1661.54 (Official build) (64-bit)


**How to reproduce:**

```
 npx react-native@latest init myapp && cd myapp && npx -p @storybook/cli sb init --type react_native -f -y
```

npm packages: 
It's basically empty. Created fresh by `react-native` and `@storybook/cli`.
```
"react": "18.2.0",
"react-native": "0.71.4"

"@storybook/addon-actions": "^5.3",
"@storybook/addon-knobs": "^5.3",
"@storybook/addon-links": "^5.3",
"@storybook/addon-ondevice-actions": "^5.3.23",
"@storybook/addon-ondevice-knobs": "^5.3.26",
"@storybook/react-native": "^5.3.27",
"@storybook/react-native-server": "^5.3.23",
```


Edit `App.tsx`, remove all the code and use only storybook UI.
```
import {getStorybookUI} from '@storybook/react-native';
import React from 'react';

const StorybookUI = getStorybookUI({});

function App(): JSX.Element {
  return <StorybookUI />;
}
export default App;

```

Then run `yarn android`


![228204501-1e83bff7-3141-46bb-85bb-97985bb992d2](https://user-images.githubusercontent.com/125230892/228207197-9f34e510-c3e0-4f5e-bf38-08adc89d503e.png)




Adding or removing `sbmodern` and/or `resolver` made no difference.
```
resolver: {
    resolverMainFields: ['sbmodern', 'react-native', 'browser', 'main'],
},
```





Shall I downgrade react-native to get storybook to work? 

If so, which version of react-native should I downgrade to?

**Comment by dannyhw** [comment]
Sbmodern resolver only works for storybook 6.5+, try using the 6.5 release candidate with `npx sb@next init --type react_native`

**Comment by feng-yu-healthbank** [comment]
@dannyhw  Thank you. It built successfully! That was very helpful. 

Now let me see how to apply it to my production project... success

**Comment by hduoc2003** [comment]
> @KPS250 could you provide a reproduction? Also can you try adding sbmodern to the resolvers in metro config like this
> 
> ```
> 
> module.exports = {
>   /* existing config */
>   resolver: {
>     resolverMainFields: ['sbmodern', 'react-native', 'browser', 'main'],
>   },
> };
> ```

You save my day bro. Can you please explain why above code is necessary? I think it should be described in readme. I cant find any guide for the current version of storybook, except this readme, but i think its set up part is quite not clear. Sorry for my poor english!!!

**Comment by dannyhw** [comment]
@hduoc2003 this is because storybook exports multiple different module types (commonjs, esm etc) and sbmodern is a modern output without transpilation.

By putting sbmodern as the first one in the list then we resolve those modules instead of the commonjs output for example.

in the past polyfills from corejs in storybook have caused errors with react native which is why we try to resolve sbmodern

**Comment by osvaguillen** [comment]
> Can you try setting inline requires to false in your metro config?

@dannyhw is there a way for you to tell us why inline requires is causing this error? I am interested on knowing that.

**Comment by dannyhw** [comment]
@osvaguillen thats no longer the suggested fix, you can enable inline requires if you just set the resolvers like I mentioned here:

https://github.com/storybookjs/react-native/issues/405#issuecomment-1436683333

I explained the same issue here: https://github.com/storybookjs/react-native/issues/405#issuecomment-1501154722

The short answer is that polyfilled code from storybook core would break things. We use the resolver config option to resolve a more modern build of storybook core.

**Comment by Mazztwo** [comment]
I am running in to this issue after upgrading RN from 70.12 to 72.3.

      "@storybook/addon-actions": "^5.3",
      "@storybook/addon-knobs": "^5.3",
      "@storybook/addon-links": "^5.3",
      "@storybook/addon-ondevice-actions": "^5.3.23",
      "@storybook/addon-ondevice-knobs": "^5.3.25",
      "@storybook/react-native": "^5.3.25",

I have tried the sbmodern fix for metro.config, but it causes same error:

`
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');

const config = {
    resolver: {
        resolverMainFields: ['sbmodern', 'react-native', 'browser', 'main'],
    },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
`
<img width="695" alt="Screenshot 2023-08-23 at 11 34 39 AM" src="https://github.com/storybookjs/react-native/assets/10237098/704936a9-212e-487a-bf95-4602af7502c2">

**Comment by dannyhw** [comment]
@Mazztwo sbmodern is the fix but it only works on version 6 not on version 5.3.

**Comment by Mazztwo** [comment]
@dannyhw Updating everything to ~6.5 + the sbmodern fix completely solved all my issues. Thank you!!

**Comment by CatWithNineLives** [comment]
> Can you try setting inline requires to false in your metro config?

@dannyhw Hey can you tell me why does this fix work ?

**Comment by dannyhw** [comment]
@CatWithNineLives turning off inline requires shouldn't be needed anymore in v6.5 you can use the other fix with sbmodern outlined above.

The problem relates to the polyfills being used in storybook core v6 and below (removed in v7).

Probably by turning on inline requires it changes the behaviour of some code. Polyfills usually need to execute first so maybe an import got placed later or removed by the transform.

**Comment by see2ever** [comment]
try downgrade corejs

`"core-js": "3.23.5",`

**Comment by sandipndev** [comment]
Am I the only one who is getting this:

 ERROR  Error reading preview.js:
 ERROR  [ReferenceError: Property 'Buffer' doesn't exist]

**Comment by dannyhw** [comment]
@sandipndev if you have a different error please open a new issue that doesn't seem related to this issue.

**Comment by Nehal-Zeller** [comment]
I'm facing the same issue and resolverMainFields adding didn't help.

```
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const exclusionList = require('metro-config/src/defaults/exclusionList');

const path = require('path');
const workspaceRoot = path.resolve(__dirname, '../..');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

const config = {
  projectRoot: __dirname,
  watchFolders: [workspaceRoot],

  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter((ext) => ext !== 'svg'),
    sourceExts: [...sourceExts, 'svg', 'cjs'],
    blockList: exclusionList([/.maestro\/.*/, /mock-server\/.*/]),
    nodeModulesPaths: [path.resolve(workspaceRoot, 'node_modules')],
    extraNodeModules: {
      modules: workspaceRoot,
    },
  },
};

module.exports = mergeConfig(defaultConfig, config);

```

I have a mono-repo structure with only one node_modules sitting at the top. 
 
 "@storybook/react-native": "6.5.7",
 "react-native": "0.73.6",
 "react": "18.2.0",
