### ISSUE TITLE
storybook try to load native code on web mode

### ISSUE THREAD

**Issue by StarHosea** [storybookjs/react-native#408]
![image](https://user-images.githubusercontent.com/5615409/205199139-c44bb80e-d55b-4710-b3bb-4c18c5517586.png)

----

    "@storybook/addon-essentials": "6.5.13",
    "@storybook/addon-links": "6.5.13",
    "@storybook/addon-ondevice-actions": "6.0.1-beta.10",
    "@storybook/addon-ondevice-backgrounds": "6.0.1-beta.10",
    "@storybook/addon-ondevice-controls": "6.0.1-beta.10",
    "@storybook/addon-ondevice-notes": "6.0.1-beta.10",
    "@storybook/react-native": "6.0.1-beta.10",
    "@storybook/addon-react-native-web": "0.0.19",
    "@storybook/react": "6.5.13",
    "@storybook/docs-tools": "6.5.13"
-----

- .storybook main.js 
```
const path = require('path');
module.exports = {
  staticDirs: ['./public'],
  stories: [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-react-native-web",
  ],
  framework: "@storybook/react",
  features: {
    storyStoreV7: true,
  },
  webpackFinal: async (config, { configType })=>{
    // Make whatever fine-grained changes you need
    // Return the altered config
    return config;
  }
};
```
----

tw-map-view folder like this

```tsx
tw-map-view/
     __stories__
           index.stories.tsx
    index.ts
    TwMapView.native.tsx: which contains  native platform code
    TwMapView.tsx:  which only has web platform code


```
- index.stories.tsx
```tsx
import { TwMapView, TwMapViewSdk } from '../TwMapView';
export default {
  title: 'display/tw-map-view',
  component: TwMapView,
  parameters: {
    actions: { argTypesRegex: '^on.*' },
    docs: {
    },
  },
};
....some other code

```
----
I try some steps
- delte TwMapView.native.tsx ，restart storybook , works fine
- rename TwMapView to TwMapView.web.ts,  rename TwMapView.native.tsx to TwMapView.tsx,  storybook will break while loading TwMapview.tsx

**Comment by dannyhw** [comment]
Did you edit any webpack config? .web files should be be getting resolved first normally.

**Comment by dannyhw** [comment]
You could as a workaround specify in your stories glob a regex that ignores files with the .native extension.

**Comment by dannyhw** [comment]
Also this is the repo for storybook/react-native so this issue would be better suited to the storybook/addon-react-native-web

**Comment by StarHosea** [comment]
thanks for you help, i created an issue for  storybook/addon-react-native-web
