### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED when running yarn storybook

### ISSUE THREAD

**Issue by nikitph** [storybookjs/react-native#412]
**Describe the bug**
ERR_OSSL_EVP_UNSUPPORTED when running yarn storybook

**To Reproduce**
1.  Do a fresh install of storybook
2. run yarn storybook 

**Expected behavior**
storybook launches correctly 

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Environment Info:

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/WebstormProjects/makua/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Safari: 16.0
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21 
    @storybook/addon-knobs: ^5.3 => 5.3.21 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.26 => 5.3.26 
    @storybook/builder-webpack5: ^6.5.14 => 6.5.14 
    @storybook/manager-webpack5: ^6.5.14 => 6.5.14 
    @storybook/react-native: ^6.0.1-beta.11 => 6.0.1-canary.3 
    @storybook/react-native-server: ^5.3.23 => 5.3.23 

**Additional context**
based on some research it was suggested to use webpack 5 but that also doesnt fix the issue. 
module.exports = {
  core: {
    builder: 'webpack5',
  },
};

**Comment by dannyhw** [comment]
In this case its not possible to use webpack 5 but the issue is with ssl changes in node 18 that aren't supported in webpack 4 which has a workaround 

`NODE_OPTIONS=--openssl-legacy-provider yarn storybook`

**Comment by nikitph** [comment]
thanks that resolved it for me

**Comment by lpatrun** [comment]
When can we expect a real solution and not a workaround? @dannyhw

**Comment by dannyhw** [comment]
@lpatrun to be clear this is not a problem for storybook web for example with addon-react-native-web. It's only a problem for @storybook/react-native-server since its not possible to use webpack5 with that package yet.

The problem is already solved for storybook by using the webpack5 builder.

If you specifically care about @storybook/react-native-server then that might happen sometime after stable release.

**Comment by lpatrun** [comment]
@dannyhw thank you for quick response
