### ISSUE TITLE
got error TypeError: undefined is not an object (evaluating 'loadable.keys')

### ISSUE THREAD

**Issue by xiongemi** [storybookjs/react-native#416]
**Describe the bug**

Run the react native storybook and got this error:

```
 LOG  [TypeError: undefined is not an object (evaluating 'loadable.keys')]
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'this.storyStore.storyIndex.storyIdFromSpecifier')
```

library version:
```
    "@storybook/addon-essentials": "6.5.15",
    "@storybook/addon-ondevice-actions": "6.0.1-beta.11",
    "@storybook/addon-ondevice-backgrounds": "6.0.1-beta.11",
    "@storybook/addon-ondevice-controls": "6.0.1-beta.11",
    "@storybook/addon-ondevice-notes": "6.0.1-beta.11",
    "@storybook/core-server": "6.5.15",
    "@storybook/react": "6.5.15",
    "@storybook/react-native": "6.0.1-beta.11",
```

**To Reproduce**

**Expected behavior**

**Screenshots**
![Simulator Screen Shot - iPhone 12 - 2023-01-09 at 14 43 48](https://user-images.githubusercontent.com/16211801/211394581-d791ac53-83a1-49a3-bf8f-064e78b70244.png)
![Simulator Screen Shot - iPhone 12 - 2023-01-09 at 14 43 24](https://user-images.githubusercontent.com/16211801/211394591-76f9227e-3f05-40ab-8bee-80922c51ad88.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.
```
Environment Info:

  System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 94.0.2
    Safari: 16.0
  npmPackages:
    @storybook/addon-essentials: 6.5.15 => 6.5.15 
    @storybook/addon-ondevice-actions: 6.0.1-beta.11 => 6.0.1-canary.3 
    @storybook/addon-ondevice-backgrounds: 6.0.1-beta.11 => 6.0.1-canary.3 
    @storybook/addon-ondevice-controls: 6.0.1-beta.11 => 6.0.1-canary.3 
    @storybook/addon-ondevice-notes: 6.0.1-beta.11 => 6.0.1-canary.3 
    @storybook/builder-webpack5: 6.5.15 => 6.5.15 
    @storybook/core-server: 6.5.9 => 6.5.15 
    @storybook/manager-webpack5: 6.5.15 => 6.5.15 
    @storybook/react: 6.5.15 => 6.5.15 
    @storybook/react-native: 6.0.1-beta.11 => 6.0.1-beta.11 
```

**Additional context**

**Comment by leotm** [comment]
what does your `preview.js` look like? it works for me on `6.0.1-beta.11`
https://github.com/leotm/react-native-template-new-architecture/blob/master/.storybook/preview.js

**Comment by leotm** [comment]
also you mentioned library version: `6.0.1-beta.11`

but `npx -p @storybook/cli@next sb info` shows downgrading from  `6.0.1-beta.11` (December 2, 2022) to `6.0.1-canary.3 ` (October 28, 2022)?

here's how i upgraded to `6.0.1-beta.11` if helps
- https://github.com/leotm/react-native-template-new-architecture/issues/1284
- https://github.com/leotm/react-native-template-new-architecture/pull/1307

and happy to look at a repro if you have one ^

**Comment by dannyhw** [comment]
Npm is resolving the wrong package when you use ^ because the alpha/canary versions aren't numeric. Beta 11 is newer than the canary version.

**Comment by xiongemi** [comment]
i figure out the issue. here is my repo: https://github.com/xiongemi/studio-ghibli-search-engine/blob/main/apps/studio-ghibli-search-engine-mobile/src/storybook/storybook.ts
i upgrade my storybook version to 6.0.1-beta.11.
i use `react-native-story-loader`, when i change to `configure(() => loadStories(), module);`, this error goes away.

```
import { configure, getStorybookUI } from '@storybook/react-native';

import { loadStories } from '../../../../.storybook/story-loader';

configure(() => loadStories(), module);

const StorybookUIRoot = getStorybookUI();

export default StorybookUIRoot;
```

**Comment by dannyhw** [comment]
V6 doesn't need the loader since a story loader is built in. However there are some config changes. I would go through the manual setup guide and make sure you have the new config files and so on.
