### ISSUE TITLE
expo-router support

### ISSUE THREAD

**Issue by leemhenson** [storybookjs/react-native#425]
**Is your feature request related to a problem? Please describe.**
I've used the latest expo template to add RN Storybook to an app that I have that uses the latest RC of expo-router. I get ` TypeError: undefined is not a function (near '...(0, s.deprecate)...')` when attempting to switch to Storybook via the expo menu. 

**Describe the solution you'd like**
I'm guessing compatibility with expo-router hasn't been a priority so far as it's still pre-release, but it will be released soon so I guess this will be a factor for people in the short term.

**Describe alternatives you've considered**
Not using expo-router or not using Storybook.

**Are you able to assist bring the feature to reality?**
no

**Additional context**
n/a

**Comment by dannyhw** [comment]
@leemhenson hey thanks for creating this issue. Could you provide some information about your setup? What version of storybook are you using for example. If you have an example project too that could help.

**Comment by leemhenson** [comment]
Yeah of course a repro works perfectly. 😂 

https://github.com/leemhenson/rnstorybook-expo-router-repro

I guess it must be some sort of interaction with the rest of our app, if I can figure it out I'll reopen the issue with a link to the repro commit that breaks it.

**Comment by dannyhw** [comment]
@leemhenson haha thats always the way 😄 . Ok cool well tag me whenever you need me to check anything 🙏
