### ISSUE TITLE
Provide option to load storybook with navigator open

### ISSUE THREAD

**Issue by andrespch** [storybookjs/react-native#439]
**Is your feature request related to a problem? Please describe.**

A repetitive task when using the storybook is having to click on the navigator tab to open the navigator and search for a specific component.

**Describe the solution you'd like**
it'd be useful for me if I could set the default status for the navigator as `open`.

**Are you able to assist bring the feature to reality?**
yes

**Comment by dannyhw** [comment]
@andrespch actually this is already available just use the `tabOpen`  option in `getStorybookUI` 

```
 tabOpen: Number (0)
        -- which tab should be open. -1 Navigator, 0 Preview, 1 Addons
```

**Comment by dannyhw** [comment]
Since this is already possible im closing this issue, let me know if you want to reopen.

**Comment by andrespch** [comment]
thanks @dannyhw it works perfectly 🥳!
