### ISSUE TITLE
Invalid prop 'initValue' of type 'number' warning - Controls addon with list of numbers + generated arg types

### ISSUE THREAD

**Issue by arielger** [storybookjs/react-native#449]
**Describe the bug**

When using a list of numbers as options for a component property I get a warning when trying to change the selected value in the control for that propery.
Also, the new selected value for the property will be applied to the component but it won't show in the controls.

**To Reproduce**

1. I was able to reproduce this error in the [RN Storybook template](https://github.com/dannyhw/react-native-template-storybook) using the following code for the `Button.tsx` component:

```
export type ButtonProps = {
  number: keyof {
    1: "test";
    2: "test";
    3: "test";
    4: "test";
    5: "test";
    6: "test";
    7: "test";
    8: "test";
    9: "test";
  };
};

export const MyButton = ({ number }: ButtonProps) => (
  <View>
    <TouchableOpacity activeOpacity={0.8}>
      <Text>{number}</Text>
    </TouchableOpacity>
  </View>
);
```

2. Go to the app and try to select one of the options for the `number` prop

![image](https://user-images.githubusercontent.com/6318057/228269042-f2bc0e8f-d9a0-4341-8ef6-dacfd84da020.png)

3. Check error:

![image](https://user-images.githubusercontent.com/6318057/228263678-ebeee207-d10d-492f-8853-5faafdd78095.png)

**Expected behavior**
- No warning should appear when selecting the option
- Selected option should appear as selected in the control

**System:**

```
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 16.3
  npmPackages:
    @storybook/addon-actions: ^6.5.14 => 6.5.16
    @storybook/addon-controls: ^6.5.14 => 6.5.16
    @storybook/addon-essentials: ^6.5.14 => 6.5.16
    @storybook/addon-links: ^6.5.14 => 6.5.16
    @storybook/addon-ondevice-actions: next => 6.5.0-rc.11
    @storybook/addon-ondevice-backgrounds: next => 6.5.0-rc.11
    @storybook/addon-ondevice-controls: next => 6.5.0-rc.11
    @storybook/addon-ondevice-notes: next => 6.5.0-rc.11
    @storybook/addon-react-native-web: ^0.0.19 => 0.0.19
    @storybook/react: ^6.5.14 => 6.5.16
    @storybook/react-native: next => 6.5.0-rc.11
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by dannyhw** [comment]
@arielger thanks for the details, I'll check that.

**Comment by dannyhw** [comment]
you may want to try using a manual arg type using the select control type

**Comment by dannyhw** [comment]
@arielger seems like it was a simple fix, I will push the change now

**Comment by dannyhw** [comment]
@arielger can you try version 6.5.0-rc.12
