### ISSUE TITLE
Extra actions listed in ondevice actions tab

### ISSUE THREAD

**Issue by stevoland** [storybookjs/react-native#454]
**Describe the bug**
Pressing the ActionButton in `expo-example` generates more that one item in the ondevice actions tab

**To Reproduce**
Run `yarn ios` in `expo-example`
Select ActionButton > Basic
Open addons > actions
Tap "Press me!" - note 2 "pressed the button" actions
Tap "Press me!" - note another 3 actions

**Expected behavior**
One action listed per press.

Note the actions listed in `storybook-server` app are correct.

**Screenshots**

https://user-images.githubusercontent.com/30143/229112042-c00672ca-bcbc-4745-b7e9-ca5f5af78f6d.mp4

**System:**
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 108.0.1
    Safari: 15.6.1

**Comment by dannyhw** [comment]
@stevoland is this with the server running? that might cause it to double log I guess. Weird though, I'll need to check some stuff.

**Comment by stevoland** [comment]
@dannyhw

> is this with the server running?

Yes, sorry, this is only with the server running. I thought when I raised it that it was both with and without but I now realise that I had a server running from another project.
