### ISSUE TITLE
problem with launch command "yarn storybook"

### ISSUE THREAD

**Issue by albo084** [storybookjs/react-native#460]
**Describe the bug**
i'm trying to launch the demo from (https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/). When demo 
 starts 'taskbox' with the command 'yarn storybook' (or npm run)  in the terminal variable "STORYBOOK_ENABLED" is not recognized as an internal or external command operable program or batch file. I've tried to handle the operation declaration in package.json as `"sb-rn-get-stories&& STORYBOOK_ENABLED='true' expo start"` but unsucessfully does not seem to be fine. I've noted that this problem appear with powershell and git bash (also with the cmd).

**To Reproduce**

1) npx degit chromaui/intro-storybook-react-native-template#main taskbox
2) cd taskbox; yarn install; 
3)yarn storybook

**Expected behavior**
Starting the demo taskbox

**Screenshots**
![image](https://user-images.githubusercontent.com/25937427/230213506-455108f2-1a97-410f-9b34-9d4cb4be43f1.png)

**Code snippets**
```
{
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@storybook/core-common": "^7.0.2",
    "expo": "^48.0.9",
    "expo-constants": "~14.2.1",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.71.4",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@react-native-async-storage/async-storage": "^1.18.1",
    "@react-native-community/datetimepicker": "^6.7.3",
    "@react-native-community/slider": "^4.4.2",
    "@storybook/addon-actions": "^6.5.14",
    "@storybook/addon-controls": "^6.5.14",
    "@storybook/addon-ondevice-actions": "^6.5.1",
    "@storybook/addon-ondevice-controls": "^6.5.1",
    "@storybook/react-native": "^6.5.0-rc.12",
    "babel-loader": "^8.3.0",
    "react-native-safe-area-context": "^4.5.0"
  },
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "storybook-generate": "sb-rn-get-stories",
    "storybook-watch": "sb-rn-watcher",
    "storybook": "sb-rn-get-stories&& STORYBOOK_ENABLED='true' expo start",
    "storybook:ios": "sb-rn-get-stories&& STORYBOOK_ENABLED='true' expo start --ios",
    "storybook:android": "sb-rn-get-stories&& STORYBOOK_ENABLED='true' expo start --android"
  },
  "version": "1.0.0",
  "private": true,
  "name": "storybook-tutorial-template"
}
```

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.44)
  npmPackages:
    @storybook/addon-actions: ^6.5.14 => 6.5.16
    @storybook/addon-controls: ^6.5.14 => 6.5.16
    @storybook/addon-ondevice-actions: ^6.5.1 => 6.5.1
    @storybook/addon-ondevice-controls: ^6.5.1 => 6.5.1
    @storybook/core-common: ^7.0.2 => 7.0.2
    @storybook/react-native: ^6.5.0-rc.12 => 6.5.0-rc.12
  npmGlobalPackages:
    @storybook/cli: 7.0.2

**Additional context**

**Comment by dannyhw** [comment]
Sounds like a windows thing, I'll try to fix it tomorrow. Thanks for reporting.

**Comment by dannyhw** [comment]
Haven't gotten around to this yet but the fix is using crossenv to set the environment variables in the scripts. It's actually a change you can make manually since  those scripts come from the starter project.

**Comment by albo084** [comment]
Hi, 
I've tried to set `.env ` in my root  project folder but without any success (it would seem not scoped). However i've found a workaround installing `"react-native-dotenv"` and writing in `babel.config.js` this : 
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset','babel-preset-expo'],
  plugins: [
    ["module:react-native-dotenv", {
      "moduleName": "@env",
      "path": ".env",
      "blacklist": null,
      "whitelist": null,
      "safe": false,
      "allowUndefined": true
    }]
  ]
};

```

Finally i've imported "import `{ STORYBOOK_ENABLED } from "@env";"` and i've started it. just one thing, once i've runned "npm run storybook" with expo is normal that storybook CLI tells that there's no story? (i'mean  in the first time you run the application)


Updating*:

I've found a better solution, basically: 
app.config.js:
```
const env =require('dotenv').config().parsed;
export default ({ config }) => {
  return {
    ...config,
    name: "Storybook Tutorial Template",
    slug: "storybook-tutorial-template",
    extra: {
      storybookEnabled: env.STORYBOOK_ENABLED,
    }
}};
```
and in App.jsx  `import Constants from "expo-constants" ` and then   


`if (STORYBOOK_ENABLED==="true") {
    AppEntryPoint = require("./.storybook").default;
  }`


that's all. :)

**Comment by jamescrosswell** [comment]
> Haven't gotten around to this yet but the fix is using crossenv to set the environment variables in the scripts. It's actually a change you can make manually since those scripts come from the starter project.

I created a [pull request with this fix](https://github.com/chromaui/intro-storybook-react-native-template/pull/2).

**Comment by dannyhw** [comment]
@jamescrosswell thanks for your contribution 🙏🙇‍♂️
