### ISSUE TITLE
React-native-navigation with Storybook v6

### ISSUE THREAD

**Issue by jvenus99** [storybookjs/react-native#474]
I can't find anything that solves how to solve the error in components that use navigation for Storybook v6, as in the web version I have an addon for react-router, is there something similar for react-native-navigation in version 6?

**Comment by dannyhw** [comment]
@jvenus99  you can add a decorator that wraps the story with the navigation provider

**Comment by jvenus99** [comment]
I am using that in version 5, that decorator still working in version 6?

**Comment by dannyhw** [comment]
I don't know any reason why it wouldn't work.

in csf you can add decorators like this
```js
export const ButtonPrimary = {
  decorators: [
    (Story) => <Provider><Story/></Provider>
  ];
}
```

**Comment by jvenus99** [comment]
Cool, I was waiting for the addon for react-native-navigation to update my project, but now with the decorator I can use it, in the future will you make the addon for navigation?
