### ISSUE TITLE
Add storybook in react-native-builder-bob P

### ISSUE THREAD

**Issue by HenriqueSuel** [storybookjs/react-native#475]
I am trying to add storybook in example project. (Project create [react-native-builder-bob](https://github.com/callstack/react-native-builder-bob))

The idea of the lib is for it to be a component lib and I'm going to use the example (the project inside the example folder) as a documentation where I'm going to use the storybook to document the components created in the lib.

and I have this error:

<img width="1440" alt="Captura de Tela 2023-05-15 às 20 30 18" src="https://github.com/callstack/react-native-builder-bob/assets/22986830/a2b4f4de-9ad7-495a-93cb-e2c388b7b15d">

I suspect it's something in webpack but I'm not sure, can anyone help me?

Repo: https://github.com/HenriqueSuel/tem-roda-test

**Comment by HenriqueSuel** [comment]
I got revolser... by installing the react-native-web lib in my package

**Comment by dannyhw** [comment]
@HenriqueSuel glad its working!
