### ISSUE TITLE
Can't resolve @storybook/addon-actions/dist/modern/preset/addArgs

### ISSUE THREAD

**Issue by clayrisser** [storybookjs/react-native#476]
**Describe the bug**
I get the following error when running storybook native in expo.

```
Android Bundling failed 40134ms
Unable to resolve "@storybook/addon-actions/dist/modern/preset/addArgs" from ".storybook/storybook.requires.js"
```

**Expected behavior**
It should work with no errors.

**Screenshots**
![2023-05-20-034757_screenshot](https://github.com/storybookjs/react-native/assets/6234038/d4adf221-6a9d-4103-8ac8-d67787d92f84)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Environment Info:

  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 3.3.1 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Firefox: 113.0

Here's the _storybook.requires.js_ file that was generated.

```js
/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
  addArgsEnhancer,
  clearDecorators,
} from "@storybook/react-native";

global.STORIES = [
  {
    titlePrefix: "",
    directory: "./stories",
    files: "**/*.stories.@(js|jsx|ts|tsx|mdx)",
    importPathMatcher:
      "^\\.[\\\\/](?:stories(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)\\/|\\/|$)(?!\\.)(?=.)[^/]*?\\.stories\\.(js|jsx|ts|tsx|mdx))$",
  },
  {
    titlePrefix: "",
    directory: "../../app",
    files: "**/*.stories.@(js|jsx|ts|tsx|mdx)",
    importPathMatcher:
      "^(?:\\.\\.\\/\\.\\.\\/app(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)\\/|\\/|$)(?!\\.)(?=.)[^/]*?\\.stories\\.(js|jsx|ts|tsx|mdx))$",
  },
  {
    titlePrefix: "",
    directory: "../../ui/src",
    files: "**/*.stories.@(js|jsx|ts|tsx|mdx)",
    importPathMatcher:
      "^(?:\\.\\.\\/\\.\\.\\/ui\\/src(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)\\/|\\/|$)(?!\\.)(?=.)[^/]*?\\.stories\\.(js|jsx|ts|tsx|mdx))$",
  },
];

import "@storybook/addon-ondevice-actions/register";
import "@storybook/addon-ondevice-backgrounds/register";
import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-notes/register";

import { argsEnhancers } from "@storybook/addon-actions/dist/modern/preset/addArgs";

import { decorators, parameters } from "./preview";

if (decorators) {
  if (__DEV__) {
    // stops the warning from showing on every HMR
    require("react-native").LogBox.ignoreLogs([
      "`clearDecorators` is deprecated and will be removed in Storybook 7.0",
    ]);
  }
  // workaround for global decorators getting infinitely applied on HMR, see https://github.com/storybookjs/react-native/issues/185
  clearDecorators();
  decorators.forEach((decorator) => addDecorator(decorator));
}

if (parameters) {
  addParameters(parameters);
}

try {
  argsEnhancers.forEach((enhancer) => addArgsEnhancer(enhancer));
} catch {}

const getStories = () => {
  return {
    "./stories/welcome.stories.tsx": require("../stories/welcome.stories.tsx"),
    "./../../app/screens/home/home.stories.tsx": require("../../../app/screens/home/home.stories.tsx"),
    "./../../app/screens/user/user.stories.tsx": require("../../../app/screens/user/user.stories.tsx"),
  };
};

configure(getStories, module, false);
```

**Comment by clayrisser** [comment]
For now I'm simply running the following sed expression to make it work.

```sh
sed 's|import { argsEnhancers } from "@storybook/addon-actions/dist/modern/preset/addArgs";|const argsEnhancers=[]|g' .storybook/storybook.requires.js
```

**Comment by dannyhw** [comment]
@clayrisser did you install `@storybook/addon-actions` it seems like its not found.

**Comment by cflorez10** [comment]
I have the same issue @dannyhw, I've installed `@storybook/addon-actions": "^7.0.15`... the issue happen when you run the command `sb-rn-get-stories`, this automatically add this line:

`import { argsEnhancers } from "@storybook/addon-actions/dist/modern/preset/addArgs";`

but if you take a look to the node_modules folder for addon-actions you will note that it doesnt have a modern folder:

![image](https://github.com/storybookjs/react-native/assets/90944198/e8728447-7c4d-4ced-94e9-9e4e7a67b2bc)

its possible a version issue with `@storybook/addon-actions`?

**Comment by cflorez10** [comment]
@dannyhw it seems the folder was removed in the 7.x.x version of `@storybook/addon-actions`, I moved to `"@storybook/addon-actions": "^6.5.14"` and now is working as expected.

**Comment by dannyhw** [comment]
yeah you need to be running v6.5+, in general follow semver and don't use v6 with v7. Use v6 versions across the board, breaking changes always happen between major versions.

**Comment by cflorez10** [comment]
Im having a similar issue with `@storybook/addon-react-native-web`, according to the [docs](https://github.com/storybookjs/addon-react-native-web#configuring-popular-libraries), I just need to add the addon but I'm getting the following issue:

![image](https://github.com/storybookjs/react-native/assets/90944198/4e1821cb-8a93-4ca8-ba7e-f078fd813e84)

the `sb-rn-get-stories` add the react native web addon into the `storybook.requires.js` file:

![image](https://github.com/storybookjs/react-native/assets/90944198/0c55fac2-a421-40bd-a0d9-db3871b622b4)

but, it seems the register file is not found in the node_modules folder:

![image](https://github.com/storybookjs/react-native/assets/90944198/ff832c0f-abd6-47c1-86ca-046214dc067e)


Im using the `@storybook/addon-react-native-web: "^0.0.20" version. 

@dannyhw Any idea what i'm doing wrong?

**Comment by cflorez10** [comment]
I also note an issue when you use the object notation for configuring an addon:

![image](https://github.com/storybookjs/react-native/assets/90944198/9f01cb03-febb-4b7d-b527-312b98fe5abf)

The `sb-rn-get-stories` is adding `[object, object]/register` in `storybook.requires.js`:

![image](https://github.com/storybookjs/react-native/assets/90944198/880f69ad-d32c-44d1-a85b-9d1bb7d83e54)

**Comment by dannyhw** [comment]
@cflorez10 thats a different issue. Thats not how the addon is used. addon-react-native-web runs on web storybook not on react native ondevice storybook

I.E you need to add reactjs storybook to your project and add it to a separate config for that. The config is not directly compatible since react native addons are different currently and react native runs using your code and web storybook runs in webpack or vite.

**Comment by cflorez10** [comment]
@dannyhw So, the idea is to create different configuration files, one for mobile and another for web? do you have an example project/repository where both have been implement? I would like to take a look. Or add more details about how to implement both in the same project... I want to use RN Mobile for developing and RN Web for stakeholders/design team reviewing

**Comment by dannyhw** [comment]
@cflorez10 the example projects have it setup

https://github.com/dannyhw/react-native-storybook-starter

https://github.com/dannyhw/expo-storybook-starter

**Comment by cflorez10** [comment]
Thanks a ton for pointing me to the right direction, one more question, its off topic... Im getting this issue, webpack never finishes building:

![image](https://github.com/storybookjs/react-native/assets/90944198/d7dfdfff-538b-4b3f-b948-41a8f3c49647)

I'm just loading one story:

![image](https://github.com/storybookjs/react-native/assets/90944198/64932518-b444-439e-bb59-fd722ba591b4)

How can I debug it?

This is my current configuration:

![image](https://github.com/storybookjs/react-native/assets/90944198/d22306b8-5aab-455d-8e68-e7f4e47cf380)

**Comment by cflorez10** [comment]
@dannyhw I tried to no load stories, and I'm getting the following issue:

![image](https://github.com/storybookjs/react-native/assets/90944198/66ca2ca4-d5df-4011-950a-ddb931dde3d8)

**Comment by dannyhw** [comment]
sorry for not responding earlier, were you able to get this resolved? sounds like you could be missing a dependency or configuration.

Do you have metro-react-native-babel-preset installed?

**Comment by dannyhw** [comment]
seems like the initial issue was solved, if you need help with addon-react-native-web you can raise the issue at http://github.com/storybookjs/addon-react-native-web
