### ISSUE TITLE
Hot reload doesn't work on iOS

### ISSUE THREAD

**Issue by CharlyAnd** [storybookjs/react-native#477]
**Is your feature request related to a problem? Please describe.**

I've noticed that hot reload doesn't seem to work on iOS, but it does on android. 

**Describe the solution you'd like**

To be able to hot reload on iOS

**Describe alternatives you've considered**

**Are you able to assist bring the feature to reality?**
no 

**Additional context**

**Comment by dannyhw** [comment]
@CharlyAnd can you provide more information about your setup, this shouldn't be the case.

What version are you using?

**Comment by CharlyAnd** [comment]
@dannyhw thanks for getting back to me. These are the versions. Let me know if you need any more info
![Screenshot 2023-05-25 at 14 19 53](https://github.com/storybookjs/react-native/assets/94613508/13b00a0e-1e31-465b-bb3f-9ea175f8ba9c)

**Comment by dannyhw** [comment]
@CharlyAnd what are you doing when the hot reload should be taking place?

One case that doesn't work is adding new files since it requires you to re-run the import generation script (or have the watcher running).

**Comment by CharlyAnd** [comment]
It doesn't seem to hot reload on save when working on an existing story, as it does on android

**Comment by dannyhw** [comment]
still having this problem?

**Comment by CharlyAnd** [comment]
@dannyhw yep still seeing this

**Comment by dannyhw** [comment]
@CharlyAnd Can you provide a reproduction of the problem?

**Comment by CharlyAnd** [comment]
Apologies, this does seems to work when storybook is run from the command line rather than xCode

**Comment by dannyhw** [comment]
Seems to be resolved, let me know if you want to reopen
