### ISSUE TITLE
Stories are not being grouped by title/filepath

### ISSUE THREAD

**Issue by CharlyAnd** [storybookjs/react-native#478]
**Is your feature request related to a problem? Please describe.**
Hi, I've noticed that stories do not get automatically grouped by filepath, as in the web version of storybook. See screenshots below.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you able to assist bring the feature to reality?**
no 

**Additional context**

![Screenshot 2023-05-25 at 13 28 21](https://github.com/storybookjs/react-native/assets/94613508/f6c92deb-5a0c-40d0-9299-703d9f59cd1e)
<img width="282" alt="Screenshot 2023-05-25 at 13 28 07" src="https://github.com/storybookjs/react-native/assets/94613508/f54a1217-bbe3-40d1-a440-978d8097ec3c">

**Comment by dannyhw** [comment]
closing since its a duplicate issue (#12)

This functionality isn't yet supported.

**Comment by dannyhw** [comment]
There is some stuff in progress but for now its not supported
