### ISSUE TITLE
What is the difference between this repo and the one at `https://github.com/storybookjs/storybook/tree/master/app/react-native`?

### ISSUE THREAD

**Issue by joshglenn** [storybookjs/react-native#48]
What is the difference between this repo and the one at `https://github.com/storybookjs/storybook/tree/master/app/react-native`?

**Comment by dannyhw** [comment]
The one at `https://github.com/storybookjs/storybook/tree/master/app/react-native` has been removed from the next branch which is the current active branch for storybookjs/storybook. 

The react native storybook was moved here and all new react native issues are being sent to this repo.

**Comment by dannyhw** [comment]
react native has been removed from the other repository and the link was changed there so I'll mark this as resolved
