### ISSUE TITLE
ADDONS_SUPPORT.md has links that point to 404 Not Found

### ISSUE THREAD

**Issue by Arron-Gill** [storybookjs/react-native#480]
**Describe the bug**
The addons.md file has a link that points to 404 not found

**To Reproduce**
1. Go to 'https://github.com/storybookjs/react-native/blob/next/ADDONS_SUPPORT.md'
![image](https://github.com/storybookjs/react-native/assets/87369513/95d6ecd6-6f72-4107-aaf8-3b812ca58e1a)
2. Click on 'Backgrounds' (takes you to https://github.com/storybookjs/react-native/blob/next/addons/backgrounds).
![image](https://github.com/storybookjs/react-native/assets/87369513/dbd08db5-02bf-4d3c-99ae-a073ef56d08e)

**Expected behavior**
Either link should not exist or link should work

**Screenshots**
Already in To Reproduce section

**Code snippets**
N/A

**System:**
N/A

**Additional context**
N/A

**Comment by dannyhw** [comment]
thanks for reporting, I will double check those links

**Comment by dannyhw** [comment]
I've removed this page since its old and comes from when the repo was copied over from the main repository. The ondevice addons are listen on the main readme.
