### ISSUE TITLE
Configuring the react-native-reanimated plugin in babel.js

### ISSUE THREAD

**Issue by vlack-coder** [storybookjs/react-native#488]
**Describe the bug**
I tried to configure the react-native-reanimated plugin in the babel.js file of the storybook directory but I got this error

`error: ../node_modules/react-native-reanimated/src/reanimated2/Colors.ts: /Users/user/node_modules/react-native-reanimated/src/reanimated2/Colors.ts: ENOENT: no such file or directory, open '/Users/user/node_modules/react-native-reanimated/src/reanimated2/Colors.ts' 
`

**I added the plugin like this**
`   [
      'react-native-reanimated/plugin',
      {
        relativeSourceLocation: true,
      },
    ],
`

**I configured my alias like this when the plugin above did not resolve the reanimated module**
  `  alias: {
          '@': '../src',
          'react-native-reanimated': path.resolve(
            __dirname,
            '..',
            'node_modules/react-native-reanimated',
          ),
        },`
        
Please.. Any  Idea?

 BUNDLE  .storybook/index.js 

**To Reproduce**
1. Go to 'Try to import any reanimated component in component.stories'

**Expected behavior**
To resolve the reanimated module correctly

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by vlack-coder** [comment]
Please @dannyhw any Idea on how to solve this.
Thank you, I appreciate

**Comment by dannyhw** [comment]
whats the purpose of adding the relativeSourceLocation: true?

**Comment by dannyhw** [comment]
can you share a reproduction?

**Comment by dannyhw** [comment]
closing due to no response, let me know if you want to reopen
