### ISSUE TITLE
Export `DecoratorFunction`

### ISSUE THREAD

**Issue by hayata-suenaga** [storybookjs/react-native#506]
**Is your feature request related to a problem? Please describe.**
I want to use `DecoratorFunction` type. However, this type is not exported from the library.

**Describe the solution you'd like**
`import { DecoratorFunction } from @storybook/react-native`

**Describe alternatives you've considered**

```ts
type Temp = Meta["decorators"];
type ExtractDecoratorFunction<T> = T extends (infer R)[] ? R : never;
type DecoratorFunction = ExtractDecoratorFunction<Temp>;
```

or

```ts
import {DecoratorFunction} from "@storybook/csf/dist/story"
```

**Are you able to assist bring the feature to reality?**
maybe?

**Additional context**
N/A

**Comment by dannyhw** [comment]
this should be possible, in the meantime heres a workaround you can use for now

```
import { addDecorator } from '@storybook/react-native';

type Decorator = Parameters<typeof addDecorator>[0];
```

You may also be able to use the decorator type from `@storybook/react` if you have it

**Comment by dannyhw** [comment]
types are now reused from storybook react
