### ISSUE TITLE
Single story hoisting not working

### ISSUE THREAD

**Issue by MadeinFrance** [storybookjs/react-native#515]
**Describe the bug**
I'm trying to have a single story without siblings but it always renders 1 child.

**Expected behavior**
See docs: https://storybook.js.org/docs/6.5/react/writing-stories/naming-components-and-hierarchy#single-story-hoisting

**Screenshots**
<img width="231" alt="image" src="https://github.com/storybookjs/react-native/assets/1864359/ac025a37-c4b4-4141-ab78-1c7ead5c0f64">

**Code snippets**
```js
// Button.tsx
import React from 'react';
import {Text, View} from 'react-native';

export const Button: React.FC = () => (
  <View testID="view:Button">
    <Text>Button</Text>
  </View>
);

// Button.stories.tsx
import {Button as ButtonComponent} from './Button';

export default {
  component: ButtonComponent,
};

// This is the only named export in the file, and it matches the component name
export const Button = {};
```

**System:**
Storybook Environment Info:

  System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - ~/.nvm/versions/node/v20.5.0/bin/node
    Yarn: 3.6.3 - /opt/homebrew/bin/yarn <----- active
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.0/bin/npm
    pnpm: 7.17.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6

**Expected**
<img width="148" alt="image" src="https://github.com/storybookjs/react-native/assets/1864359/97e0e176-2b7c-49c7-bcac-608b41c51bed">

**Comment by dannyhw** [comment]
@MadeinFrance  Thats not the case, what you are seeing is the Component->Stories. It never shows with just the individual story, there is always the meta default export with its title and then stories which are children to that. There is then another layer above that which is the folders/categories you can add.

You should probably not have your story have the same name as the title or you will see duplicated names like this. 

Usually you would have something like Base.

**Comment by miikemccabe** [comment]
I'm sorry but @MadeinFrance is absolutely right. The docs he has linked to clearly state you can remove the redundant extra layer by having only one named export and having that export have the same name as the title of the default. I am also having this exact same issue.

**Comment by dannyhw** [comment]
I see i guess I didn't understand, never heard of that feature. That won't work currently in react native. This would be a new feature for the react native side of things.
