### ISSUE TITLE
Absolute Path not working

### ISSUE THREAD

**Issue by mattg95** [storybookjs/react-native#516]
**Describe the bug**
I am unable to import from an absolute path in Storybook React Native. Here is my file structure:
```
/app
  - Login.tsx
/storybook
  - main.js
  - storybook.requires.js
  - renderWithProviders.tsx // custom functions to render stories with redux/navigation context providers
  - preview.js
  - Storybook.tsx
```
If I try to import a function from `renderWithProviders` in `Login.tsx` like so: `import { renderWithProviders } from '.storybook/renderWithProviders';` I get the error :`None of these files exist: ../.storybook/renderWithProviders`. If I change it to use a relative import path, it works fine. 

**Things I've tried**
Almost every stackoverflow/github issue raised on this suggests adding this to the main.js: 
```
 webpackFinal: async (config) => {
      config.resolve.modules = [
        ...(config.resolve.modules || []),
        path.resolve(__dirname, "../"),
      ];
  
      return config;
    },
```
However, webpack is for browsers, not RN. I tried adding it anyway and it didn't fix the issue.

**Code snippets**
package.json:
```
	"@storybook/core-common": "6.5.16",
		"@storybook/react-native": "6.5.6",
```

**System:**
```Storybook Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.homebrew/bin/yarn <----- active
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Edge: 117.0.2045.55
    Safari: 15.5
  npmPackages:
    @storybook/core-common: 6.5.16 => 6.5.16 
    @storybook/react-native: 6.5.6 => 6.5.6 
    storybook-addon-state: 1.0.3 => 1.0.3 
```

**Additional context**

**Comment by dannyhw** [comment]
@mattg95  You need to configure babel to allow for absolute paths the same do for other react native apps, there is no specific storybook config required. I suggest looking into babel-plugin-module-resolver.

**Comment by mattg95** [comment]
@dannyhw Many thanks, I will look into that
