### ISSUE TITLE
Unable to resolve module @storybook/addon-links/register

### ISSUE THREAD

**Issue by Gregoirevda** [storybookjs/react-native#518]
Using @storybook/addon-links@7.4.6 and 
@storybook/react-native@next (7.alpha)

the `sb-rn-get-stories` script generates imports to `@storybook/addon-links/register` which doesn't exist anymore.

Is this package compatible with 7.X @storybook/addons ?

**Comment by dannyhw** [comment]
@Gregoirevda react native storybook is on 6.5.6 so its not compatible with v7 storybook since thats a major version difference. You should stick to version ^6.5 for everything for now.
