### ISSUE TITLE
Issue running react-native-server on the example app

### ISSUE THREAD

**Issue by mljlynch** [storybookjs/react-native#520]
**Describe the bug**

**To Reproduce**
- git clone https://github.com/storybookjs/react-native.git react-native-storybook\ncd react-native-storybook
- yarn build
- npm install --global yarn
- yarn
- yarn build
- cd examples/expo-example
- yarn ios
- yarn web

infinite spinner:

<img width="800" alt="image" src="https://github.com/storybookjs/react-native/assets/13424219/35f2899c-576d-4dfb-8185-6615329a459d">

**Expected behavior**
It works

**Comment by dannyhw** [comment]
If you want the server to work you need to go into the example app and enable websockets, not sure if they are on by default in the example app.

**Comment by mljlynch** [comment]
`enableWebsockets` is set to true by default in `getStorybookUI` - however `yarn web` fails with:

`Unable to resolve "telejson" from "../../node_modules/@storybook/channel-websocket/dist/esm/index.js"`

I can get the server started by running:

```npx react-native-storybook-server```

But this leads to the infinite spinner above.

**Comment by dannyhw** [comment]
@mljlynch make sure you are on the right branch, you need to be on the `next` branch. Otherwise you'll be running old code.

**Comment by mljlynch** [comment]
This is on a fresh clone so I am on the next branch by default.

**Comment by dannyhw** [comment]
after you open the mobile app and the server ui can you try refreshing the mobile ui for example by hitting `r`, usually that gets it working

**Comment by dannyhw** [comment]
and yeah if I remember correctly yarn web will fail currently just because metro web isn't working correctly with some esm stuff. Might need to add the webpack version back for a bit.

 However you should be able to try stuff with android/ios

**Comment by mljlynch** [comment]
yes confirmed working for iOS.

**Comment by mljlynch** [comment]
woah ok that works. let's goooooo!

**Comment by mljlynch** [comment]
Ok It works,BUT it won't switch through the components it just shows the default body:

<img width="1728" alt="image" src="https://github.com/storybookjs/react-native/assets/13424219/96238dbb-4fed-422d-a872-ac99d30bf713">

**Comment by dannyhw** [comment]
@mljlynch the server ui doesn't have any preview its just for controlling the mobile device UI. There is another project for react native web storybook http://github.com/storybookjs/addon-react-native-web that runs on reactjs storybook. If you're looking to see components on the web you should go there.
