### ISSUE TITLE
use with ``react-native-linear-gradient`` in storybook project

### ISSUE THREAD

**Issue by YOEL311** [storybookjs/react-native#526]
I try to display components that contain a view with ``react-native-linear-gradient``
but i got error

````
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports
````

**To Reproduce**
1. Install React native CLI app with template (not expo app)
``npx react-native init MyApp --template react-native-template-storybook``
npm add react-native-linear-gradient
add a simple LinearGradient view in the component

````
 <LinearGradient
        style={{
          borderRadius: 30,
          justifyContent: 'center',
          alignItems: 'center',
          flexDirection: 'row',
        }}
        start={{ x: 0.47, y: -0.2 }}
        end={{ x: 0.5, y: 0.8 }}
        colors={['red', 'green']}>
        <View style={{ width: 200, height: 200, backgroundColor: 'red' }} />
      </LinearGradient>
````

**Comment by dannyhw** [comment]
@YOEL311 this type of error is generally due to incorrectly using components by not exporting or importing them correctly. There should be no issue using linear gradient. Maybe you could share more code?

**Comment by YOEL311** [comment]
@dannyhw 
I have to explain
In mobile app it's working as well 
But in web with ''yarn storyboard'' I got the above error

**Comment by dannyhw** [comment]
@YOEL311 there is another repo for that web addon http://www.github.com/storybookjs/addon-react-native-web so you can make those issues there.

However you can resolve this by using the modulesToAlias option and aliasing the gradient package to react-native-web-linear-gradient 

https://github.com/react-native-web-community/react-native-web-linear-gradient

see the option here

https://github.com/storybookjs/addon-react-native-web#aliasing-react-native-web-libraries

```
module.exports = {
  addons: [
    /*existing addons,*/
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToAlias: {
          'react-native-linear-gradient': 'react-native-web-linear-gradient',
        },
      },
    },
  ],
}; 
```

**Comment by YOEL311** [comment]
Thanks!
