### ISSUE TITLE
[Regression] Stories configuration object not working with auto titles

### ISSUE THREAD

**Issue by stevoland** [storybookjs/react-native#527]
**Describe the bug**
Stories not loaded when meta has no title property (auto titles).

Works in 6.5.4

**To Reproduce**
Checkout https://github.com/stevoland/react-native/commit/b61b898ed4a7d0e8517ad8625fc5e394580d8dd9
Run the example app

Observe no `Background Example/Background Csf` stories and log:
```
 INFO  Unexpected default export without title in './BackgroundExample/BackgroundCsf.stories.tsx': {"decorators":[null],"parameters":{"backgrounds":{"default":"warm","values":[{"name":"warm","value":"hotpink"},{"name":"cool","value":"deepskyblue"},{"name":"white","value":"white"},{"name":"black","value":"black"}]}}}
```

**Expected behavior**
Stories should appear in storybook under `Components/Background Example/Background Csf`

**System:**
Storybook Environment Info:

  System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Pro
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 3.6.1 - ~/.nvm/versions/node/v18.18.0/bin/yarn <----- active
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1

**Comment by dannyhw** [comment]
Thanks for the report I will look into it soon

**Comment by dannyhw** [comment]
I believe this is resolved in v7, let me know if we need to reopen
