### ISSUE TITLE
HMR issues

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#558]
**Describe the bug**
There are sometimes issues where HMR doesn't correctly trigger in v7 when editing stories, in these cases a reload is required to see the changes.

This seems to be an issue mainly for stories files. Still investigating the root cause.

**Comment by robin-ambachtsheer** [comment]
This seems related so just leaving as a comment here. After an HMR update on the iOS simulator, when trying to use the story search the app crashes. It works fine when doing a hard refresh.

I also found that the HMR does seem to trigger a refresh, but it just reloads with the old story code (updates in components do seem to come through). Also only on iOS for me, on Android it does seem to update the stories correctly.

Might be worth noting I'm using Expo.

**Comment by dannyhw** [comment]
@robin-ambachtsheer hey, yeah this has been a tough one to debug but hoping to have a fix sometime soon.

**Comment by dannyhw** [comment]
@robin-ambachtsheer please try 7.6.16, this should be fixed now :)

**Comment by robin-ambachtsheer** [comment]
Seems to be working perfectly now, thanks!
