### ISSUE TITLE
@storybook/react-native webpack bundler support

### ISSUE THREAD

**Issue by mlakmal** [storybookjs/react-native#569]
We are using webpack based bundler (@callstack/repack) in our react-native application (instead of default metro bundler).

can this module be supported with webpack based bundlers?

**Comment by dannyhw** [comment]
@mlakmal  yeah that should work, if you run into any issues then if you can share a reproduction I'm happy to take a look

**Comment by mlakmal** [comment]
closing this as it worked after some path mapping and @storybook/addon-webpack5-compiler-babe addon
