### ISSUE TITLE
Unable to run expo-example: Unable to resolve "./dist/index" from "../../packages/ondevice-controls/register.js"

### ISSUE THREAD

**Issue by Gome510** [storybookjs/react-native#580]
**Describe the bug**
When I try to run the expo-example storybook app on ios simulator, I get an error `Unable to resolve "./dist/index" from "../../packages/ondevice-controls/register.js"`

**To Reproduce**
1. git clone https://github.com/storybookjs/react-native.git
2. cd react-native
3. yarn
4. yarn workspace expo-example storybook
5. Press "i" (I was running it on ios)

**Expected behavior**
I expected the see a storybook react native app.

**Screenshots**
<img width="439" alt="image" src="https://github.com/storybookjs/react-native/assets/26130543/121f560a-2847-4a36-a361-1f3654e29f3d">

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - /usr/local/bin/node
    Yarn: 4.1.0 - /usr/local/bin/yarn <----- active
    npm: 10.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.4.1

**Comment by dannyhw** [comment]
Have you ran yarn build in the workspace root?

**Comment by Gome510** [comment]
> Have you ran yarn build in the workspace root?

That worked, thank you!
