### ISSUE TITLE
Warning: Support for defaultProps will be removed

### ISSUE THREAD

**Issue by martinezguillaume** [storybookjs/react-native#582]
**Describe the bug**
[This line](https://github.com/storybookjs/react-native/blob/5601d15d23c7a6729a013eeb7b4ff94b661b101b/packages/ondevice-controls/src/types/Text.tsx#L38) in the package `@storybook/addon-ondevice-controls` raises a warning
```
Warning: TextType: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```
**To Reproduce**
1. `npx storybook@latest init` in an existing project
2. Run your storybook
3. Go to "ADDONS" tab

**Expected behavior**
No warning at all 😎

**Screenshots**
![Simulator Screenshot - iPhone 15 - 2024-06-18 at 21 50 20](https://github.com/storybookjs/react-native/assets/17292331/caefd494-7d97-4d11-a856-9f5a6d7dc256)

**Comment by dannyhw** [comment]
ah I was hoping I could get v8 out before this became an issue haha, I can get out a fix soon for this thanks for flagging.

**Comment by ericwilsontruerx** [comment]
Is there a fix for this issue yet? I'm currently using version "^7.6.20"

**Comment by dannyhw** [comment]
@ericwilsontruerx i believe it should be fixed in v8, if not I can push a fix

**Comment by bbaoNg97** [comment]
Hi, is this fixed in v8?

**Comment by dannyhw** [comment]
yes its fixed in v8
