### ISSUE TITLE
RangeError: Maximum call stack size exceeded -  Error after upgrading from Storybook 7-8

### ISSUE THREAD

**Issue by kotAPI** [storybookjs/react-native#586]
**Describe the bug**
I had just upgraded my storybook version to 8 from 7-alpha. A lot of stories have broken due to the upgrade, but I haven't been able to fix this one.

Detailed Error stack
```
RangeError: Maximum call stack size exceeded
    at http://localhost:6006/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-548047.iframe.bundle.js:126:61
    at Array.map (<anonymous>)
    at prettyPrint (http://localhost:6006/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-548047.iframe.bundle.js:126:48)
    at http://localhost:6006/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-548047.iframe.bundle.js:151:25
    at Array.map (<anonymous>)
    at prettyPrint (http://localhost:6006/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-548047.iframe.bundle.js:146:52)
    at http://localhost:6006/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-548047.iframe.bundle.js:151:25
    at Array.map (<anonymous>)
    at prettyPrint (http://localhost:6006/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-548047.iframe.bundle.js:146:52)
    at http://localhost:6006/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-548047.iframe.bundle.js:151:25
```

**Screenshots**
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/14a0b09d-aa86-4537-92ec-4a213ddd421d">

any ideas on why this might happen? This story worked perfectly fine and none of the code has been changed. When the component is used in a regular react app, it works completely fine. It only remains broken on Storybook 8

**Comment by dannyhw** [comment]
@kotAPI storybook 8 is not yet supported for react native there is only an alpha version available. Dont mix v7 with v8 since they are incompatible.

The web addon should work though.

**Comment by kotAPI** [comment]
> @kotAPI storybook 8 is not yet supported for react native there is only an alpha version available. Dont mix v7 with v8 since they are incompatible.
> 
> The web addon should work though.

@dannyhw just realised that,sorry about that. thanks!
