### ISSUE TITLE
TypeError: require.context is not a function

### ISSUE THREAD

**Issue by eduardo-santos-tribia** [storybookjs/react-native#590]
**Describe the bug**
I'm getting an error when running my Jest tests. The error happens on `storybook.requires.ts` file (line 20) when the `require.context` function is called.

**To Reproduce**
1. Install @storybook/react-native v7 into a react-native App with Jest.
2. Run the tests with Jest.
3. See error

**Expected behavior**
No errors related to Storybook when running tests.

**Screenshots**
![image](https://github.com/user-attachments/assets/683fa002-5a1c-409d-930b-11b48af309b2)

**Code snippets**
```
const normalizedStories = [
  {
    titlePrefix: "",
    directory: "./src",
    files: "**/*.stories.tsx",
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.tsx)$/,
    // @ts-ignore
    req: require.context(
      "../src",
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.tsx)$/
    ),
  },
];
```

**System:**
@storybook/cli@8.3.0-alpha.5

**Additional context**
* My current react-native version is: 0.74.2
* My current storybook version is: 7.6.20

**Comment by dannyhw** [comment]
This seems like a jest configuration issue because these tests are working in the examples with the default expo jest setup

**Comment by dannyhw** [comment]
Though really you shouldn't need to load this code in tests. You should use compose stories on individual stories if you want to test stroybook stories

**Comment by eduardo-santos-tribia** [comment]
You're right @dannyhw, I was importing the `view` from `'./storybook.requires'` to get the `view.getStorybookUI` even when running my tests. 

To fix this I'm conditionally importing the view:
```
const getView = () => {
    if (process.env.NODE_ENV !== 'test') {
      try {
        const storybookRequires = require('./storybook.requires')
  
        return storybookRequires.view
      } catch (err) {
        console.error('Failed to load storybook.requires', err)
      }
    }
  
    return undefined
}
```

Another way to fix this is using the `babel-plugin-require-context-hook` library to mock the `require.context` during tests.
