### ISSUE TITLE
Add-on notes should support dark mode

### ISSUE THREAD

**Issue by trajano** [storybookjs/react-native#600]
**Is your feature request related to a problem? Please describe.**
On dark mode the text for the nodes is not readable because it's black on a dark baground

**Describe the solution you'd like**
Depending on mode switch just choose between black or white.  

**Describe alternatives you've considered**

**Are you able to assist bring the feature to reality?**
not sure yet

**Additional context**

**Comment by dannyhw** [comment]
this is solved by #602, thanks again for the help 🙏
