### ISSUE TITLE
Add responsive storybook ui with persistent sidebars, controls on larger devices

### ISSUE THREAD

**Issue by jvliwanag** [storybookjs/react-native#609]
**Is your feature request related to a problem? Please describe.**
While the current storybook UI fits well with mobile phones on portrait mode, devices with larger screens especially when on landscape mode can lend itself to having a persistent side bar, and even add-ons on some cases.

**Describe the solution you'd like**

Make the RN storybook UI responsive such that at a certain size, display the sidebar persistently, and possibly the addons at the bottom, similar to storybook web.

**Comment by dannyhw** [comment]
@jvliwanag this is already implemented in v8 beta

**Comment by dannyhw** [comment]
These are all the ondevice ui from react native storybook in v8
![image](https://github.com/user-attachments/assets/16bc4538-69c8-45bc-b2b4-07332fb13aed)

**Comment by jvliwanag** [comment]
Just migrated to v8 -- wow! Amazing!
