### ISSUE TITLE
Action argtypes cause "Property 'args' is missing" in v8.3

### ISSUE THREAD

**Issue by leemhenson** [storybookjs/react-native#618]
**Describe the bug**
If you use an `action` in `argtypes` for a required callback property you are forced to populate `args`. I don't encounter this under v7.

**To Reproduce**
If you make the following change in the `examples/expo-example/components/ActionExample/Actions.tsx` file in the 8.3 release:

![Image](https://github.com/user-attachments/assets/d19a9928-ee76-4a31-afae-86256ee75b87)

Then typescript begins complaining about `args` not being provided in the `Story` definitions:

![Image](https://github.com/user-attachments/assets/911efff3-0a00-4daa-ac3c-eedaa382e20a)

**Expected behavior**
It would be great if the `action` argtype could hint to typescript that the developer doesn't need to provide that prop.

**Screenshots**
see above

**Code snippets**
see above

**System:**
`@storybook/react-native@8.3.6`

**Additional context**
n/a

**Comment by dannyhw** [comment]
this is a change in functionality from v8 where now actions must be explicit it comes from upstream and is not specific to react native storybook.

**Comment by leemhenson** [comment]
ah ok so i found this in the main docs: 

https://storybook.js.org/docs/essentials/actions#action

assume this is what I need to do now. thanks 👍
