### ISSUE TITLE
New expo projects yields "you need to install flashlist" error due to @gorhom/bottom-sheet 5

### ISSUE THREAD

**Issue by jvliwanag** [storybookjs/react-native#619]
**Describe the bug**
A fresh `pnpm create expo`  project followed by storybook rn installation guide yields to an error while running the android build stating:

    You need to install FlashList first, `yarn install @shopify/flash-list`

This message is coming from the `@gorhom/bottom-sheet` which just dropped a new major version (v5) and integrates new FlashList features.

Also tried these steps with yarn yielding identical issues.

**To Reproduce**
1. pnpm create expo
2. pnpx storybook@latest init
3. follow rest of storybook installation

**Workaround**

Do either:

A - Downgrade `@gorhom/bottom-sheet` to `4.6.4`.
B - Install a new version of `@shopify/flash-list`. Note that the version that `expo add @shopify/flat-list` doesn't seem to work even though it's what's referenced on the latest bottom-sheet examples. Upgrading this instead to the latest flash-list `1.7.1` works.

**Comment by dannyhw** [comment]
This seems like an issue for `@gorhom/bottom-sheet` since flashlist is supposed to be an optional dependency for that library

**Comment by dannyhw** [comment]
However for now please stay on v4 of @gorhom/bottom-sheet since I haven't had time to test v5 yet given it just came out

**Comment by dannyhw** [comment]
I have confirmed this is an issue but its because the @gorhom/bottom-sheet uses barrel file exports so every file is included + ran everytime even if its not used. 

Also just pushed 8.3.7-alpha.0 to fix the addons panel not opening with the new bottomsheet version

You can use v5 if you install flashlist or patch bottom sheet to remove the error it throws

**Comment by dannyhw** [comment]
This should now be solved with bottom sheet 5.0.2 and sb 8.3.7 will be out with the other fix shortly
