### ISSUE TITLE
incorrect typing for withStorybook

### ISSUE THREAD

**Issue by trajano** [storybookjs/react-native#630]
Thanks for adding the typing but you did it incorrectly at the end

https://github.com/storybookjs/react-native/blob/next/packages/react-native/metro/withStorybook.d.ts

you had 

```
export function withStorybook(config: InputConfigT, options?: WithStorybookOptions): InputConfigT;
```

when it should've been

```
declare function withStorybook(config: InputConfigT, options?: WithStorybookOptions): InputConfigT;

export = withStorybook
```

**Comment by dannyhw** [comment]
ah I copied it from what you sent before but I never manually wrote .d.ts before so no idea what im doing haha

will try it soon, if you want/have time to make a pr please do 🙏

**Comment by trajano** [comment]
The better way IMO is for the code to be in typescript and let it emit the JS and the .D.TS be emitted.
