### ISSUE TITLE
The story titles are not displaying in the React Native Android app

### ISSUE THREAD

**Issue by Anahita-Fakhravar** [storybookjs/react-native#635]
**Describe the bug**

In the React Native Android app, titles aren’t showing, and component names in the bottom bar are white with a transparent background. This works fine on iOS. I tried changing colors in the theme and applying my custom theme, but it didn’t work at all on both Android and iOS.

**To Reproduce**
1. Try to run storybook on android emulator or real device.
2. You will see that it does not show the stories properly.

**Expected behavior**
The Storybook titles, text, and bottom bar colors should match the iOS version and display correctly.

**Screenshots**
Please see the screenshots: 
![Image](https://github.com/user-attachments/assets/96ff0ceb-f7e2-44d3-9020-4ba72c242272)
![Image](https://github.com/user-attachments/assets/0a866d43-b6cf-4592-a726-60f742858b12)
![Image](https://github.com/user-attachments/assets/9914fed2-863c-4c11-bc0f-19da6d64a17d)

**System:**

  System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.1 - /usr/local/bin/node
    Yarn: 4.1.1 - /usr/local/bin/yarn <----- active
    npm: 9.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 17.3.1

**Additional context**

Storybook version: 
   "@storybook/addon-docs": "^8.1.4",
    "@storybook/addon-essentials": "^8.1.4",
    "@storybook/addon-interactions": "^8.1.4",
    "@storybook/addon-links": "^8.1.4",
    "@storybook/addon-ondevice-actions": "^8.0.0-alpha.4",
    "@storybook/addon-ondevice-backgrounds": "^8.0.0-alpha.4",
    "@storybook/addon-ondevice-controls": "^8.0.0-alpha.4",
    "@storybook/addon-ondevice-notes": "^8.0.0-alpha.4",
    "@storybook/blocks": "^8.1.4",
    "@storybook/manager-api": "^8.1.4",
    "@storybook/react": "^8.1.4",
    "@storybook/react-native": "^8.0.0-alpha.4",
    "@storybook/react-vite": "^8.1.4",
    "@storybook/test": "^8.1.4",
    "@storybook/theming": "^8.1.4",
    "storybook": "^8.1.4",
React-Native version:
"react-native": "=0.75.4"

I tried to upgrade storybook to the last and next versions but I got the following error: 
![Image](https://github.com/user-attachments/assets/7bb53e15-b76d-4f1b-a74d-f9ff941a0e47)

**Comment by dannyhw** [comment]
In the latest version you need to add a metro function in metro config called withStorybook that will solve your error

**Comment by Anahita-Fakhravar** [comment]
@dannyhw Sure thing! Do you have any insight into the error I’m encountering when trying to update Storybook? I followed the instructions in the documentation, but I’m still getting an error. I’ve attached a screenshot of the error (it’s the last one).

**Comment by Anahita-Fakhravar** [comment]
> In the latest version you need to add a metro function in metro config called withStorybook that will solve your error

Thank you. Will try it.

**Comment by Anahita-Fakhravar** [comment]
@dannyhw I upgraded to the latest version, and now everything is working perfectly. Thank you so much for your quick response and help. You really saved the day!

**Comment by dannyhw** [comment]
Happy to help :)

The reason for the error is that the metro option for package exports is required to load most storybook packages since they use the exports field to define entry points to the package
