### ISSUE TITLE
[6.0] support for declarative config like web storybook

### ISSUE THREAD

**Issue by amalfra** [storybookjs/react-native#65]
**Is your feature request related to a problem? Please describe.**

Looks like web version supports declarative config but react native one still is in old config. I was wondering whether there is any plan to support declarative config here too? It will be lot easy to share configs for people who use monorepos with web and mobile apps.

**Describe the solution you'd like**

```
module.exports = {
  stories: [`${packagesPath}/**/*.stories.js`],
  addons: [
    '@storybook/addon-actions/register',
  ],
};
```
this web version's config will work with native too.

**Describe alternatives you've considered**
https://storybook.js.org/docs/guides/guide-react-native/

**Are you able to assist bring the feature to reality?**
no

**Comment by dannyhw** [comment]
It would be good to get this done, however currently the focus is to fix some bugs and gets things stable. Once things are looking more stable then we will look into bringing the native storybook up to speed with the web.

**Comment by dannyhw** [comment]
in #182 a large part of this work is already completed for the [first 6.0 alpha milestone](https://github.com/storybookjs/react-native/milestone/1)
