### ISSUE TITLE
Getting Reanimated Warning on Latest StoryBook

### ISSUE THREAD

**Issue by satheshrgs-rksv** [storybookjs/react-native#658]
I'm currently on React Native - 0.76.3, and following are the story book versions

"@storybook/addon-actions": "^8.4.6",
  "@storybook/addon-controls": "^8.4.6",
  "@storybook/addon-ondevice-actions": "^8.4.2",
  "@storybook/addon-ondevice-controls": "^8.4.2",
  "@storybook/react-native": "^8.4.2",
  "storybook": "^8.4.6",

"@gorhom/bottom-sheet": "^5.0.6",
"react-native-reanimated": "^3.16.3",
"react-native-gesture-handler": "^2.21.2",
"react-native-svg": "^15.10.0",

Geting this following warning
If you don't want to see this message, you can disable the `strict` mode. Refer to:
https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.
 (NOBRIDGE) WARN  [Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use `get` method of a shared value while React is rendering a component.

**Comment by dannyhw** [comment]
@satheshrgs-rksv can you try 8.4.3-alpha.2?

**Comment by satheshrgs-rksv** [comment]
That error seems to be gone. Also getting this in the new Arch - ` (NOBRIDGE) ERROR  Error: Unsupported top level event type "topAnimationLoadedEvent" dispatched`

**Comment by satheshrgs-rksv** [comment]
Also unable to open controls and actions panel. Says cannot read property size of undefined. Should i need to update all versions to alpha ?

**Comment by satheshrgs-rksv** [comment]
warning is resolved in the latest story book versions
