### ISSUE TITLE
Console warnings from `Animated` usage of react-native-switch

### ISSUE THREAD

**Issue by vpicone** [storybookjs/react-native#69]
We don't need this package and can use the native switch element

**Comment by dannyhw** [comment]
I think that you're right about this, I have tried it with the native switch and it seems ok. I saw that you made a PR for this previously, if you want to re-open it I can take a look.

**Comment by vpicone** [comment]
@dannyhw re-opened. Thanks!

**Comment by dannyhw** [comment]
Resolved by #70
