### ISSUE TITLE
[Documentation]: Update RN documentation around AsyncStorage

### ISSUE THREAD

**Issue by jsjoeio** [storybookjs/react-native#7]
**Is your feature request related to a problem? Please describe.**
I'm new user of Storybook. We're using it on a React Native project. I've upgraded to the `@next` version to remove a warning about `AsyncStorage` per the recommendation here: https://github.com/storybookjs/storybook/issues/6078#issuecomment-549834805

Now, I see a new warning, which suggests I follow the `MIGRATION.md` guide, which takes me here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-native-async-storage

I see the solutions (thank you for those!), but now I'm wondering if I'm choosing the right one. 

> Use `null` to disable Async Storage completely.

Also wondering, "What are the benefits of using AsyncStorage within Storybook? It doesn't tell me, and I am struggling to find any documentation around this. 

The only relevant info I've found is the PR which adds in the new change:
- https://github.com/storybookjs/storybook/pull/7801

**Describe the solution you'd like**
I'd love to see some documentation around why, I as a developer, should use AsyncStorage with React Native Storybook.

**Describe alternatives you've considered**
I could just leave it as is and not say anything, but I figure I'm not the only one who may stumble into this scenario. And I like what Storybook provides for us, so I'd like to give back. 

**Are you able to assist bring the feature to reality?**
Yes, I'd be happy to update the docs or the `MIGRATION.md`. 

**Additional context**

**Comment by dannyhw** [comment]
@Gongreg  after adding asyncStorage I'm not seeing the app return to my last visited story on refresh, is there any other config required for this to work?

**Comment by Gongreg** [comment]
Hey @dannyhw, how did you enable it? What did you pass to asyncStorage?

**Comment by dannyhw** [comment]
```
import {AsyncStorage} from '@react-native-community/async-storage';
const StorybookUIRoot = getStorybookUI({
  asyncStorage: AsyncStorage,
});
```

However I also tried with `require('@react-native-community/async-storage').AsyncStorage`

**Comment by Gongreg** [comment]
Did you fully link it? https://github.com/react-native-community/async-storage There is information about linking it.

**Comment by dannyhw** [comment]
😅 I just changed `import {AsyncStorage}` to `import AsyncStorage` and it started working, now I feel silly haha. I immediately saw this from their example. Thanks for the quick response though!

**Comment by Gongreg** [comment]
glad that it works :)

**Comment by jsjoeio** [comment]
I did this but forgot to close the issue:

Closing via https://github.com/storybookjs/storybook/pull/9494
