### ISSUE TITLE
Error in React native storybook

### ISSUE THREAD

**Issue by amalfra** [storybookjs/react-native#71]
**Describe the bug**
When adding storybook view in react native app as main component using appRegistry, even without loading anything the app is crashing with below error. This is a monorepo setup using lerna.

```
[Tue Jul 21 2020 19:04:32.685]  ERROR    TypeError: undefined is not an object (evaluating '_this.props.updateCellsBatchingPeriod')

This error is located at:
    in VirtualizedList (at VirtualizedSectionList.js:216)
    in VirtualizedSectionList (at SectionList.js:246)
    in SectionList
    in emotion(SectionList) (at StoryListView/index.tsx:176)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in ForwardRef(SafeAreaView) (at StoryListView/index.tsx:167)
    in StoryListView (at OnDeviceUI/index.tsx:152)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper)
    in emotion(Styled) (at panel.tsx:16)
    in Panel (at OnDeviceUI/index.tsx:151)
    in RCTView (at View.js:34)
    in View (at absolute-positioned-keyboard-aware-view.tsx:91)
    in RCTView (at View.js:34)
    in View (at absolute-positioned-keyboard-aware-view.tsx:90)
    in AbsolutePositionedKeyboardAwareView (at OnDeviceUI/index.tsx:136)
    in RCTView (at View.js:34)
    in View (at KeyboardAvoidingView.js:204)
    in KeyboardAvoidingView (at OnDeviceUI/index.tsx:130)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in ForwardRef(SafeAreaView) (at OnDeviceUI/index.tsx:129)
    in OnDeviceUI (at preview/index.tsx:148)
    in ThemeProvider (at preview/index.tsx:147)
    in StorybookRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

**To Reproduce**
1. Setup storybook for react native in lastest react native and storybook v5.3.19.
2. Run the app after including storybook component as app entry point.

**Expected behavior**
Storybook is loaded

**Comment by amalfra** [comment]
It shows one story if I disable onDeviceUI. Though there is no way to navigate and the story is the top of device overlapping with battery indicator. At least it didn't crash with above error.

**Comment by amahajan87** [comment]
Same Issue, even after disabling onDeviceUI, it did not work.

**Comment by dannyhw** [comment]
@amalfra could you include the code where you are using the app registry?

**Comment by amalfra** [comment]
@dannyhw it's
```
AppRegistry.registerComponent(appName, () => StorybookApp);
```
this is inside react native index.js file. StorybookApp has config code that exports the view returned by getStorybookUI.

**Comment by dannyhw** [comment]
@amalfra sorry I mean can you show more of the code like for example the getStorybookUI call etc. Or If possible share a fresh github repo that has the problem for example. If not that's fine it just might take longer for me to get around to this.

**Comment by amalfra** [comment]
@dannyhw below is the code that I use.

```
configure(() => {
  loadStories();
}, module);

addDecorator(addAppWrapper);

// add some margin to prevent overlap with mobile header
addDecorator(story => (
  <ScrollView style={{ marginTop: 50, marginLeft: 5, marginRight: 5 }}>
    <ThemeProvider theme={theme}>
      {story()}
    </ThemeProvider>
  </ScrollView>
));

// Refer to https://github.com/storybookjs/storybook/tree/master/app/react-native#start-command-parameters
// To find allowed options for getStorybookUI
const StorybookUIRoot = getStorybookUI({
  asyncStorage: null,
  port: 9002,
  shouldPersistSelection: false,
  onDeviceUI: false,
});

export default StorybookUIRoot;

```

And I import this file in mobile app and register it using
```
AppRegistry.registerComponent(appName, () => StorybookApp);
```

**Comment by dannyhw** [comment]
@amalfra thanks for the extra info, hopefully I can look at this soon.

**Comment by dannyhw** [comment]
loadstories() seems weird here because in configure usually you just have the story imports

**Comment by amalfra** [comment]
@dannyhw I use https://github.com/elderfo/react-native-storybook-loader and that function just imports the file generated by that package.

**Comment by dannyhw** [comment]
Ok, well did you manage to resolve this issue or is it still happening?

**Comment by amalfra** [comment]
nope, it's still there. I use the version of storybook with the server. Don't use in-app anymore.

**Comment by dannyhw** [comment]
Does it work if you import a story manually? Also this repo uses a mono repo with Lerna and the example app runs ok so I don't think lerna should be an issue. Do you think you can reproduce this issue with a fork of this repo you can use the example app to reproduce the issue. See the contributing documentation (recently updated).

**Comment by amalfra** [comment]
No, even if I import stories manually when in-app mode is used I get this error. Let me try with example app.

**Comment by jeremyeaton89** [comment]
@amalfra any luck with example app? i'm seeing same issue.

**Comment by Nasseratic** [comment]
@amalfra @dannyhw  
Any updates?
Did you find any solution?

**Comment by dannyhw** [comment]
@Nasseratic if you have a reproduction of the issue I could look at it.

**Comment by dannyhw** [comment]
this seems like an old issue related to 5.3 so im closing. Let me know if I should reopen
