### ISSUE TITLE
Unable to use start-storybook when having both react and react native storybook servers

### ISSUE THREAD

**Issue by amalfra** [storybookjs/react-native#72]
**Describe the bug**
I have a monorepo setup with both storybook react and react native installed. But when I install ```@storybook/react-native-server``` package the command start-storybook is replaced with native's server. Is there any way to use both web and native in same package?

**To Reproduce**
1. Install @storybook/react, @storybook/react-native and @storybook/react-native-server
2. try running start-storybook command.
3. it starts mobile server instead of web.

**Expected behavior**
Able to use both servers

**Comment by amalfra** [comment]
for the time being is there any workaround for this?

**Comment by amalfra** [comment]
I managed to find a workaround.
```
"start": "node_modules/@storybook/react/bin/index.js start-storybook -s ../web/public -p 9001 -c src",
"start:mobile": "start-storybook -c src/mobile"
```

But it would be great if storybook by default supports installing both servers without overriding the binaries with same name.

**Comment by dannyhw** [comment]
I've renamed the binaries in v6 to avoid clashes.
