### ISSUE TITLE
Date time picker warning using old react lifecycle methods

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#84]
**Describe the bug**

Date time picker gives a warning in new versions of react native 62+

**To Reproduce**
1. add a date time picker knob to a story
2. open knobs addon tab

**Expected behavior**
Should not give a warning

**Additional context**
might be fixed by updating react-native-modal-datetime-picker dependency

**Comment by kiranjd** [comment]
I would like to take up this issue

**Comment by dannyhw** [comment]
> I would like to take up this issue

Hey thats great to hear, however currently I have a PR open for this #86. I've not merged the changes since it would be a breaking change for people not using expo.

This is because by adding the updated date time picker you need to add a new dependency to knobs which would be @react-native-community/datetimepicker.

However please don't be discouraged and feel free to pick up another issue, I really appreciate your interest in getting involved!

I will mark more issues with good first issue since I realise this is the only one currently

**Comment by dannyhw** [comment]
Expo 39 for web breaks due to these deprecated components so this has become more important to fix now.

**Comment by dannyhw** [comment]
was already fixed
