### ISSUE TITLE
Storybook in app rendering

### ISSUE THREAD

**Issue by fabicsp** [storybookjs/react-native#96]
**Is your feature request related to a problem? Please describe.**

- Is it possible to render the react-native storybook in the app without any dev. server?
- If yes, how?

**Describe the solution you'd like**
- I would like to render the storybook directly in the react-native app

**Comment by pistonsky** [comment]
Yes, it is possible. Create a file `storybook.ts` next to your index.js and then add a new target, and inside build phases where you bundle react native assets add `export ENTRY_FILE=storybook.ts`
